dependencies {
    aopDependencies.each { dep -> implementation dep }
    databaseDependencies.each { dep -> implementation dep }
    testContainersDependencies.each { dep -> implementation dep }
    implementation "commons-io:commons-io:${commonsIoVersion}"
    testImplementation project(":appendix:spring-boot-starter-test-container")
    compileOnly project(":chap01")
}