dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    aopDependencies.each { dep -> implementation dep }
    thymeleafDependencies.each { dep -> implementation dep }
    implementation "commons-io:commons-io:${commonsIoVersion}"
    testContainersDependencies.each { dep -> testImplementation dep }
}