CREATE TABLE IF NOT EXISTS USER
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(255) NOT NULL,
    NICKNAME   VARCHAR(50)  NOT NULL,
    STATUS     INT          NOT NULL DEFAULT 1 COMMENT '1:ON, 2:BLOCK, 3:DORMANT, 4:LEAVE',
    CREATED_AT TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_USER_EMAIL (EMAIL),
    INDEX IDX_USER_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ROLE
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE INT NOT NULL COMMENT '1:ADMINISTRATOR, 2:MANAGER, 3:USER',
    UNIQUE KEY UK_ROLE_TYPE (TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID INT    NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID) ON DELETE CASCADE,
    INDEX IDX_USER_ROLE_USER_ID (USER_ID),
    INDEX IDX_USER_ROLE_ROLE_ID (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ROLE (ID, TYPE) VALUES 
(1, 1), -- ADMINISTRATOR(1, "최고관리자")
(2, 2), -- MANAGER(2, "관리자")  
(3, 3)  -- USER(3, "사용자")
ON DUPLICATE KEY UPDATE TYPE = VALUES(TYPE);

INSERT INTO USER (ID, EMAIL, PASSWORD, NICKNAME, STATUS, CREATED_AT, UPDATED_AT) VALUES 
(1, 'genius@primavera.com', '$2a$10$9OUQiTQ6xiR0xYv8G0FGkOGJsY8PLO6LKUEeNXz4ePgN.NChVF6Ja', 'genius', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'admin@primavera.com', '$2a$10$9OUQiTQ6xiR0xYv8G0FGkOGJsY8PLO6LKUEeNXz4ePgN.NChVF6Ja', 'admin', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'user@primavera.com', '$2a$10$9OUQiTQ6xiR0xYv8G0FGkOGJsY8PLO6LKUEeNXz4ePgN.NChVF6Ja', 'user', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'blocked@primavera.com', '$2a$10$9OUQiTQ6xiR0xYv8G0FGkOGJsY8PLO6LKUEeNXz4ePgN.NChVF6Ja', 'blocked', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES
(1, 1), -- ADMINISTRATOR
(1, 2), -- MANAGER
(1, 3), -- USER
(2, 2), -- MANAGER
(2, 3), -- USER
(3, 3), -- USER
(4, 3)  -- USER
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);