spring:
  application:
    name: privamera
  profiles:
    active: local
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
      test:
        - console-appender

primavera:
  logs:
    path: ./logs