plugins {
    id 'java-library'
    id 'org.springframework.boot' apply false
    id 'io.spring.dependency-management'
}

bootJar.enabled = false
jar.enabled = true

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-configuration-processor'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    api "org.testcontainers:testcontainers:${testContainersVersion}"
    api "org.testcontainers:junit-jupiter:${testContainersVersion}"
    api "org.testcontainers:mariadb:${testContainersVersion}"
    api "org.testcontainers:mysql:${testContainersVersion}"
    api "org.testcontainers:postgresql:${testContainersVersion}"
    api "org.testcontainers:mongodb:${testContainersVersion}"
    api "org.testcontainers:kafka:${testContainersVersion}"
    api "org.testcontainers:elasticsearch:${testContainersVersion}"
    implementation "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    implementation "com.mysql:mysql-connector-j:${mysqlVersion}"
    implementation "org.postgresql:postgresql"
    implementation "org.mongodb:mongodb-driver-sync:${mongodbDriverVersion}"
    implementation "com.zaxxer:HikariCP"
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation "redis.clients:jedis"
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
    testImplementation 'org.mariadb.jdbc:mariadb-java-client'
    testImplementation 'org.postgresql:postgresql'
    testImplementation 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
}