dependencies {
    aopDependencies.each { dep -> implementation dep }
    databaseDependencies.each { dep -> implementation dep }
    mybatisDependencies.each { dep -> implementation dep }
    testContainersDependencies.each { dep -> testImplementation dep }
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springframework.cloud:spring-cloud-starter-vault-config:${springCloudVaultVersion}"
    implementation "org.springframework.cloud:spring-cloud-vault-config-databases:${springCloudVaultVersion}"
    implementation "commons-io:commons-io:${commonsIoVersion}"
    implementation "org.reflections:reflections:${reflectionsVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
    testImplementation "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    testImplementation project(":appendix:spring-boot-starter-test-container")
}