plugins {
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-aop"
    implementation "org.springframework.boot:spring-boot-starter-jdbc"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.mybatis.spring.boot:mybatis-spring-boot-starter:${mybatisSpringBootStarterVersion}"
    implementation "org.mybatis.dynamic-sql:mybatis-dynamic-sql:${mybatisDynamicSqlVersion}"
    implementation "com.mysql:mysql-connector-j:${mysqlVersion}"
    compileOnly "org.hibernate:hibernate-validator:${hibernateValidatorVersion}"
    compileOnly "com.zaxxer:HikariCP:${hikariCPVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.security:spring-security-crypto:${springSecurityVersion}"
    testImplementation "org.mybatis.spring.boot:mybatis-spring-boot-starter-test:${mybatisSpringBootStarterVersion}"
    testImplementation "org.springframework.security:spring-security-test"
    testImplementation "org.mockito:mockito-core:4.+"
    testImplementation "com.mysql:mysql-connector-j:${mysqlVersion}"
    testImplementation "org.testcontainers:testcontainers:${testContainersVersion}"
    testImplementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    testImplementation "org.testcontainers:mysql:${testContainersVersion}"
}