spring:
  config:
    import: optional:configserver:http://localhost:8081
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
  data:
    redis:
      host: localhost
      port: 6379
      username: primavera
      password: primavera
