-- ==============================================
-- Chapter 12 - Advanced Board System with Hierarchical Comments Test Data
-- Uses primavera_test database (TestContainers)
-- Focus: Hierarchical comments, advanced security, board management
-- ==============================================

-- 사용자 테이블 (고급 보안 기능 포함)
CREATE TABLE IF NOT EXISTS USERS
(
    ID                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL                 VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD              VARCHAR(255),
    NICKNAME              VARCHAR(50)         NOT NULL,
    FIRST_NAME            VARCHAR(50),
    LAST_NAME             VARCHAR(50),
    PHONE                 VARCHAR(20),
    PROFILE_IMAGE         VARCHAR(500),
    PROVIDER              VARCHAR(20) DEFAULT 'LOCAL',
    PROVIDER_ID           VARCHAR(100),
    EMAIL_VERIFIED        BOOLEAN     DEFAULT FALSE,
    PHONE_VERIFIED        BOOLEAN     DEFAULT FALSE,
    TWO_FACTOR_ENABLED    BOOLEAN     DEFAULT FALSE,
    FAILED_LOGIN_ATTEMPTS INT         DEFAULT 0,
    ACCOUNT_LOCKED_UNTIL  DATETIME,
    STATUS                INT DEFAULT 1,
    LAST_LOGIN_AT         DATETIME,
    CREATED_AT            DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT            DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX IDX_USERS_EMAIL (EMAIL),
    INDEX IDX_USERS_NICKNAME (NICKNAME),
    INDEX IDX_USERS_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 역할 테이블 (계층형)
CREATE TABLE IF NOT EXISTS ROLES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME   VARCHAR(50) UNIQUE NOT NULL,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (PARENT_ID) REFERENCES ROLES (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자 역할 매핑 테이블
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT   NOT NULL,
    ROLE_ID    BIGINT   NOT NULL,
    GRANTED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE  BOOLEAN  DEFAULT TRUE,
    
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    UNIQUE KEY UK_USER_ROLE (USER_ID, ROLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 게시글 테이블 (계층형 구조)
CREATE TABLE IF NOT EXISTS ARTICLES
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    P_ID             BIGINT,                -- 부모 게시글 ID (계층형)
    REFERENCE        BIGINT,                -- 참조 번호 (그룹)
    STEP             INT DEFAULT 0,         -- 답글 순서
    LEVEL            INT DEFAULT 0,         -- 답글 깊이
    SUBJECT          VARCHAR(200) NOT NULL, -- 제목
    AUTHOR           BIGINT       NOT NULL, -- 작성자 ID
    STATUS           INT DEFAULT 1,         -- 상태 (1: 공개, 0: 비공개)
    HIT              INT DEFAULT 0,         -- 조회수
    RECOMMEND        INT DEFAULT 0,         -- 추천수
    DISAPPROVE       INT DEFAULT 0,         -- 비추천수
    CREATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (P_ID) REFERENCES ARTICLES (ID),
    FOREIGN KEY (AUTHOR) REFERENCES USERS (ID),
    INDEX IDX_ARTICLES_P_ID (P_ID),
    INDEX IDX_ARTICLES_AUTHOR (AUTHOR),
    INDEX IDX_ARTICLES_REFERENCE (REFERENCE),
    INDEX IDX_ARTICLES_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 게시글 내용 테이블
CREATE TABLE IF NOT EXISTS ARTICLE_CONTENT
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID     BIGINT      NOT NULL,
    CONTENTS       LONGTEXT    NOT NULL,
    CREATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID) ON DELETE CASCADE,
    INDEX IDX_ARTICLE_CONTENT_ARTICLE_ID (ARTICLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 게시글 댓글 테이블 (계층형)
CREATE TABLE IF NOT EXISTS ARTICLE_COMMENT
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID     BIGINT      NOT NULL,
    LEVEL          INT         DEFAULT 0,
    STEP           INT         DEFAULT 0,
    COMMENT        TEXT        NOT NULL,
    AUTHOR         BIGINT      NOT NULL,
    STATUS         INT         DEFAULT 1,
    CREATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR) REFERENCES USERS (ID),
    INDEX IDX_ARTICLE_COMMENT_ARTICLE_ID (ARTICLE_ID),
    INDEX IDX_ARTICLE_COMMENT_AUTHOR (AUTHOR)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 테스트 데이터 - Chapter 12: Advanced Board with Hierarchical Comments
INSERT INTO ROLES (ROLE_NAME, ) VALUES
('ROLE_USER', '일반 사용자', 1, TRUE, NULL),
('ROLE_MANAGER', '매니저', 5, TRUE, 1),
('ROLE_ADMINISTRATOR', '관리자', 10, TRUE, 2)
ON DUPLICATE KEY UPDATE ROLE_NAME = VALUES(ROLE_NAME);

INSERT INTO USERS (EMAIL, PASSWORD, NICKNAME, FIRST_NAME, LAST_NAME, EMAIL_VERIFIED, STATUS) VALUES 
('admin@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'SuperAdmin', '슈퍼', '관리자', TRUE, 1),
('manager@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'BoardManager', '게시판', '매니저', TRUE, 1),
('user1@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'TestUser1', '테스트', '사용자1', TRUE, 1)
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES 
(1, 3), -- Admin
(2, 2), -- Manager
(3, 1)  -- User
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);