-- ==============================================
-- Chapter 12 - Advanced Board System with Hierarchical Comments Test Data
-- Uses primavera_test database (TestContainers)
-- Focus: Hierarchical comments, advanced security, board management
-- ==============================================

-- 사용자 테이블 (고급 보안 기능 포함)
CREATE TABLE IF NOT EXISTS USERS
(
    ID                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL                 VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD              VARCHAR(255),
    NICKNAME              VARCHAR(50)         NOT NULL,
    FIRST_NAME            VARCHAR(50),
    LAST_NAME             VARCHAR(50),
    PHONE                 VARCHAR(20),
    PROFILE_IMAGE         VARCHAR(500),
    PROVIDER              VARCHAR(20) DEFAULT 'LOCAL',
    PROVIDER_ID           VARCHAR(100),
    EMAIL_VERIFIED        BOOLEAN     DEFAULT FALSE,
    PHONE_VERIFIED        BOOLEAN     DEFAULT FALSE,
    TWO_FACTOR_ENABLED    BOOLEAN     DEFAULT FALSE,
    FAILED_LOGIN_ATTEMPTS INT         DEFAULT 0,
    ACCOUNT_LOCKED_UNTIL  DATETIME,
    STATUS                VARCHAR(20) DEFAULT 'ACTIVE',
    LAST_LOGIN_AT         DATETIME,
    CREATED_AT            DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT            DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX IDX_USERS_EMAIL (EMAIL),
    INDEX IDX_USERS_NICKNAME (NICKNAME),
    INDEX IDX_USERS_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 역할 테이블 (계층형)
CREATE TABLE IF NOT EXISTS ROLES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME   VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(200),
    LEVEL       INT DEFAULT 0,
    IS_SYSTEM   BOOLEAN DEFAULT FALSE,
    PARENT_ID   BIGINT,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (PARENT_ID) REFERENCES ROLES (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자 역할 매핑 테이블
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT   NOT NULL,
    ROLE_ID    BIGINT   NOT NULL,
    GRANTED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE  BOOLEAN  DEFAULT TRUE,
    
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    UNIQUE KEY UK_USER_ROLE (USER_ID, ROLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 게시판 카테고리 테이블
CREATE TABLE IF NOT EXISTS BOARD_CATEGORIES
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME             VARCHAR(100) NOT NULL,
    DESCRIPTION      TEXT,
    SORT_ORDER       INT     DEFAULT 0,
    READ_PERMISSION  VARCHAR(50) DEFAULT 'ROLE_USER',
    WRITE_PERMISSION VARCHAR(50) DEFAULT 'ROLE_USER',
    ADMIN_PERMISSION VARCHAR(50) DEFAULT 'ROLE_MANAGER',
    STATUS           VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP,
    
    INDEX IDX_BOARD_CATEGORIES_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 게시글 테이블 (고급 기능)
CREATE TABLE IF NOT EXISTS ARTICLES
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_ID      BIGINT,
    TITLE            VARCHAR(200) NOT NULL,
    CONTENT          LONGTEXT     NOT NULL,
    CONTENT_TYPE     VARCHAR(20) DEFAULT 'HTML',
    AUTHOR_ID        BIGINT       NOT NULL,
    VIEW_COUNT       INT         DEFAULT 0,
    LIKE_COUNT       INT         DEFAULT 0,
    COMMENT_COUNT    INT         DEFAULT 0,
    STATUS           VARCHAR(20) DEFAULT 'PUBLISHED',
    IS_NOTICE        BOOLEAN     DEFAULT FALSE,
    IS_PINNED        BOOLEAN     DEFAULT FALSE,
    ALLOW_COMMENTS   BOOLEAN     DEFAULT TRUE,
    PUBLISHED_AT     DATETIME,
    CREATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (CATEGORY_ID) REFERENCES BOARD_CATEGORIES (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID),
    INDEX IDX_ARTICLES_CATEGORY_ID (CATEGORY_ID),
    INDEX IDX_ARTICLES_AUTHOR_ID (AUTHOR_ID),
    INDEX IDX_ARTICLES_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 계층형 댓글 테이블 (Nested Set Model)
CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID     BIGINT      NOT NULL,
    PARENT_ID      BIGINT,
    ROOT_ID        BIGINT,
    AUTHOR_ID      BIGINT      NOT NULL,
    CONTENT        TEXT        NOT NULL,
    STATUS         VARCHAR(20) DEFAULT 'ACTIVE',
    DEPTH          INT         DEFAULT 0,
    LEFT_NODE      INT         NOT NULL,
    RIGHT_NODE     INT         NOT NULL,
    LIKE_COUNT     INT         DEFAULT 0,
    CREATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ID) REFERENCES COMMENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROOT_ID) REFERENCES COMMENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID),
    INDEX IDX_COMMENTS_ARTICLE_ID (ARTICLE_ID),
    INDEX IDX_COMMENTS_NESTED_SET (LEFT_NODE, RIGHT_NODE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 테스트 데이터 - Chapter 12: Advanced Board with Hierarchical Comments
INSERT INTO ROLES (ROLE_NAME, DESCRIPTION, LEVEL, IS_SYSTEM, PARENT_ID) VALUES 
('ROLE_USER', '일반 사용자', 1, TRUE, NULL),
('ROLE_MANAGER', '매니저', 5, TRUE, 1),
('ROLE_ADMINISTRATOR', '관리자', 10, TRUE, 2)
ON DUPLICATE KEY UPDATE ROLE_NAME = VALUES(ROLE_NAME);

INSERT INTO USERS (EMAIL, PASSWORD, NICKNAME, FIRST_NAME, LAST_NAME, EMAIL_VERIFIED, STATUS) VALUES 
('admin@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'SuperAdmin', '슈퍼', '관리자', TRUE, 'ACTIVE'),
('manager@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'BoardManager', '게시판', '매니저', TRUE, 'ACTIVE'),
('user1@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'TestUser1', '테스트', '사용자1', TRUE, 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES 
(1, 3), -- Admin
(2, 2), -- Manager
(3, 1)  -- User
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

INSERT INTO BOARD_CATEGORIES (NAME, DESCRIPTION, SORT_ORDER) VALUES 
('테스트 게시판', '테스트용 게시판입니다.', 1),
('자유게시판', '자유로운 의견을 나누는 공간입니다.', 2)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO ARTICLES (CATEGORY_ID, TITLE, CONTENT, AUTHOR_ID, STATUS, IS_NOTICE, ALLOW_COMMENTS, PUBLISHED_AT) VALUES 
(1, '계층형 댓글 테스트', '<h2>계층형 댓글 시스템 테스트</h2><p>이 게시글은 계층형 댓글 기능을 테스트하기 위한 글입니다.</p>', 1, 'PUBLISHED', TRUE, TRUE, NOW()),
(2, '일반 게시글', '<p>일반적인 게시글 내용입니다.</p>', 2, 'PUBLISHED', FALSE, TRUE, NOW())
ON DUPLICATE KEY UPDATE TITLE = VALUES(TITLE);

-- 계층형 댓글 테스트 데이터 (Nested Set Model)
INSERT INTO COMMENTS (ARTICLE_ID, PARENT_ID, ROOT_ID, AUTHOR_ID, CONTENT, DEPTH, LEFT_NODE, RIGHT_NODE) VALUES 
-- 게시글 1의 댓글들
(1, NULL, NULL, 2, '첫 번째 댓글입니다.', 0, 1, 6),
(1, 1, 1, 3, '첫 번째 댓글에 대한 답글입니다.', 1, 2, 5),
(1, 2, 1, 1, '답글에 대한 답글입니다.', 2, 3, 4),
-- 게시글 1의 두 번째 최상위 댓글
(1, NULL, NULL, 3, '두 번째 댓글입니다.', 0, 7, 8)
ON DUPLICATE KEY UPDATE ARTICLE_ID = VALUES(ARTICLE_ID);