plugins {
    id 'java'
    id 'jacoco'
}

task jacocoRootReport(type: JacocoReport) {
    description = 'Generates an aggregate report from all subprojects'
    group = 'reporting'
    
    // 모든 서브프로젝트의 jacocoTestReport에 의존
    dependsOn {
        subprojects.findAll { 
            it.plugins.hasPlugin('jacoco') 
        }.collect { 
            it.tasks.jacocoTestReport 
        }
    }
    
    subprojects.each { subproject ->
        if (subproject.plugins.hasPlugin('java')) {
            additionalSourceDirs.from(subproject.sourceSets.main.allSource.srcDirs)
            sourceDirectories.from(subproject.sourceSets.main.allSource.srcDirs)  
            classDirectories.from(subproject.sourceSets.main.output)
        }
    }
    
    executionData.from(fileTree(dir: '.', includes: ['**/build/jacoco/test.exec']))
    
    reports {
        xml.required = true
        csv.required = false
        html.required = true
        xml.outputLocation = file("${buildDir}/reports/jacoco/test/jacocoTestReport.xml")
        html.outputLocation = file("${buildDir}/reports/jacoco/test/html")
    }
}

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {

    group = 'com.genius.primavera'
    version = '0.0.1-SNAPSHOT'

    apply plugin: 'java'
    apply plugin: 'jacoco'
    

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation "org.slf4j:slf4j-api:${slf4jVersion}"
        compileOnly "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
        testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
        testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    }

    test {
        useJUnitPlatform()
        finalizedBy jacocoTestReport
    }
    
    jacocoTestReport {
        dependsOn test
        reports {
            xml.required = true
            csv.required = false
            html.required = true
        }
    }
}
