rootProject.name = 'primavera'
include 'chap01'
include 'chap02'
include 'chap03'
include 'chap04'
//include 'chap05'
//include 'chap06'
//include 'chap07'
//include 'chap08'
//include 'chap09'
//include 'chap10'
//include 'chap11'
//include 'chap12'
//include 'chap13'
//include 'chap14'
//include 'chap15'
//include 'chap15:account'
//include 'chap15:configuration'
//include 'chap15:front'
//include 'chap15:order'
//include 'chap15:product'
//include 'chap16'
//include 'chap17'
//include 'chap18'
include 'preface'
include 'appendix:spring-boot-starter-lucy-filter'
include 'appendix:spring-boot-starter-social-kakao'
include 'appendix:spring-boot-starter-test-container'