rootProject.name = 'primavera'
//include 'chap01'
//include 'chap02'
//include 'chap03'
//include 'chap04'
//include 'chap05'
//include 'chap06'
//include 'chap07'
//include 'chap08'
//include 'chap09'
//include 'chap10'
//include 'chap11'
//include 'chap12'
//include 'chap13'
//include 'chap14'
//include 'chap15'
//include 'chap16'
//include 'chap17:batch'
//include 'chap17:streaming'
//include 'chap18:account'
//include 'chap18:configuration'
//include 'chap18:front'
//include 'chap18:order'
//include 'chap18:product'
//include 'preface'
//include 'appendix:spring-boot-starter-lucy-filter'
//include 'appendix:spring-boot-test-support'
include 'appendix:spring-boot-starter-testcontainer'