plugins {
    id 'org.springframework.boot' version '3.5.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

compileJava {
    options.compilerArgs += ["-Xlint:deprecation"]
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web") {
        exclude module: "spring-boot-starter-tomcat"
    }
    implementation("org.springframework.boot:spring-boot-starter-undertow")
    implementation "org.springframework.boot:spring-boot-starter-aop"
    implementation "org.springframework.boot:spring-boot-starter-jdbc"
    implementation "org.springframework.boot:spring-boot-starter-thymeleaf"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-security"
    implementation "org.springframework.boot:spring-boot-starter-oauth2-client"
    implementation "org.springframework.security:spring-security-oauth2-client:${springSecurityVersion}"
    implementation "org.springframework.security:spring-security-oauth2-jose:${springSecurityVersion}"
    implementation "org.springframework.boot:spring-boot-devtools"
    implementation "com.github.gavlyukovskiy:p6spy-spring-boot-starter:${p6spySpringBootStarterVersion}"
    implementation "org.thymeleaf.extras:thymeleaf-extras-springsecurity6:${thymeleafExtrasSpringSecurity6Version}"
    implementation "org.mybatis.spring.boot:mybatis-spring-boot-starter:${mybatisSpringBootStarterVersion}"
    implementation "org.mybatis.dynamic-sql:mybatis-dynamic-sql:${mybatisDynamicSqlVersion}"
    implementation "com.mysql:mysql-connector-j:${mysqlVersion}"
    implementation "org.hibernate:hibernate-core:${hibernateVersion}"
    implementation "nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:${thymeleafLayoutDialectVersion}"
    implementation "org.graalvm.js:js:${graalvmJsVersion}"
    implementation "org.graalvm.js:js-scriptengine:${graalvmJsVersion}"
    implementation "org.webjars:bootstrap:${bootstrapVersion}"
    implementation "org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4.1:${log4jdbcLog4j2Version}"
    implementation "commons-codec:commons-codec:${commonsCodecVersion}"
    compileOnly "org.jetbrains:annotations:${jetbrainsAnnotationsVersion}"
    compileOnly "jakarta.validation:jakarta.validation-api:${javaxValidationVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.security:spring-security-test:${springSecurityVersion}"
    testImplementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    testImplementation "org.testcontainers:mysql:${testContainersVersion}"
    testImplementation "io.rest-assured:rest-assured:5.3.2"
    implementation "com.navercorp.lucy:lucy-xss-servlet:${lucyXssServletVersion}"
}