spring:
  application:
    name: MvcAopApplication
  jackson:
    time-zone: UTC

server:
  tomcat:
    use-apr: never

logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug

primavera:
  logs:
    path: ./logs
