spring:
  config:
    activate:
      on-profile: default
  application:
    name: primavera-chapter-03
  jackson:
    time-zone: UTC
  banner:
    charset: UTF-8
    location: classpath:primavera.txt

server:
  tomcat:
    use-apr: never

logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug
