spring:
  application:
    name: MvcAopApplication
  jackson:
    time-zone: UTC
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug
