spring:
  application:
    name: Privamera
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/primavera
    username: primavera
    password: primavera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt

logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug