spring:
  config:
    activate:
      on-profile: local
    import:
      - "optional:vault:"
      - "optional:configserver:"
  aop:
    proxy-target-class: true
  cloud:
    config:
      enabled: true
    vault:
      enabled: true
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: primavera-vault-token
      connection-timeout: 5000
      read-timeout: 15000
      fail-fast: false
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: VaadinApplication
        application-name: VaadinApplication
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: "BalancedHikariPool"
      leak-detection-threshold: 60000
      connection-test-query: "SELECT 1"
      validation-timeout: 5000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
    cache-enabled: false
    local-cache-scope: statement
  type-aliases-package: com.genius.primavera.domain
  type-handlers-package: com.genius.primavera.domain