dependencies {
    implementation "org.projectlombok:lombok:${lombokVersion}"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation "org.springframework.cloud:spring-cloud-starter-bootstrap"
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    runtimeOnly "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    testImplementation "io.projectreactor:reactor-test:${reactorTestVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
}