-- ==============================================
-- Chapter 07 - MyBatis Advanced Mapping Test Data
-- Uses primavera_test database (TestContainers)
-- ==============================================

-- 공통 테스트 사용자 테이블
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 권한 테이블
CREATE TABLE IF NOT EXISTS ROLES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    TYPE        INT                NOT NULL,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자-권한 연결 테이블
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_USER_ROLE (USER_ID, ROLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Chapter 07 특화 테이블 - MYBATIS 접두사 사용
-- 상속 매핑 전략 테스트
CREATE TABLE IF NOT EXISTS MYBATIS_ITEMS
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE   VARCHAR(10)  NOT NULL,
    NAME   VARCHAR(100) NOT NULL,
    PRICE  INT          NOT NULL DEFAULT 0,
    ARTIST VARCHAR(100),
    AUTHOR VARCHAR(100),
    ISBN   VARCHAR(20),
    INDEX IDX_TYPE (TYPE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_CONTACTS
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE   VARCHAR(10) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_ADDRESSES
(
    ID      BIGINT PRIMARY KEY,
    COUNTRY VARCHAR(100),
    CITY    VARCHAR(100),
    STREET  VARCHAR(200),
    ZIPCODE VARCHAR(20),
    FOREIGN KEY (ID) REFERENCES MYBATIS_CONTACTS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_EMAILS
(
    ID            BIGINT PRIMARY KEY,
    EMAIL_ADDRESS VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID) REFERENCES MYBATIS_CONTACTS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_MOBILES
(
    ID           BIGINT PRIMARY KEY,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID) REFERENCES MYBATIS_CONTACTS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_TABLE_SEQ
(
    SEQUENCE_NAME VARCHAR(50) PRIMARY KEY,
    NEXT_VAL      BIGINT NOT NULL DEFAULT 1
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

INSERT INTO MYBATIS_TABLE_SEQ (SEQUENCE_NAME, NEXT_VAL)
VALUES ('table_generator', 1)
ON DUPLICATE KEY UPDATE NEXT_VAL = NEXT_VAL;

CREATE TABLE IF NOT EXISTS MYBATIS_CANIDAE
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    SPECIES    VARCHAR(100),
    HABITAT    VARCHAR(200)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_FELIDAE
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    BREED      VARCHAR(100),
    TERRITORY  VARCHAR(200)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_SCINCIDAE
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LENGTH_CM  INT,
    HABITAT    VARCHAR(200)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_PROFESSORS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    COURSE     VARCHAR(100)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_STUDENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEPARTMENT VARCHAR(100)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 기본 테스트 데이터
INSERT INTO ROLES (ID, NAME, DESCRIPTION, TYPE)
VALUES (1, 'ROLE_ADMIN', '테스트 관리자', 1),
       (2, 'ROLE_MANAGER', '테스트 매니저', 2),
       (3, 'ROLE_USER', '테스트 사용자', 3)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS)
VALUES (1, 'genius@primavera.com', '{noop}test', 'Genius', 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (1, 1), (1, 2), (1, 3)
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

-- Chapter 07 특화 테스트 데이터
INSERT INTO MYBATIS_ITEMS (ID, TYPE, NAME, PRICE)
VALUES (1, 'BOOK', 'Advanced MyBatis', 35000),
       (2, 'ALBUM', 'Spring Jazz', 18000),
       (3, 'MOVIE', 'Database Design', 15000)
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO MYBATIS_CONTACTS (ID, TYPE)
VALUES (1, 'ADDRESS'),
       (2, 'EMAIL'),
       (3, 'MOBILE')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO MYBATIS_ADDRESSES (ID, COUNTRY, CITY, STREET, ZIPCODE)
VALUES (1, 'South Korea', 'Seoul', 'Gangnam-gu', '12345')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO MYBATIS_EMAILS (ID, EMAIL_ADDRESS)
VALUES (2, 'test@primavera.com')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO MYBATIS_MOBILES (ID, PHONE_NUMBER)
VALUES (3, '010-1234-5678')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);