-- chap06 Database Schema
-- MySQL Database Schema for Primavera Application

CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(255) NOT NULL,
    NICKNAME   VARCHAR(50)  NOT NULL,
    STATUS     INT          NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_USER_EMAIL (EMAIL),
    INDEX IDX_USER_STATUS (STATUS)
);

CREATE TABLE IF NOT EXISTS ROLES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE INT NOT NULL,
    UNIQUE KEY UK_ROLE_TYPE (TYPE)
);

CREATE TABLE IF NOT EXISTS USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE
);

-- Single Table Inheritance Strategy (Item hierarchy)
CREATE TABLE IF NOT EXISTS ITEM
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE   VARCHAR(10)  NOT NULL,
    NAME   VARCHAR(100) NOT NULL,
    PRICE  INT          NOT NULL DEFAULT 0,
    ARTIST VARCHAR(100),
    AUTHOR VARCHAR(100),
    ISBN   VARCHAR(20),
    INDEX IDX_ITEM_TYPE (TYPE)
);

CREATE TABLE IF NOT EXISTS CONTACT
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE   VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ADDRESS
(
    ID      BIGINT PRIMARY KEY,
    COUNTRY VARCHAR(100),
    CITY    VARCHAR(100),
    STREET  VARCHAR(200),
    ZIPCODE VARCHAR(20),
    FOREIGN KEY (ID) REFERENCES CONTACT (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EMAIL
(
    ID            BIGINT PRIMARY KEY,
    EMAIL_ADDRESS VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID) REFERENCES CONTACT (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MOBILE
(
    ID           BIGINT PRIMARY KEY,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID) REFERENCES CONTACT (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TABLE_SEQ
(
    SEQUENCE_NAME VARCHAR(50) PRIMARY KEY,
    NEXT_VAL      BIGINT NOT NULL DEFAULT 1
);

INSERT INTO TABLE_SEQ (SEQUENCE_NAME, NEXT_VAL)
VALUES ('table_generator', 1)
ON DUPLICATE KEY UPDATE NEXT_VAL = NEXT_VAL;

CREATE TABLE IF NOT EXISTS CANIDAE
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    SPECIES    VARCHAR(100),
    HABITAT    VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS FELIDAE
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    BREED      VARCHAR(100),
    TERRITORY  VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS SCINCIDAE
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LENGTH_CM  INT,
    HABITAT    VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS PROFESSOR
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    COURSE     VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS STUDENT
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DEPARTMENT VARCHAR(100)
);

-- Insert initial data
INSERT INTO ROLES (ID, TYPE)
VALUES (1, 1), -- ADMINISTRATOR
       (2, 2), -- MANAGER
       (3, 3)  -- USER
ON DUPLICATE KEY UPDATE TYPE = VALUES(TYPE);

INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS, CREATED_AT, UPDATED_AT) 
VALUES (1, 'genius@primavera.com', '$2a$10$9OUQiTQ6xiR0xYv8G0FGkOGJsY8PLO6LKUEeNXz4ePgN.NChVF6Ja', 'genius', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);