plugins {
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    implementation "org.springframework:spring-web"
    implementation "org.springframework:spring-webmvc"
    implementation "org.springframework:spring-context"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-autoconfigure-processor"
    implementation "jakarta.servlet:jakarta.servlet-api:${jakartaServletVersion}"
    implementation "org.apache.commons:commons-lang3:${commonsLangVersion}"
    implementation "org.apache.commons:commons-text:${commonsTextVersion}"
    implementation "commons-codec:commons-codec"
    implementation "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testImplementation "org.projectlombok:lombok:${lombokVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}