-- ==============================================
-- Chapter 16 - File Processing and Batch Operations Test Data
-- Uses primavera_test database (TestContainers)
-- Focus: File upload/download, batch processing, scheduled tasks
-- ==============================================

-- 사용자 테이블
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX IDX_USERS_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 파일 정보 테이블 (고급 파일 관리)
CREATE TABLE IF NOT EXISTS FILE_METADATA
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORIGINAL_NAME    VARCHAR(255) NOT NULL,
    STORED_NAME      VARCHAR(255) NOT NULL,
    FILE_PATH        VARCHAR(500) NOT NULL,
    FILE_SIZE        BIGINT       NOT NULL,
    CONTENT_TYPE     VARCHAR(100),
    FILE_HASH        VARCHAR(64),          -- SHA-256 해시
    UPLOAD_USER_ID   BIGINT       NOT NULL,
    DOWNLOAD_COUNT   INT          DEFAULT 0,
    IS_PUBLIC        BOOLEAN      DEFAULT FALSE,
    IS_PROCESSED     BOOLEAN      DEFAULT FALSE,
    PROCESSING_STATUS VARCHAR(20)  DEFAULT 'PENDING', -- PENDING, PROCESSING, COMPLETE, FAILED
    THUMBNAIL_PATH   VARCHAR(500),         -- 이미지 썸네일 경로
    FILE_TYPE        VARCHAR(50),          -- IMAGE, DOCUMENT, ARCHIVE, VIDEO, AUDIO, OTHER
    METADATA_JSON    JSON,                 -- 파일 메타데이터 (EXIF, 문서 정보 등)
    CREATED_AT       DATETIME     DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (UPLOAD_USER_ID) REFERENCES USERS (ID),
    INDEX IDX_FILE_METADATA_HASH (FILE_HASH),
    INDEX IDX_FILE_METADATA_TYPE (FILE_TYPE),
    INDEX IDX_FILE_METADATA_STATUS (PROCESSING_STATUS),
    INDEX IDX_FILE_METADATA_USER (UPLOAD_USER_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 배치 작업 테이블
CREATE TABLE IF NOT EXISTS BATCH_JOBS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    JOB_NAME       VARCHAR(100) NOT NULL,
    JOB_TYPE       VARCHAR(50)  NOT NULL, -- FILE_PROCESS, DATA_IMPORT, REPORT_GENERATION
    STATUS         VARCHAR(20)  DEFAULT 'PENDING', -- PENDING, RUNNING, COMPLETED, FAILED
    TOTAL_ITEMS    INT          DEFAULT 0,
    PROCESSED_ITEMS INT         DEFAULT 0,
    FAILED_ITEMS   INT          DEFAULT 0,
    START_TIME     DATETIME,
    END_TIME       DATETIME,
    ERROR_MESSAGE  TEXT,
    PARAMETERS     JSON,                   -- 작업 파라미터
    CREATED_BY     BIGINT       NOT NULL,
    CREATED_AT     DATETIME     DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
    INDEX IDX_BATCH_JOBS_TYPE (JOB_TYPE),
    INDEX IDX_BATCH_JOBS_STATUS (STATUS),
    INDEX IDX_BATCH_JOBS_CREATED_AT (CREATED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 배치 작업 아이템 테이블
CREATE TABLE IF NOT EXISTS BATCH_JOB_ITEMS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    JOB_ID         BIGINT       NOT NULL,
    ITEM_ID        VARCHAR(100) NOT NULL,
    ITEM_TYPE      VARCHAR(50)  NOT NULL,
    STATUS         VARCHAR(20)  DEFAULT 'PENDING',
    ERROR_MESSAGE  TEXT,
    PROCESSED_AT   DATETIME,
    PROCESSING_TIME_MS BIGINT,
    RESULT_DATA    JSON,                   -- 처리 결과 데이터
    
    FOREIGN KEY (JOB_ID) REFERENCES BATCH_JOBS (ID) ON DELETE CASCADE,
    INDEX IDX_BATCH_ITEMS_JOB_ID (JOB_ID),
    INDEX IDX_BATCH_ITEMS_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 파일 다운로드 로그 테이블
CREATE TABLE IF NOT EXISTS FILE_DOWNLOAD_LOGS
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_ID         BIGINT       NOT NULL,
    DOWNLOAD_USER_ID BIGINT,
    IP_ADDRESS      VARCHAR(45),
    USER_AGENT      VARCHAR(500),
    REFERER         VARCHAR(500),
    DOWNLOAD_TIME   DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (FILE_ID) REFERENCES FILE_METADATA (ID) ON DELETE CASCADE,
    FOREIGN KEY (DOWNLOAD_USER_ID) REFERENCES USERS (ID),
    INDEX IDX_DOWNLOAD_LOGS_FILE_ID (FILE_ID),
    INDEX IDX_DOWNLOAD_LOGS_USER_ID (DOWNLOAD_USER_ID),
    INDEX IDX_DOWNLOAD_LOGS_TIME (DOWNLOAD_TIME)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 파일 처리 규칙 테이블
CREATE TABLE IF NOT EXISTS FILE_PROCESSING_RULES
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    RULE_NAME         VARCHAR(100) NOT NULL,
    FILE_TYPE_PATTERN VARCHAR(255) NOT NULL, -- MIME type pattern
    PROCESSING_ACTION VARCHAR(50)  NOT NULL, -- THUMBNAIL, COMPRESS, SCAN, EXTRACT_TEXT
    PARAMETERS        JSON,                   -- 처리 파라미터
    ACTIVE            BOOLEAN      DEFAULT TRUE,
    CREATED_AT        DATETIME     DEFAULT CURRENT_TIMESTAMP,
    
    INDEX IDX_PROCESSING_RULES_ACTIVE (ACTIVE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 테스트 데이터 - Chapter 16: File Processing and Batch Operations
INSERT INTO USERS (EMAIL, PASSWORD, NICKNAME, STATUS) VALUES 
('fileadmin@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'FileAdmin', 'ACTIVE'),
('batchuser@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'BatchUser', 'ACTIVE'),
('uploader@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'Uploader', 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO FILE_METADATA (ORIGINAL_NAME, STORED_NAME, FILE_PATH, FILE_SIZE, CONTENT_TYPE, FILE_HASH, UPLOAD_USER_ID, FILE_TYPE, IS_PROCESSED, PROCESSING_STATUS) VALUES 
('sample-document.pdf', 'doc-20241201-001.pdf', '/uploads/documents/doc-20241201-001.pdf', 2048000, 'application/pdf', 'sha256-hash-001', 1, 'DOCUMENT', TRUE, 'COMPLETE'),
('profile-image.jpg', 'img-20241201-001.jpg', '/uploads/images/img-20241201-001.jpg', 512000, 'image/jpeg', 'sha256-hash-002', 2, 'IMAGE', TRUE, 'COMPLETE'),
('data-export.xlsx', 'excel-20241201-001.xlsx', '/uploads/data/excel-20241201-001.xlsx', 1024000, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'sha256-hash-003', 3, 'DOCUMENT', FALSE, 'PENDING'),
('video-sample.mp4', 'video-20241201-001.mp4', '/uploads/videos/video-20241201-001.mp4', 10485760, 'video/mp4', 'sha256-hash-004', 1, 'VIDEO', FALSE, 'PROCESSING')
ON DUPLICATE KEY UPDATE ORIGINAL_NAME = VALUES(ORIGINAL_NAME);

INSERT INTO BATCH_JOBS (JOB_NAME, JOB_TYPE, STATUS, TOTAL_ITEMS, PROCESSED_ITEMS, FAILED_ITEMS, START_TIME, END_TIME, CREATED_BY) VALUES 
('Image Thumbnail Generation', 'FILE_PROCESS', 'COMPLETED', 10, 10, 0, '2024-01-20 09:00:00', '2024-01-20 09:15:00', 1),
('Daily Report Generation', 'REPORT_GENERATION', 'COMPLETED', 1, 1, 0, '2024-01-21 02:00:00', '2024-01-21 02:05:00', 1),
('File Cleanup Task', 'FILE_PROCESS', 'RUNNING', 50, 25, 2, '2024-01-22 03:00:00', NULL, 2),
('Data Import Job', 'DATA_IMPORT', 'PENDING', 100, 0, 0, NULL, NULL, 3)
ON DUPLICATE KEY UPDATE JOB_NAME = VALUES(JOB_NAME);

INSERT INTO BATCH_JOB_ITEMS (JOB_ID, ITEM_ID, ITEM_TYPE, STATUS, PROCESSED_AT, PROCESSING_TIME_MS) VALUES 
(1, 'file-001', 'IMAGE', 'COMPLETED', '2024-01-20 09:05:00', 1500),
(1, 'file-002', 'IMAGE', 'COMPLETED', '2024-01-20 09:06:00', 1200),
(3, 'cleanup-001', 'TEMP_FILE', 'COMPLETED', '2024-01-22 03:10:00', 500),
(3, 'cleanup-002', 'TEMP_FILE', 'FAILED', '2024-01-22 03:11:00', 100)
ON DUPLICATE KEY UPDATE JOB_ID = VALUES(JOB_ID);

INSERT INTO FILE_DOWNLOAD_LOGS (FILE_ID, DOWNLOAD_USER_ID, IP_ADDRESS, USER_AGENT) VALUES 
(1, 2, '192.168.1.100', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'),
(1, 3, '192.168.1.101', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'),
(2, 2, '192.168.1.100', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'),
(3, 1, '192.168.1.102', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36')
ON DUPLICATE KEY UPDATE FILE_ID = VALUES(FILE_ID);

INSERT INTO FILE_PROCESSING_RULES (RULE_NAME, FILE_TYPE_PATTERN, PROCESSING_ACTION, PARAMETERS, ACTIVE) VALUES 
('Image Thumbnail', 'image/*', 'THUMBNAIL', '{"width": 300, "height": 300, "quality": 85}', TRUE),
('Image Compression', 'image/jpeg', 'COMPRESS', '{"quality": 80, "progressive": true}', TRUE),
('Document Text Extraction', 'application/pdf', 'EXTRACT_TEXT', '{"ocr": false, "language": "ko"}', TRUE),
('Video Thumbnail', 'video/*', 'THUMBNAIL', '{"timestamp": "00:00:05", "width": 640, "height": 360}', TRUE)
ON DUPLICATE KEY UPDATE RULE_NAME = VALUES(RULE_NAME);