
plugins {
    id 'org.graalvm.buildtools.native' version '0.10.3'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    implementation project(':chap17:common')
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    runtimeOnly "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    implementation "co.elastic.clients:elasticsearch-java:${elasticsearchVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVersion}"
    implementation "org.apache.commons:commons-lang3:${commonsLang3Version}"
    implementation "org.apache.commons:commons-csv:${commonsCsvVersion}"
    implementation "io.debezium:debezium-embedded:${debeziumVersion}"
    implementation "io.debezium:debezium-connector-mysql:${debeziumVersion}"
    implementation "io.debezium:debezium-api:${debeziumVersion}"
    implementation "io.debezium:debezium-core:${debeziumVersion}"
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
    testImplementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    testImplementation "org.testcontainers:mariadb:${testContainersVersion}"
    testImplementation "org.testcontainers:elasticsearch:${testContainersVersion}"
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation project(':appendix:spring-boot-starter-test-containers')
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.named('test') {
    useJUnitPlatform()
}

graalvmNative {
    binaries {
        main {
            imageName = 'product-batch-indexer'
            mainClass = 'com.genius.primavera.ProductBatchApplication'
            useFatJar = false
        }
    }
}

springBoot {
    mainClass = 'com.genius.primavera.ProductBatchApplication'
    buildInfo()
}

jar {
    enabled = false
    archiveClassifier = ''
}

bootJar {
    archiveFileName = 'product-batch-indexer.jar'
    launchScript()
}