dependencies {
    implementation "com.fasterxml.jackson.core:jackson-databind"
    implementation "org.aspectj:aspectjweaver"
    implementation "org.projectlombok:lombok:${lombokVersion}"
    implementation "org.springframework.boot:spring-boot-starter-aop"
    implementation "org.springframework.boot:spring-boot-starter-cache"
    implementation "org.springframework.boot:spring-boot-starter-data-mongodb-reactive"
    implementation "org.springframework.boot:spring-boot-starter-data-redis"
    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation "org.springframework.cloud:spring-cloud-starter-bootstrap"
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springframework.kafka:spring-kafka"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    runtimeOnly "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    testImplementation "io.projectreactor:reactor-test:${reactorTestVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.kafka:spring-kafka-test"
}