dependencies {
    implementation("jakarta.annotation:jakarta.annotation-api")
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude module: 'junit'
        exclude module: 'junit-vintage-engine'
    }
}

bootJar {
    mainClass.set("com.genius.primavera.PrimaveraApplication")
}