dependencies {
    // Implementation dependencies (alphabetical)
    implementation "jakarta.annotation:jakarta.annotation-api:${javaxAnnotationVersion}"
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-web"
}

bootJar {
    mainClass.set("com.genius.primavera.PrimaveraApplication")
}