CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_USERS_EMAIL (EMAIL)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

INSERT INTO USERS (ID, EMAIL, NICKNAME)
VALUES (1, 'test@primavera.com', 'TestUser'),
       (2, 'demo@primavera.com', 'DemoUser')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);
