  redis-${CHAPTER}:
    image: redis:7.4.1-alpine
    container_name: redis-primavera-${CHAPTER}
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-${CHAPTER}-data:/data
    command: >
      sh -c "echo 'user primavera on >primavera ~* &* +@all' > /tmp/redis.conf &&
             echo 'appendonly yes' >> /tmp/redis.conf &&
             echo 'requirepass primavera' >> /tmp/redis.conf &&
             redis-server /tmp/redis.conf"
    healthcheck:
      test: ["CMD", "redis-cli", "-u", "primavera", "-a", "primavera", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ${CHAPTER}-network