spring:
  application:
    name: AdvancedAuthorizationApplication
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  profiles:
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
      test:
        - console-appender
  jackson:
    time-zone: UTC

lucy-filter:
  name: lucyXssFilter
  order: 1
  addUrlPatterns: /*

logging:
  config: classpath:logback-spring.xml

server:
  http2:
    enabled: true
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    key-alias: primavera
    key-store: classpath:certs/primavera.p12
    key-store-type: PKCS12
    key-store-password: primavera
  port: 8443

storage:
  location: upload

primavera:
  logs:
    path: ./logs