spring:
  application:
    name: SecurityFilterApplication
  profiles:
    active: local
  jackson:
    time-zone: UTC
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
      test:
        - console-appender
  main:
    allow-bean-definition-overriding: true

  lucy-filter:
    enabled: true
    name: lucyXssFilter
    order: 1
    addUrlPatterns: /*

primavera:
  logs:
    path: ./logs