CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT(20)   NOT NULL AUTO_INCREMENT,
    EMAIL      VARCHAR(50)  NOT NULL,
    PASSWORD   VARCHAR(100) NOT NULL,
    NICKNAME   VARCHAR(45)  NOT NULL,
    STATUS     INT(1)      NOT NULL DEFAULT 1,
    CREATED_AT DATETIME     NOT NULL,
    UPDATED_AT DATETIME              DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY EMAIL_UNIQUE (EMAIL)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ROLES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(255) NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID         BIGINT(20) NOT NULL AUTO_INCREMENT,
    USER_ID    BIGINT(20) NOT NULL,
    ROLE_ID    BIGINT(20) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    UNIQUE KEY USER_ROLE_UNIQUE (USER_ID, ROLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS WINNERS
(
    ID     BIGINT(20)  NOT NULL AUTO_INCREMENT,
    NAME   VARCHAR(50) NOT NULL,
    YEAR   INT         NOT NULL,
    SPORT  VARCHAR(50) NOT NULL,
    PRIZE  VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(10, 2) DEFAULT 0.00,
    PRIMARY KEY (ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

INSERT INTO ROLES(TYPE)
VALUES (1),
       (2),
       (3);


INSERT INTO WINNERS(NAME, YEAR, SPORT, PRIZE, AMOUNT)
VALUES ('Lionel Messi', 2023, 'Football', 'Ballon d''Or', 1000000.00),
       ('Erling Haaland', 2023, 'Football', 'Golden Boot', 500000.00),
       ('Lewis Hamilton', 2023, 'Formula 1', 'World Championship', 2000000.00),
       ('Serena Williams', 2023, 'Tennis', 'Wimbledon', 750000.00),
       ('Tiger Woods', 2023, 'Golf', 'Masters Tournament', 1500000.00);