-- USERS 테이블 생성 (H2 호환)
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     INT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
-- 인덱스는 별도의 구문으로 생성
CREATE INDEX IDX_EMAIL ON USERS (EMAIL);
CREATE INDEX IDX_STATUS ON USERS (STATUS);


-- ROLES 테이블 생성 (H2 호환)
CREATE TABLE IF NOT EXISTS ROLES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    TYPE        INT                NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );


-- USER_ROLES 테이블 생성 (H2 호환)
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    -- UNIQUE KEY를 표준 UNIQUE 제약조건으로 변경
    CONSTRAINT UNIQUE_USER_ROLE UNIQUE (USER_ID, ROLE_ID)
    );


-- WINNERS 테이블 생성 (H2 호환)
CREATE TABLE IF NOT EXISTS WINNERS (
                                       ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                                       NAME VARCHAR(50) NOT NULL,
    "YEAR" INT NOT NULL, -- YEAR는 예약어이므로 큰따옴표로 감싸기
    SPORT VARCHAR(50) NOT NULL,
    PRIZE VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(10, 2) DEFAULT 0.00
    );
-- 인덱스는 별도의 구문으로 생성
CREATE INDEX IDX_YEAR ON WINNERS("YEAR");
CREATE INDEX IDX_SPORT ON WINNERS(SPORT);
