dependencies {
    // Implementation dependencies (alphabetical)
    implementation "com.querydsl:querydsl-apt"
    implementation "com.querydsl:querydsl-jpa"
    implementation "com.squareup.retrofit2:converter-jackson:${retrofitVersion}"
    implementation "com.squareup.retrofit2:retrofit:${retrofitVersion}"
    implementation "jakarta.persistence:jakarta.persistence-api"
    implementation "org.hibernate:hibernate-envers:${hibernateEnversVersion}"
    implementation "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    implementation "org.springframework.boot:spring-boot-starter-data-mongodb-reactive"
    implementation "org.springframework.boot:spring-boot-starter-data-redis-reactive"
    implementation "org.springframework.boot:spring-boot-starter-jdbc"
    implementation "org.springframework.boot:spring-boot-starter-oauth2-client"
    implementation "org.springframework.boot:spring-boot-starter-security"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation "org.springframework.data:spring-data-envers"
    
    // Annotation processors
    annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jpa"
    
    // Test implementation dependencies (alphabetical)
    testImplementation "io.projectreactor:reactor-test:${reactorTestVersion}"
    testImplementation "org.springframework.security:spring-security-test"
    testImplementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    testImplementation "org.testcontainers:mariadb:${testContainersVersion}"
    testImplementation "org.testcontainers:mongodb:${testContainersVersion}"
    testImplementation project(':appendix:spring-boot-starter-test-containers')
}

def querydslSrcDir = 'src/main/java'

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', querydslSrcDir]
        }
    }
}