-- ==============================================
-- Chapter 13 - Enhanced Board System with Analytics Test Data
-- Uses primavera_test database (TestContainers)
-- Focus: Board analytics, file uploads, enhanced security, logging
-- ==============================================

-- 사용자 테이블 (고급 보안 기능)
CREATE TABLE IF NOT EXISTS USERS
(
    ID                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL                 VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD              VARCHAR(255),
    NICKNAME              VARCHAR(50)         NOT NULL,
    FIRST_NAME            VARCHAR(50),
    LAST_NAME             VARCHAR(50),
    PHONE                 VARCHAR(20),
    PROFILE_IMAGE         VARCHAR(500),
    PROVIDER              VARCHAR(20) DEFAULT 'LOCAL',
    EMAIL_VERIFIED        BOOLEAN     DEFAULT FALSE,
    TWO_FACTOR_ENABLED    BOOLEAN     DEFAULT FALSE,
    FAILED_LOGIN_ATTEMPTS INT         DEFAULT 0,
    STATUS                VARCHAR(20) DEFAULT 'ACTIVE',
    LAST_LOGIN_AT         DATETIME,
    CREATED_AT            DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT            DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX IDX_USERS_EMAIL (EMAIL),
    INDEX IDX_USERS_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 역할 테이블
CREATE TABLE IF NOT EXISTS ROLES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME   VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(200),
    LEVEL       INT DEFAULT 0,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자 역할 매핑
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    UNIQUE KEY UK_USER_ROLE (USER_ID, ROLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 게시글 테이블 (고급 기능 포함)
CREATE TABLE IF NOT EXISTS ARTICLES
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE            VARCHAR(200) NOT NULL,
    CONTENT          LONGTEXT     NOT NULL,
    AUTHOR_ID        BIGINT       NOT NULL,
    VIEW_COUNT       INT         DEFAULT 0,
    LIKE_COUNT       INT         DEFAULT 0,
    COMMENT_COUNT    INT         DEFAULT 0,
    STATUS           VARCHAR(20) DEFAULT 'PUBLISHED',
    IS_NOTICE        BOOLEAN     DEFAULT FALSE,
    IS_PINNED        BOOLEAN     DEFAULT FALSE,
    ALLOW_COMMENTS   BOOLEAN     DEFAULT TRUE,
    HAS_ATTACHMENTS  BOOLEAN     DEFAULT FALSE,
    PUBLISHED_AT     DATETIME,
    CREATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID),
    INDEX IDX_ARTICLES_AUTHOR_ID (AUTHOR_ID),
    INDEX IDX_ARTICLES_STATUS (STATUS),
    INDEX IDX_ARTICLES_CREATED_AT (CREATED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 계층형 댓글 테이블
CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID BIGINT      NOT NULL,
    PARENT_ID  BIGINT,
    AUTHOR_ID  BIGINT      NOT NULL,
    CONTENT    TEXT        NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    DEPTH      INT         DEFAULT 0,
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ID) REFERENCES COMMENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID),
    INDEX IDX_COMMENTS_ARTICLE_ID (ARTICLE_ID),
    INDEX IDX_COMMENTS_PARENT_ID (PARENT_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 첨부파일 테이블 (고급 기능)
CREATE TABLE IF NOT EXISTS ATTACHMENTS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID     BIGINT       NOT NULL,
    ORIGINAL_NAME  VARCHAR(255) NOT NULL,
    STORED_NAME    VARCHAR(255) NOT NULL,
    FILE_PATH      VARCHAR(500) NOT NULL,
    FILE_SIZE      BIGINT       NOT NULL,
    CONTENT_TYPE   VARCHAR(100),
    FILE_HASH      VARCHAR(64),
    DOWNLOAD_COUNT INT DEFAULT 0,
    IS_IMAGE       BOOLEAN   DEFAULT FALSE,
    IMAGE_WIDTH    INT,
    IMAGE_HEIGHT   INT,
    CREATED_AT     DATETIME  DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID) ON DELETE CASCADE,
    INDEX IDX_ATTACHMENTS_ARTICLE_ID (ARTICLE_ID),
    INDEX IDX_ATTACHMENTS_IS_IMAGE (IS_IMAGE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 방문 통계 테이블
CREATE TABLE IF NOT EXISTS VISIT_STATS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATE       DATE   NOT NULL,
    USER_ID    BIGINT,
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    PAGE_URL   VARCHAR(500),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    INDEX IDX_VISIT_STATS_DATE (DATE),
    INDEX IDX_VISIT_STATS_USER_ID (USER_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 시스템 로그 테이블 (MongoDB와 연동 가능)
CREATE TABLE IF NOT EXISTS SYSTEM_LOGS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    LEVEL      VARCHAR(10)  NOT NULL,
    MESSAGE    TEXT         NOT NULL,
    LOGGER     VARCHAR(100),
    THREAD     VARCHAR(50),
    USER_ID    BIGINT,
    SESSION_ID VARCHAR(100),
    IP_ADDRESS VARCHAR(45),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    INDEX IDX_SYSTEM_LOGS_LEVEL (LEVEL),
    INDEX IDX_SYSTEM_LOGS_CREATED_AT (CREATED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 테스트 데이터 - Chapter 13: Enhanced Board with Analytics
INSERT INTO ROLES (ROLE_NAME, DESCRIPTION, LEVEL) VALUES 
('ROLE_USER', '일반 사용자', 1),
('ROLE_MANAGER', '매니저', 5),
('ROLE_ADMINISTRATOR', '관리자', 10)
ON DUPLICATE KEY UPDATE ROLE_NAME = VALUES(ROLE_NAME);

INSERT INTO USERS (EMAIL, PASSWORD, NICKNAME, EMAIL_VERIFIED, STATUS) VALUES 
('analytics@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'AnalyticsAdmin', TRUE, 'ACTIVE'),
('uploader@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'FileUploader', TRUE, 'ACTIVE'),
('viewer@primavera.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.', 'Viewer', TRUE, 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES 
(1, 3), -- Analytics Admin
(2, 2), -- File Uploader Manager
(3, 1)  -- Viewer User
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

INSERT INTO ARTICLES (TITLE, CONTENT, AUTHOR_ID, STATUS, IS_NOTICE, HAS_ATTACHMENTS, PUBLISHED_AT) VALUES 
('파일 업로드 기능 테스트', '<h2>파일 업로드 및 첨부파일 관리</h2><p>이 게시글은 파일 업로드 기능을 테스트합니다.</p>', 1, 'PUBLISHED', TRUE, TRUE, NOW()),
('통계 분석 테스트', '<p>방문 통계 및 로그 분석 기능을 테스트하는 게시글입니다.</p>', 2, 'PUBLISHED', FALSE, FALSE, NOW()),
('이미지 갤러리', '<p>이미지 첨부 기능을 테스트하는 게시글입니다.</p>', 2, 'PUBLISHED', FALSE, TRUE, NOW())
ON DUPLICATE KEY UPDATE TITLE = VALUES(TITLE);

INSERT INTO COMMENTS (ARTICLE_ID, PARENT_ID, AUTHOR_ID, CONTENT, DEPTH) VALUES 
(1, NULL, 2, '파일 업로드 기능이 잘 작동하네요!', 0),
(1, 1, 3, '네, 정말 편리합니다.', 1),
(2, NULL, 3, '통계 기능도 유용할 것 같아요.', 0)
ON DUPLICATE KEY UPDATE ARTICLE_ID = VALUES(ARTICLE_ID);

INSERT INTO ATTACHMENTS (ARTICLE_ID, ORIGINAL_NAME, STORED_NAME, FILE_PATH, FILE_SIZE, CONTENT_TYPE, IS_IMAGE, IMAGE_WIDTH, IMAGE_HEIGHT) VALUES 
(1, 'test-document.pdf', 'test-doc-20241201-001.pdf', '/uploads/files/test-doc-20241201-001.pdf', 2048000, 'application/pdf', FALSE, NULL, NULL),
(3, 'sample-image.jpg', 'sample-img-20241201-001.jpg', '/uploads/images/sample-img-20241201-001.jpg', 512000, 'image/jpeg', TRUE, 1920, 1080),
(3, 'thumbnail.png', 'thumb-20241201-001.png', '/uploads/images/thumb-20241201-001.png', 128000, 'image/png', TRUE, 300, 200)
ON DUPLICATE KEY UPDATE ARTICLE_ID = VALUES(ARTICLE_ID);

INSERT INTO VISIT_STATS (DATE, USER_ID, IP_ADDRESS, PAGE_URL) VALUES 
(CURDATE(), 1, '192.168.1.100', '/articles/1'),
(CURDATE(), 2, '192.168.1.101', '/articles/2'),
(CURDATE(), 3, '192.168.1.102', '/articles/3'),
(CURDATE() - INTERVAL 1 DAY, 1, '192.168.1.100', '/dashboard')
ON DUPLICATE KEY UPDATE DATE = VALUES(DATE);

INSERT INTO SYSTEM_LOGS (LEVEL, MESSAGE, LOGGER, USER_ID, IP_ADDRESS) VALUES 
('INFO', 'User login successful', 'com.genius.primavera.auth.AuthController', 1, '192.168.1.100'),
('INFO', 'File upload completed', 'com.genius.primavera.file.FileController', 2, '192.168.1.101'),
('WARN', 'Failed login attempt', 'com.genius.primavera.auth.AuthController', NULL, '192.168.1.999')
ON DUPLICATE KEY UPDATE LEVEL = VALUES(LEVEL);