-- Chapter 13 JPA 관계 매핑 테스트를 위한 종합 데이터베이스 스키마

-- ===========================================
-- OneToOne 관계 테이블들
-- ===========================================

-- Member-Address OneToOne 관계
CREATE TABLE IF NOT EXISTS MEMBERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ADDRESSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    POSTAL_CODE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL DEFAULT 'South Korea',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(ID) ON DELETE CASCADE,
    INDEX IDX_MEMBER_ID (MEMBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Product-Serial OneToOne 관계
CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SERIALS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    SERIAL_NUMBER VARCHAR(100) UNIQUE NOT NULL,
    MANUFACTURE_DATE DATE NOT NULL,
    WARRANTY_PERIOD_MONTHS INT DEFAULT 12,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    INDEX IDX_PRODUCT_ID (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Article-Content OneToOne 관계
CREATE TABLE IF NOT EXISTS ARTICLES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(100) NOT NULL,
    PUBLISHED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'DRAFT'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID BIGINT NOT NULL,
    BODY LONGTEXT NOT NULL,
    WORD_COUNT INT DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ID) ON DELETE CASCADE,
    INDEX IDX_ARTICLE_ID (ARTICLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Book-ISBN OneToOne 관계
CREATE TABLE IF NOT EXISTS BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(100) NOT NULL,
    PUBLISHER VARCHAR(100),
    PUBLICATION_DATE DATE,
    PAGES INT DEFAULT 0,
    PRICE DECIMAL(8,2) DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ISBNS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID BIGINT NOT NULL,
    ISBN_10 VARCHAR(10),
    ISBN_13 VARCHAR(13) UNIQUE NOT NULL,
    ASSIGNED_DATE DATE DEFAULT (CURRENT_DATE),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE,
    INDEX IDX_BOOK_ID (BOOK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================
-- OneToMany 관계 테이블들
-- ===========================================

-- Customer-Contact OneToMany 관계
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    REGISTRATION_DATE DATE DEFAULT (CURRENT_DATE),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTACTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    CONTACT_TYPE VARCHAR(50) NOT NULL, -- EMAIL, PHONE, ADDRESS
    CONTACT_VALUE VARCHAR(255) NOT NULL,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_CONTACT_TYPE (CONTACT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Professor-Student OneToMany 관계
CREATE TABLE IF NOT EXISTS PROFESSORS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    OFFICE VARCHAR(50),
    HIRE_DATE DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STUDENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PROFESSOR_ID BIGINT,
    STUDENT_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    MAJOR VARCHAR(100) NOT NULL,
    GRADE INT NOT NULL CHECK (GRADE BETWEEN 1 AND 4),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    ENROLLMENT_DATE DATE NOT NULL,
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSORS(ID) ON DELETE SET NULL,
    INDEX IDX_PROFESSOR_ID (PROFESSOR_ID),
    INDEX IDX_STUDENT_NUMBER (STUDENT_NUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================
-- ManyToOne 관계 테이블들
-- ===========================================

-- Department-Employee ManyToOne 관계
CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CODE VARCHAR(10) UNIQUE NOT NULL,
    MANAGER_NAME VARCHAR(100),
    BUDGET DECIMAL(15,2) DEFAULT 0.00,
    ESTABLISHED_DATE DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_ID BIGINT NOT NULL,
    EMPLOYEE_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(100) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(ID) ON DELETE RESTRICT,
    INDEX IDX_DEPARTMENT_ID (DEPARTMENT_ID),
    INDEX IDX_EMPLOYEE_NUMBER (EMPLOYEE_NUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Team-Player ManyToOne 관계
CREATE TABLE IF NOT EXISTS TEAMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    FOUNDED_YEAR INT NOT NULL,
    LEAGUE VARCHAR(100) NOT NULL,
    BUDGET DECIMAL(15,2) DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS PLAYERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEAM_ID BIGINT,
    JERSEY_NUMBER INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    NATIONALITY VARCHAR(100) DEFAULT 'South Korea',
    SALARY DECIMAL(12,2) DEFAULT 0.00,
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID) ON DELETE SET NULL,
    INDEX IDX_TEAM_ID (TEAM_ID),
    INDEX IDX_POSITION (POSITION),
    UNIQUE KEY UNIQUE_TEAM_JERSEY (TEAM_ID, JERSEY_NUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================
-- ManyToMany 관계 테이블들
-- ===========================================

-- Buyer-Seller ManyToMany 관계 (Contract 중간 테이블)
CREATE TABLE IF NOT EXISTS BUYERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    COMPANY VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    REGISTRATION_DATE DATE DEFAULT (CURRENT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SELLERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    COMPANY VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    REGISTRATION_DATE DATE DEFAULT (CURRENT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTRACTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BUYER_ID BIGINT NOT NULL,
    SELLER_ID BIGINT NOT NULL,
    CONTRACT_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'KRW',
    CONTRACT_DATE DATE NOT NULL,
    DELIVERY_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BUYER_ID) REFERENCES BUYERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (SELLER_ID) REFERENCES SELLERS(ID) ON DELETE CASCADE,
    INDEX IDX_BUYER_ID (BUYER_ID),
    INDEX IDX_SELLER_ID (SELLER_ID),
    INDEX IDX_CONTRACT_DATE (CONTRACT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Publisher-Subscriber ManyToMany 관계
CREATE TABLE IF NOT EXISTS PUBLISHERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    WEBSITE VARCHAR(255),
    ESTABLISHED_DATE DATE,
    COUNTRY VARCHAR(100) DEFAULT 'South Korea'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SUBSCRIBERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SUBSCRIPTION_DATE DATE NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    SUBSCRIPTION_TYPE VARCHAR(50) DEFAULT 'BASIC'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS PUBLISHER_SUBSCRIBERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PUBLISHER_ID BIGINT NOT NULL,
    SUBSCRIBER_ID BIGINT NOT NULL,
    SUBSCRIPTION_START_DATE DATE NOT NULL,
    SUBSCRIPTION_END_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (SUBSCRIBER_ID) REFERENCES SUBSCRIBERS(ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_PUBLISHER_SUBSCRIBER (PUBLISHER_ID, SUBSCRIBER_ID),
    INDEX IDX_PUBLISHER_ID (PUBLISHER_ID),
    INDEX IDX_SUBSCRIBER_ID (SUBSCRIBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Origin-Destination ManyToMany 관계
CREATE TABLE IF NOT EXISTS ORIGINS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CODE VARCHAR(10) UNIQUE NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    AIRPORT_CODE VARCHAR(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS DESTINATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CODE VARCHAR(10) UNIQUE NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    AIRPORT_CODE VARCHAR(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ORIGIN_DESTINATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORIGIN_ID BIGINT NOT NULL,
    DESTINATION_ID BIGINT NOT NULL,
    DISTANCE_KM INT NOT NULL DEFAULT 0,
    FLIGHT_TIME_MINUTES INT NOT NULL DEFAULT 0,
    IS_DIRECT_FLIGHT BOOLEAN DEFAULT TRUE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORIGIN_ID) REFERENCES ORIGINS(ID) ON DELETE CASCADE,
    FOREIGN KEY (DESTINATION_ID) REFERENCES DESTINATIONS(ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_ORIGIN_DESTINATION (ORIGIN_ID, DESTINATION_ID),
    INDEX IDX_ORIGIN_ID (ORIGIN_ID),
    INDEX IDX_DESTINATION_ID (DESTINATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Sender-Recipient ManyToMany 관계 (Letter 중간 테이블)
CREATE TABLE IF NOT EXISTS SENDERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS RECIPIENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS LETTERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SENDER_ID BIGINT NOT NULL,
    RECIPIENT_ID BIGINT NOT NULL,
    SUBJECT VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    SENT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    DELIVERY_STATUS VARCHAR(20) DEFAULT 'SENT',
    PRIORITY VARCHAR(10) DEFAULT 'NORMAL',
    FOREIGN KEY (SENDER_ID) REFERENCES SENDERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (RECIPIENT_ID) REFERENCES RECIPIENTS(ID) ON DELETE CASCADE,
    INDEX IDX_SENDER_ID (SENDER_ID),
    INDEX IDX_RECIPIENT_ID (RECIPIENT_ID),
    INDEX IDX_SENT_DATE (SENT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================
-- 상속 계층 구조 테이블들
-- ===========================================

-- Family 상속 계층 (Joined Strategy)
CREATE TABLE IF NOT EXISTS FAMILY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    SCIENTIFIC_NAME VARCHAR(100) NOT NULL,
    HABITAT VARCHAR(255),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CANIDAE (
    ID BIGINT PRIMARY KEY,
    PACK_SIZE INT DEFAULT 1,
    HUNTING_STYLE VARCHAR(100),
    FOREIGN KEY (ID) REFERENCES FAMILY(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS FELIDAE (
    ID BIGINT PRIMARY KEY,
    CLIMBING_ABILITY VARCHAR(50),
    HUNTING_STYLE VARCHAR(100),
    FOREIGN KEY (ID) REFERENCES FAMILY(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SCINCIDAE (
    ID BIGINT PRIMARY KEY,
    SCALE_TYPE VARCHAR(50),
    BURROWING_ABILITY VARCHAR(50),
    FOREIGN KEY (ID) REFERENCES FAMILY(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Item 상속 계층 (Single Table Strategy)
CREATE TABLE IF NOT EXISTS ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DTYPE VARCHAR(31) NOT NULL, -- ALBUM, BOOK, MOVIE
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    STOCK_QUANTITY INT DEFAULT 0,
    -- Album 전용 필드
    ARTIST VARCHAR(100),
    ETC VARCHAR(255),
    -- Book 전용 필드
    AUTHOR VARCHAR(100),
    ISBN VARCHAR(20),
    -- Movie 전용 필드
    DIRECTOR VARCHAR(100),
    ACTOR VARCHAR(255),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_DTYPE (DTYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Contact 상속 계층 (Table Per Class Strategy)
CREATE TABLE IF NOT EXISTS CONTACT_ADDRESSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    POSTAL_CODE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(100) DEFAULT 'South Korea',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTACT_EMAILS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    DOMAIN VARCHAR(100),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================
-- 초기 테스트 데이터 삽입
-- ===========================================

-- OneToOne 관계 테스트 데이터
INSERT INTO MEMBERS (NAME, EMAIL) VALUES 
('김철수', 'kim@primavera.com'),
('이영희', 'lee@primavera.com'),
('박민수', 'park@primavera.com');

INSERT INTO ADDRESSES (MEMBER_ID, STREET, CITY, POSTAL_CODE) VALUES 
(1, '강남대로 123', '서울특별시', '06123'),
(2, '해운대해변로 456', '부산광역시', '48094'),
(3, '중앙로 789', '대구광역시', '41911');

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE) VALUES 
('MacBook Pro', 'Apple 노트북 컴퓨터', 2500000.00),
('iPhone 15', 'Apple 스마트폰', 1200000.00),
('Galaxy S24', 'Samsung 스마트폰', 1100000.00);

INSERT INTO SERIALS (PRODUCT_ID, SERIAL_NUMBER, MANUFACTURE_DATE) VALUES 
(1, 'MBP2024001', '2024-01-15'),
(2, 'IPH2024001', '2024-02-20'),
(3, 'GAL2024001', '2024-03-10');

-- OneToMany 관계 테스트 데이터
INSERT INTO CUSTOMERS (NAME, EMAIL, PHONE, STATUS) VALUES 
('고객1', 'customer1@test.com', '010-1111-1111', 'ACTIVE'),
('고객2', 'customer2@test.com', '010-2222-2222', 'ACTIVE');

INSERT INTO CONTACTS (CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE, IS_PRIMARY) VALUES 
(1, 'EMAIL', 'customer1@test.com', TRUE),
(1, 'PHONE', '010-1111-1111', FALSE),
(1, 'ADDRESS', '서울시 강남구', FALSE),
(2, 'EMAIL', 'customer2@test.com', TRUE),
(2, 'PHONE', '010-2222-2222', FALSE);

INSERT INTO PROFESSORS (NAME, DEPARTMENT, EMAIL, OFFICE, HIRE_DATE) VALUES 
('김교수', '컴퓨터공학과', 'prof.kim@univ.ac.kr', '공학관 301', '2010-03-01'),
('이교수', '전자공학과', 'prof.lee@univ.ac.kr', '공학관 401', '2015-09-01');

INSERT INTO STUDENTS (PROFESSOR_ID, STUDENT_NUMBER, NAME, MAJOR, GRADE, EMAIL, ENROLLMENT_DATE) VALUES 
(1, '2021001', '학생1', '컴퓨터공학', 3, 'student1@univ.ac.kr', '2021-03-01'),
(1, '2021002', '학생2', '컴퓨터공학', 2, 'student2@univ.ac.kr', '2022-03-01'),
(2, '2021003', '학생3', '전자공학', 4, 'student3@univ.ac.kr', '2020-03-01');

-- ManyToOne 관계 테스트 데이터
INSERT INTO DEPARTMENTS (NAME, CODE, MANAGER_NAME, BUDGET, ESTABLISHED_DATE) VALUES 
('개발팀', 'DEV', '개발팀장', 1000000000.00, '2020-01-01'),
('마케팅팀', 'MKT', '마케팅팀장', 500000000.00, '2020-01-01'),
('영업팀', 'SALES', '영업팀장', 800000000.00, '2020-01-01');

INSERT INTO EMPLOYEES (DEPARTMENT_ID, EMPLOYEE_NUMBER, NAME, POSITION, SALARY, HIRE_DATE, EMAIL) VALUES 
(1, 'EMP001', '개발자1', 'Senior Developer', 8000000.00, '2022-01-01', 'dev1@company.com'),
(1, 'EMP002', '개발자2', 'Junior Developer', 5000000.00, '2023-01-01', 'dev2@company.com'),
(2, 'EMP003', '마케터1', 'Marketing Manager', 7000000.00, '2022-06-01', 'mkt1@company.com'),
(3, 'EMP004', '영업1', 'Sales Representative', 6000000.00, '2022-03-01', 'sales1@company.com');

INSERT INTO TEAMS (NAME, CITY, FOUNDED_YEAR, LEAGUE, BUDGET) VALUES 
('FC Seoul', '서울', 1983, 'K League 1', 15000000000.00),
('Busan IPark', '부산', 1979, 'K League 1', 8000000000.00);

INSERT INTO PLAYERS (TEAM_ID, JERSEY_NUMBER, NAME, POSITION, AGE, NATIONALITY, SALARY, CONTRACT_START_DATE, CONTRACT_END_DATE) VALUES 
(1, 10, '손흥민', 'Forward', 31, 'South Korea', 5000000000.00, '2024-01-01', '2026-12-31'),
(1, 7, '이강인', 'Midfielder', 23, 'South Korea', 2000000000.00, '2024-01-01', '2025-12-31'),
(2, 9, '황희찬', 'Forward', 28, 'South Korea', 3000000000.00, '2024-01-01', '2025-12-31');

-- ManyToMany 관계 테스트 데이터
INSERT INTO BUYERS (NAME, COMPANY, EMAIL, PHONE) VALUES 
('구매자1', '구매회사A', 'buyer1@companya.com', '02-1111-1111'),
('구매자2', '구매회사B', 'buyer2@companyb.com', '02-2222-2222');

INSERT INTO SELLERS (NAME, COMPANY, EMAIL, PHONE) VALUES 
('판매자1', '판매회사X', 'seller1@companyx.com', '02-3333-3333'),
('판매자2', '판매회사Y', 'seller2@companyy.com', '02-4444-4444');

INSERT INTO CONTRACTS (BUYER_ID, SELLER_ID, CONTRACT_NUMBER, AMOUNT, CONTRACT_DATE, DELIVERY_DATE, STATUS) VALUES 
(1, 1, 'CON-2024-001', 10000000.00, '2024-01-15', '2024-02-15', 'COMPLETED'),
(1, 2, 'CON-2024-002', 15000000.00, '2024-02-01', '2024-03-01', 'IN_PROGRESS'),
(2, 1, 'CON-2024-003', 8000000.00, '2024-01-20', '2024-02-20', 'COMPLETED');

-- 상속 계층 테스트 데이터
INSERT INTO FAMILY (NAME, SCIENTIFIC_NAME, HABITAT) VALUES 
('개과', 'Canidae', '전 세계 다양한 서식지'),
('고양이과', 'Felidae', '숲, 초원, 사막 등'),
('도마뱀과', 'Scincidae', '땅속, 낙엽 아래');

INSERT INTO CANIDAE (ID, PACK_SIZE, HUNTING_STYLE) VALUES 
(1, 8, '무리 사냥');

INSERT INTO FELIDAE (ID, CLIMBING_ABILITY, HUNTING_STYLE) VALUES 
(2, '뛰어남', '단독 사냥');

INSERT INTO SCINCIDAE (ID, SCALE_TYPE, BURROWING_ABILITY) VALUES 
(3, '매끄러운 비늘', '뛰어남');

INSERT INTO ITEMS (DTYPE, NAME, PRICE, STOCK_QUANTITY, ARTIST, AUTHOR, DIRECTOR) VALUES 
('ALBUM', 'Love Yourself', 25000.00, 100, 'BTS', NULL, NULL),
('BOOK', 'Spring Boot 완전정복', 35000.00, 50, NULL, '김개발', NULL),
('MOVIE', 'Parasite', 15000.00, 200, NULL, NULL, '봉준호');

INSERT INTO CONTACT_ADDRESSES (NAME, STREET, CITY, POSTAL_CODE) VALUES 
('주소연락처1', '테헤란로 123', '서울', '06142'),
('주소연락처2', '해운대해변로 456', '부산', '48094');

INSERT INTO CONTACT_EMAILS (NAME, EMAIL, IS_VERIFIED, DOMAIN) VALUES 
('이메일연락처1', 'contact1@test.com', TRUE, 'test.com'),
('이메일연락처2', 'contact2@example.com', FALSE, 'example.com');