-- MySQL 8.4.0용 시퀀스 테이블 초기화
CREATE TABLE IF NOT EXISTS TABLE_SEQ (
    SEQ_NAME VARCHAR(50) NOT NULL PRIMARY KEY,
    SEQ_COUNT BIGINT NOT NULL DEFAULT 0
) ENGINE=InnoDB;

-- Family 시퀀스 초기화 (ON DUPLICATE KEY UPDATE로 중복 방지)
INSERT INTO TABLE_SEQ (SEQ_NAME, SEQ_COUNT) VALUES ('FAMILY', 0) ON DUPLICATE KEY UPDATE SEQ_COUNT = SEQ_COUNT;
INSERT INTO TABLE_SEQ (SEQ_NAME, SEQ_COUNT) VALUES ('ITEM', 0) ON DUPLICATE KEY UPDATE SEQ_COUNT = SEQ_COUNT;
INSERT INTO TABLE_SEQ (SEQ_NAME, SEQ_COUNT) VALUES ('CONTACT', 0) ON DUPLICATE KEY UPDATE SEQ_COUNT = SEQ_COUNT;