// chap06: Web + Validation + Lucy Filter + Thymeleaf + MyBatis
dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-security"
    databaseDependencies.each { dep -> implementation dep }
    mybatisDependencies.each { dep -> implementation dep }
    thymeleafDependencies.each { dep -> implementation dep }
    validationDependencies.each { dep -> implementation dep }
    
    implementation project(":appendix:spring-boot-starter-lucy-filter")
    
    testContainersDependencies.each { dep -> testImplementation dep }
}