
configurations {
    implementation.exclude group: 'org.springframework.boot', module: 'spring-boot-starter-web'
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    aopDependencies.each { dep -> implementation dep }
    databaseDependencies.each { dep -> implementation dep }
    developmentDependencies.each { dep -> implementation dep }
    loggingDependencies.each { dep -> implementation dep }
    testContainersDependencies.each { dep -> testImplementation dep }
    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    implementation "org.springframework.data:spring-data-envers"
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springframework.cloud:spring-cloud-starter-vault-config:${springCloudVaultVersion}"
}