plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
}

group = 'com.genius.primavera'
version = '1.0.0'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation "org.testcontainers:testcontainers:${testContainersVersion}"
    implementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    implementation "org.testcontainers:mariadb:${testContainersVersion}"
    implementation "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    // annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
    compileOnly "org.jetbrains:annotations:${jetbrainsAnnotationsVersion}"
}

bootJar {
    enabled = false
}

jar {
    enabled = true
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
}