plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootVersion}" apply false
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.genius.primavera'
version = '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        mavenBom "org.testcontainers:testcontainers-bom:${testContainersVersion}"
    }
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-test'
    api 'org.testcontainers:testcontainers'
    api 'org.testcontainers:junit-jupiter'
    api 'org.testcontainers:mariadb'
    api 'org.testcontainers:postgresql'
    api 'org.testcontainers:mysql'
    api 'org.testcontainers:mongodb'
    api 'org.testcontainers:kafka'
    api 'org.testcontainers:elasticsearch'

    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-configuration-processor'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-testcontainers'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-redis'
    testImplementation 'org.mariadb.jdbc:mariadb-java-client'
    testImplementation 'org.postgresql:postgresql'
    testImplementation 'com.mysql:mysql-connector-j'
}

tasks.named('test') {
    useJUnitPlatform()
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}