plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.testcontainers:mariadb:${testContainersVersion}"
    implementation "org.testcontainers:mysql:${testContainersVersion}"
    implementation "org.testcontainers:postgresql:${testContainersVersion}"
    implementation "org.testcontainers:kafka:${testContainersVersion}"
    implementation "org.testcontainers:testcontainers:${testContainersVersion}"
    implementation "org.testcontainers:elasticsearch:${testContainersVersion}"
    implementation "com.redis.testcontainers:testcontainers-redis:1.6.4"
    implementation "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    implementation "com.mysql:mysql-connector-j:8.3.0"
    implementation "org.postgresql:postgresql:42.7.2"
    implementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    implementation "org.springframework:spring-test"
    implementation "org.springframework.boot:spring-boot-test"
    implementation "org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}"

    // Lombok
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.boot:spring-boot-starter-jdbc"
    testImplementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    testImplementation "org.testcontainers:mariadb:${testContainersVersion}"
}

jar {
    enabled = true
    archiveClassifier = ''
}

bootJar {
    enabled = false
}