-- ==============================================
-- Test Database Schema
-- ==============================================

-- 카테고리 테이블
CREATE TABLE IF NOT EXISTS CATEGORIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    LEVEL INT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 판매자 테이블
CREATE TABLE IF NOT EXISTS SELLERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    RATING DECIMAL(3,2) DEFAULT 0.00,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 상품 테이블
CREATE TABLE IF NOT EXISTS PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    PRICE INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    SELLER_ID BIGINT NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (SELLER_ID) REFERENCES SELLERS(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테스트 데이터
INSERT INTO CATEGORIES (ID, NAME, LEVEL) VALUES
(1, '전자제품', 1),
(2, '컴퓨터', 2),
(3, '스마트폰', 2);

INSERT INTO SELLERS (ID, NAME, EMAIL, RATING) VALUES
(1, '테스트스토어', 'test@primavera.com', 4.5),
(2, '샘플샵', 'sample@primavera.com', 4.2);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STATUS, SELLER_ID, CATEGORY_ID) VALUES
(1, 'Test Laptop', 'Test laptop description', 1000000, 'ACTIVE', 1, 2),
(2, 'Test Phone', 'Test phone description', 800000, 'ACTIVE', 2, 3),
(3, 'Test Tablet', 'Test tablet description', 600000, 'ACTIVE', 1, 1);