spring:
  config:
    activate:
      on-profile: local
    import:
      - "optional:vault:"
  aop:
    proxy-target-class: true
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: ${VAULT_SCHEME:http}
      authentication: TOKEN
      token: ${VAULT_TOKEN:primavera-vault-token}
      connection-timeout: 5000
      read-timeout: 15000
      fail-fast: false
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: AdvancedJpaApplication
        application-name: AdvancedJpaApplication
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: "BalancedHikariPool"
      leak-detection-threshold: 60000
      connection-test-query: "SELECT 1"
      validation-timeout: 5000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
    reactive:
      chunked-mode-view-names: chart,stream,debug
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/resources/templates
      additional-exclude: static/**,public/**