-- ==============================================
-- Chapter 15 - JPA Advanced Relationship Mapping Test Data
-- Uses primavera_test database (TestContainers) 
-- ==============================================

-- 공통 테스트 사용자 테이블
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 권한 테이블
CREATE TABLE IF NOT EXISTS ROLES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    TYPE        INT                NOT NULL,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자-권한 연결 테이블
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_USER_ROLE (USER_ID, ROLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ===========================================
-- Chapter 15 특화 테이블 - JPA 접두사 사용
-- JPA 관계 매핑 테스트를 위한 종합 데이터베이스 스키마
-- ===========================================

-- OneToOne 관계 테이블들
CREATE TABLE IF NOT EXISTS JPA_MEMBERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_ADDRESSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID BIGINT NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    POSTAL_CODE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL DEFAULT 'South Korea',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES JPA_MEMBERS(ID) ON DELETE CASCADE,
    INDEX IDX_MEMBER_ID (MEMBER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_SERIALS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    SERIAL_NUMBER VARCHAR(100) UNIQUE NOT NULL,
    MANUFACTURE_DATE DATE NOT NULL,
    WARRANTY_PERIOD_MONTHS INT DEFAULT 12,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES JPA_PRODUCTS(ID) ON DELETE CASCADE,
    INDEX IDX_PRODUCT_ID (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- OneToMany 관계 테이블들
CREATE TABLE IF NOT EXISTS JPA_CUSTOMERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    REGISTRATION_DATE DATE DEFAULT (CURRENT_DATE),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_CONTACTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    CONTACT_TYPE VARCHAR(50) NOT NULL COMMENT 'EMAIL, PHONE, ADDRESS',
    CONTACT_VALUE VARCHAR(255) NOT NULL,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES JPA_CUSTOMERS(ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_CONTACT_TYPE (CONTACT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_PROFESSORS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    OFFICE VARCHAR(50),
    HIRE_DATE DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_STUDENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PROFESSOR_ID BIGINT,
    STUDENT_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    MAJOR VARCHAR(100) NOT NULL,
    GRADE INT NOT NULL CHECK (GRADE BETWEEN 1 AND 4),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    ENROLLMENT_DATE DATE NOT NULL,
    FOREIGN KEY (PROFESSOR_ID) REFERENCES JPA_PROFESSORS(ID) ON DELETE SET NULL,
    INDEX IDX_PROFESSOR_ID (PROFESSOR_ID),
    INDEX IDX_STUDENT_NUMBER (STUDENT_NUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ManyToOne 관계 테이블들
CREATE TABLE IF NOT EXISTS JPA_DEPARTMENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CODE VARCHAR(10) UNIQUE NOT NULL,
    MANAGER_NAME VARCHAR(100),
    BUDGET DECIMAL(15,2) DEFAULT 0.00,
    ESTABLISHED_DATE DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_EMPLOYEES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_ID BIGINT NOT NULL,
    EMPLOYEE_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(100) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES JPA_DEPARTMENTS(ID) ON DELETE RESTRICT,
    INDEX IDX_DEPARTMENT_ID (DEPARTMENT_ID),
    INDEX IDX_EMPLOYEE_NUMBER (EMPLOYEE_NUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_TEAMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    FOUNDED_YEAR INT NOT NULL,
    LEAGUE VARCHAR(100) NOT NULL,
    BUDGET DECIMAL(15,2) DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_PLAYERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEAM_ID BIGINT,
    JERSEY_NUMBER INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    NATIONALITY VARCHAR(100) DEFAULT 'South Korea',
    SALARY DECIMAL(12,2) DEFAULT 0.00,
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    FOREIGN KEY (TEAM_ID) REFERENCES JPA_TEAMS(ID) ON DELETE SET NULL,
    INDEX IDX_TEAM_ID (TEAM_ID),
    INDEX IDX_POSITION (POSITION),
    UNIQUE KEY UNIQUE_TEAM_JERSEY (TEAM_ID, JERSEY_NUMBER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ManyToMany 관계 테이블들
CREATE TABLE IF NOT EXISTS JPA_BUYERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    COMPANY VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    REGISTRATION_DATE DATE DEFAULT (CURRENT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_SELLERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    COMPANY VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    REGISTRATION_DATE DATE DEFAULT (CURRENT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_CONTRACTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BUYER_ID BIGINT NOT NULL,
    SELLER_ID BIGINT NOT NULL,
    CONTRACT_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'KRW',
    CONTRACT_DATE DATE NOT NULL,
    DELIVERY_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BUYER_ID) REFERENCES JPA_BUYERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (SELLER_ID) REFERENCES JPA_SELLERS(ID) ON DELETE CASCADE,
    INDEX IDX_BUYER_ID (BUYER_ID),
    INDEX IDX_SELLER_ID (SELLER_ID),
    INDEX IDX_CONTRACT_DATE (CONTRACT_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 상속 계층 구조 테이블들
CREATE TABLE IF NOT EXISTS JPA_FAMILY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    SCIENTIFIC_NAME VARCHAR(100) NOT NULL,
    HABITAT VARCHAR(255),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_CANIDAE (
    ID BIGINT PRIMARY KEY,
    PACK_SIZE INT DEFAULT 1,
    HUNTING_STYLE VARCHAR(100),
    FOREIGN KEY (ID) REFERENCES JPA_FAMILY(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_FELIDAE (
    ID BIGINT PRIMARY KEY,
    CLIMBING_ABILITY VARCHAR(50),
    HUNTING_STYLE VARCHAR(100),
    FOREIGN KEY (ID) REFERENCES JPA_FAMILY(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_SCINCIDAE (
    ID BIGINT PRIMARY KEY,
    SCALE_TYPE VARCHAR(50),
    BURROWING_ABILITY VARCHAR(50),
    FOREIGN KEY (ID) REFERENCES JPA_FAMILY(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Item 상속 계층 (Single Table Strategy)
CREATE TABLE IF NOT EXISTS JPA_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DTYPE VARCHAR(31) NOT NULL COMMENT 'ALBUM, BOOK, MOVIE',
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    STOCK_QUANTITY INT DEFAULT 0,
    -- Album 전용 필드
    ARTIST VARCHAR(100),
    ETC VARCHAR(255),
    -- Book 전용 필드
    AUTHOR VARCHAR(100),
    ISBN VARCHAR(20),
    -- Movie 전용 필드
    DIRECTOR VARCHAR(100),
    ACTOR VARCHAR(255),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_DTYPE (DTYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- JPA 시퀀스 관리 테이블
CREATE TABLE IF NOT EXISTS JPA_TABLE_SEQ (
    SEQ_NAME VARCHAR(50) NOT NULL PRIMARY KEY,
    SEQ_COUNT BIGINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 기본 테스트 데이터
INSERT INTO ROLES (ID, NAME, DESCRIPTION, TYPE)
VALUES (1, 'ROLE_ADMIN', '테스트 관리자', 1),
       (2, 'ROLE_USER', '테스트 사용자', 3)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS)
VALUES (1, 'test-admin@primavera.com', '{noop}test', 'TestAdmin', 'ACTIVE'),
       (2, 'test-user@primavera.com', '{noop}test', 'TestUser', 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (1, 1), (1, 2),
       (2, 2)
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

-- JPA 시퀀스 초기화
INSERT INTO JPA_TABLE_SEQ (SEQ_NAME, SEQ_COUNT) VALUES 
('FAMILY', 0),
('ITEM', 0), 
('CONTACT', 0)
ON DUPLICATE KEY UPDATE SEQ_COUNT = SEQ_COUNT;

-- Chapter 15 특화 테스트 데이터 - OneToOne 관계
INSERT INTO JPA_MEMBERS (ID, NAME, EMAIL) VALUES 
(1, '김철수', 'kim@primavera.com'),
(2, '이영희', 'lee@primavera.com')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_ADDRESSES (MEMBER_ID, STREET, CITY, POSTAL_CODE) VALUES 
(1, '강남대로 123', '서울특별시', '06123'),
(2, '해운대해변로 456', '부산광역시', '48094')
ON DUPLICATE KEY UPDATE MEMBER_ID = VALUES(MEMBER_ID);

INSERT INTO JPA_PRODUCTS (ID, NAME, DESCRIPTION, PRICE) VALUES 
(1, 'MacBook Pro', 'Apple 노트북 컴퓨터', 2500000.00),
(2, 'iPhone 15', 'Apple 스마트폰', 1200000.00)
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_SERIALS (PRODUCT_ID, SERIAL_NUMBER, MANUFACTURE_DATE) VALUES 
(1, 'MBP2024001', '2024-01-15'),
(2, 'IPH2024001', '2024-02-20')
ON DUPLICATE KEY UPDATE PRODUCT_ID = VALUES(PRODUCT_ID);

-- OneToMany 관계 테스트 데이터
INSERT INTO JPA_CUSTOMERS (ID, NAME, EMAIL, PHONE, STATUS) VALUES 
(1, '고객1', 'customer1@test.com', '010-1111-1111', 'ACTIVE'),
(2, '고객2', 'customer2@test.com', '010-2222-2222', 'ACTIVE')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_CONTACTS (CUSTOMER_ID, CONTACT_TYPE, CONTACT_VALUE, IS_PRIMARY) VALUES 
(1, 'EMAIL', 'customer1@test.com', TRUE),
(1, 'PHONE', '010-1111-1111', FALSE),
(2, 'EMAIL', 'customer2@test.com', TRUE)
ON DUPLICATE KEY UPDATE CUSTOMER_ID = VALUES(CUSTOMER_ID);

INSERT INTO JPA_PROFESSORS (ID, NAME, DEPARTMENT, EMAIL, OFFICE, HIRE_DATE) VALUES 
(1, '김교수', '컴퓨터공학과', 'prof.kim@univ.ac.kr', '공학관 301', '2010-03-01')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_STUDENTS (PROFESSOR_ID, STUDENT_NUMBER, NAME, MAJOR, GRADE, EMAIL, ENROLLMENT_DATE) VALUES 
(1, '2021001', '학생1', '컴퓨터공학', 3, 'student1@univ.ac.kr', '2021-03-01'),
(1, '2021002', '학생2', '컴퓨터공학', 2, 'student2@univ.ac.kr', '2022-03-01')
ON DUPLICATE KEY UPDATE PROFESSOR_ID = VALUES(PROFESSOR_ID);

-- ManyToOne 관계 테스트 데이터
INSERT INTO JPA_DEPARTMENTS (ID, NAME, CODE, MANAGER_NAME, BUDGET, ESTABLISHED_DATE) VALUES 
(1, '개발팀', 'DEV', '개발팀장', 1000000000.00, '2020-01-01'),
(2, '마케팅팀', 'MKT', '마케팅팀장', 500000000.00, '2020-01-01')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_EMPLOYEES (DEPARTMENT_ID, EMPLOYEE_NUMBER, NAME, POSITION, SALARY, HIRE_DATE, EMAIL) VALUES 
(1, 'EMP001', '개발자1', 'Senior Developer', 8000000.00, '2022-01-01', 'dev1@company.com'),
(1, 'EMP002', '개발자2', 'Junior Developer', 5000000.00, '2023-01-01', 'dev2@company.com'),
(2, 'EMP003', '마케터1', 'Marketing Manager', 7000000.00, '2022-06-01', 'mkt1@company.com')
ON DUPLICATE KEY UPDATE DEPARTMENT_ID = VALUES(DEPARTMENT_ID);

INSERT INTO JPA_TEAMS (ID, NAME, CITY, FOUNDED_YEAR, LEAGUE, BUDGET) VALUES 
(1, 'FC Seoul', '서울', 1983, 'K League 1', 15000000000.00)
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_PLAYERS (TEAM_ID, JERSEY_NUMBER, NAME, POSITION, AGE, NATIONALITY, SALARY, CONTRACT_START_DATE, CONTRACT_END_DATE) VALUES 
(1, 10, '손흥민', 'Forward', 31, 'South Korea', 5000000000.00, '2024-01-01', '2026-12-31'),
(1, 7, '이강인', 'Midfielder', 23, 'South Korea', 2000000000.00, '2024-01-01', '2025-12-31')
ON DUPLICATE KEY UPDATE TEAM_ID = VALUES(TEAM_ID);

-- ManyToMany 관계 테스트 데이터
INSERT INTO JPA_BUYERS (ID, NAME, COMPANY, EMAIL, PHONE) VALUES 
(1, '구매자1', '구매회사A', 'buyer1@companya.com', '02-1111-1111')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_SELLERS (ID, NAME, COMPANY, EMAIL, PHONE) VALUES 
(1, '판매자1', '판매회사X', 'seller1@companyx.com', '02-3333-3333')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_CONTRACTS (BUYER_ID, SELLER_ID, CONTRACT_NUMBER, AMOUNT, CONTRACT_DATE, DELIVERY_DATE, STATUS) VALUES 
(1, 1, 'CON-2024-001', 10000000.00, '2024-01-15', '2024-02-15', 'COMPLETED')
ON DUPLICATE KEY UPDATE BUYER_ID = VALUES(BUYER_ID);

-- 상속 계층 테스트 데이터
INSERT INTO JPA_FAMILY (ID, NAME, SCIENTIFIC_NAME, HABITAT) VALUES 
(1, '개과', 'Canidae', '전 세계 다양한 서식지'),
(2, '고양이과', 'Felidae', '숲, 초원, 사막 등')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_CANIDAE (ID, PACK_SIZE, HUNTING_STYLE) VALUES 
(1, 8, '무리 사냥')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_FELIDAE (ID, CLIMBING_ABILITY, HUNTING_STYLE) VALUES 
(2, '뛰어남', '단독 사냥')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO JPA_ITEMS (ID, DTYPE, NAME, PRICE, STOCK_QUANTITY, ARTIST, AUTHOR, DIRECTOR) VALUES 
(1, 'ALBUM', 'Love Yourself', 25000.00, 100, 'BTS', NULL, NULL),
(2, 'BOOK', 'Spring Boot 완전정복', 35000.00, 50, NULL, '김개발', NULL),
(3, 'MOVIE', 'Parasite', 15000.00, 200, NULL, NULL, '봉준호')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);