
// chap10: Web + OAuth2 Client + Spring Security + MyBatis
dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-security"
    implementation "org.springframework.boot:spring-boot-starter-oauth2-client"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-cache"
    implementation "org.springframework.boot:spring-boot-starter-data-redis"
    implementation "com.github.ben-manes.caffeine:caffeine"
    databaseDependencies.each { dep -> implementation dep }
    mybatisDependencies.each { dep -> implementation dep }
    
    testContainersDependencies.each { dep -> testImplementation dep }
    testImplementation "org.springframework.security:spring-security-test"
}