
plugins {
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {
    // Implementation dependencies (alphabetical)
    implementation "org.springframework.cloud:spring-cloud-config-server"
    
    // Test implementation dependencies (alphabetical)
    testImplementation "org.springframework.boot:spring-boot-starter-test"
}