spring:
  config:
    activate:
      on-profile: default
  application:
    name: Privamera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt

server:
  tomcat:
    use-apr: never

logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug

mariadb:
  url: jdbc:mariadb://localhost:3306/primavera
  username: primavera
  password: primavera
  allows: local, dev, prod