spring:
  application:
    name: DataAccessApplication
  banner:
    charset: UTF-8
    location: banner.txt
  jackson:
    time-zone: UTC

server:
  tomcat:
    use-apr: never

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault: DEBUG
    com.zaxxer.hikari: DEBUG