spring:
  config:
    activate:
      on-profile: local
    import:
      - "optional:vault:"
      - "optional:configserver:"
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      connection-timeout: 5000
      read-timeout: 15000
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: DataAccessApplication
        application-name: DataAccessApplication

logging:
  level:
    org.springframework.cloud.vault: DEBUG
    org.springframework.vault: DEBUG
    com.zaxxer.hikari: DEBUG