spring:
  application:
    name: DataAccessApplication
  jackson:
    time-zone: UTC
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:1109/primavera?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: primavera
    password: primavera

server:
  tomcat:
    use-apr: never

logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug