spring:
  config:
    activate:
      on-profile: local
    import:
      - "optional:vault:"
      - "optional:configserver:"
  cloud:
    config:
      enabled: false
    vault:
      enabled: true
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: primavera-vault-token
      connection-timeout: 5000
      read-timeout: 15000
      fail-fast: false
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: MyBatisLoggingApplication
        application-name: MyBatisLoggingApplication