spring:
  config:
    activate:
      on-profile: local
    import: "optional:vault:"
  aop:
    proxy-target-class: true
  hikari:
    auto-commit: false
    data-source-properties:
      cachePrepStmts: false
      useServerPrepStmts: false
      useLocalSessionState: false
      cacheResultSetMetadata: false
      preparedStatementCacheQueries: 0
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      connection-timeout: 5000
      read-timeout: 15000
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: DataAccessApplication
        application-name: DataAccessApplication

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
    cache-enabled: false
    local-cache-scope: statement
  type-aliases-package: com.genius.primavera.domain
  type-handlers-package: com.genius.primavera.domain