dependencies {
    aopDependencies.each { dep -> implementation dep }
    databaseDependencies.each { dep -> implementation dep }
    mybatisDependencies.each { dep -> implementation dep }
    testContainersDependencies.each { dep -> testImplementation dep }
    
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springframework.cloud:spring-cloud-starter-vault-config:${springCloudVaultVersion}"
    implementation "org.springframework.cloud:spring-cloud-vault-config-databases:${springCloudVaultVersion}"
    
    compileOnly "com.zaxxer:HikariCP:${hikariCPVersion}"
    compileOnly "org.hibernate:hibernate-validator:${hibernateValidatorVersion}"
    
    testImplementation "org.springframework.security:spring-security-crypto:${springSecurityVersion}"
    testImplementation "org.springframework.security:spring-security-test"
    testImplementation "org.mybatis.spring.boot:mybatis-spring-boot-starter-test:${mybatisSpringBootStarterVersion}"
    testImplementation "org.mockito:mockito-core:4.+"
    testImplementation project(':appendix:spring-boot-starter-test-containers')
}