// chap05: Web + MyBatis + Vault Config
dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    databaseDependencies.each { dep -> implementation dep }
    mybatisDependencies.each { dep -> implementation dep }
    
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springframework.cloud:spring-cloud-starter-vault-config:${springCloudVaultVersion}"
    implementation "org.springframework.cloud:spring-cloud-vault-config-databases:${springCloudVaultVersion}"
    
    testContainersDependencies.each { dep -> testImplementation dep }
    testImplementation project(':appendix:spring-boot-starter-test-containers')
}