// chap05: Web + MyBatis + Vault Config
dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-jdbc"
    implementation "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    implementation "org.mybatis.spring.boot:mybatis-spring-boot-starter:${mybatisSpringBootStarterVersion}"
    implementation "org.mybatis.dynamic-sql:mybatis-dynamic-sql:${mybatisDynamicSqlVersion}"
    
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springframework.cloud:spring-cloud-starter-vault-config:${springCloudVaultVersion}"
    implementation "org.springframework.cloud:spring-cloud-vault-config-databases:${springCloudVaultVersion}"
    
    testImplementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    testImplementation "org.testcontainers:mariadb:${testContainersVersion}"
    testImplementation project(':appendix:spring-boot-starter-test-containers')
}