spring:
  application:
    name: JpaAdvancedMappingApplication
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
  profiles:
    active: local
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
      test:
        - console-appender
  jackson:
    time-zone: UTC

lucy-filter:
  enabled: true
  name: lucyXssFilter
  order: 1
  addUrlPatterns: /*

logging:
  config: classpath:logback-spring.xml

primavera:
  logs:
    path: ./logs
