-- ==============================================
-- Chapter 14 - JPA Advanced Features Test Data
-- Uses primavera_test database (TestContainers)
-- Focus: JPA entities, relationships, advanced queries, JPA repositories
-- ==============================================

-- 사용자 테이블 (JPA Entity 매핑용)
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME  VARCHAR(50),
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VERSION    BIGINT      DEFAULT 0,  -- Optimistic Locking
    
    INDEX IDX_USERS_EMAIL (EMAIL),
    INDEX IDX_USERS_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 카테고리 테이블 (JPA 계층 구조)
CREATE TABLE IF NOT EXISTS CATEGORIES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PARENT_ID   BIGINT,
    LEVEL       INT     DEFAULT 0,
    SORT_ORDER  INT     DEFAULT 0,
    ACTIVE      BOOLEAN DEFAULT TRUE,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (PARENT_ID) REFERENCES CATEGORIES (ID),
    INDEX IDX_CATEGORIES_PARENT_ID (PARENT_ID),
    INDEX IDX_CATEGORIES_LEVEL (LEVEL)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 상품 테이블 (JPA Entity 관계 매핑)
CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(200) NOT NULL,
    DESCRIPTION LONGTEXT,
    PRICE       DECIMAL(10, 2) NOT NULL,
    STOCK       INT            NOT NULL DEFAULT 0,
    CATEGORY_ID BIGINT,
    CREATED_BY  BIGINT         NOT NULL,
    STATUS      VARCHAR(20)    DEFAULT 'ACTIVE',
    CREATED_AT  DATETIME       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VERSION     BIGINT         DEFAULT 0,
    
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID),
    FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
    INDEX IDX_PRODUCTS_CATEGORY_ID (CATEGORY_ID),
    INDEX IDX_PRODUCTS_CREATED_BY (CREATED_BY),
    INDEX IDX_PRODUCTS_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 주문 테이블 (JPA 복합 관계)
CREATE TABLE IF NOT EXISTS ORDERS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    USER_ID      BIGINT             NOT NULL,
    TOTAL_AMOUNT DECIMAL(12, 2)     NOT NULL,
    STATUS       VARCHAR(20)        DEFAULT 'PENDING',
    ORDER_DATE   DATETIME           DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT   DATETIME           DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME           DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    INDEX IDX_ORDERS_USER_ID (USER_ID),
    INDEX IDX_ORDERS_STATUS (STATUS),
    INDEX IDX_ORDERS_ORDER_DATE (ORDER_DATE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 주문 항목 테이블 (JPA ManyToMany 관계)
CREATE TABLE IF NOT EXISTS ORDER_ITEMS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID   BIGINT         NOT NULL,
    PRODUCT_ID BIGINT         NOT NULL,
    QUANTITY   INT            NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    TOTAL_PRICE DECIMAL(12, 2) NOT NULL,
    
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID),
    UNIQUE KEY UK_ORDER_PRODUCT (ORDER_ID, PRODUCT_ID),
    INDEX IDX_ORDER_ITEMS_ORDER_ID (ORDER_ID),
    INDEX IDX_ORDER_ITEMS_PRODUCT_ID (PRODUCT_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 리뷰 테이블 (JPA 복합 키 예제)
CREATE TABLE IF NOT EXISTS REVIEWS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT  NOT NULL,
    USER_ID    BIGINT  NOT NULL,
    RATING     INT     NOT NULL CHECK (RATING >= 1 AND RATING <= 5),
    TITLE      VARCHAR(200),
    CONTENT    TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    UNIQUE KEY UK_PRODUCT_USER_REVIEW (PRODUCT_ID, USER_ID),
    INDEX IDX_REVIEWS_PRODUCT_ID (PRODUCT_ID),
    INDEX IDX_REVIEWS_USER_ID (USER_ID),
    INDEX IDX_REVIEWS_RATING (RATING)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 테스트 데이터 - Chapter 14: JPA Advanced Features
INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, FIRST_NAME, LAST_NAME, STATUS) VALUES 
(1, 'genius@primavera.com', '{noop}test', 'Genius', 'Genius', 'User', 'ACTIVE'),
(2, 'admin@primavera.com', '{noop}test', 'Admin', 'Admin', 'User', 'ACTIVE'),
(3, 'user@primavera.com', '{noop}test', 'User', 'Regular', 'User', 'ACTIVE'),
(4, 'son@primavera.com', '{noop}test', 'Son', 'Heung-Min', 'Son', 'ACTIVE'),
(5, 'messi@primavera.com', '{noop}test', 'Messi', 'Lionel', 'Messi', 'ACTIVE'),
(6, 'ronaldo@primavera.com', '{noop}test', 'Ronaldo', 'Cristiano', 'Ronaldo', 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO CATEGORIES (NAME, DESCRIPTION, PARENT_ID, LEVEL, SORT_ORDER) VALUES 
('Electronics', '전자제품 카테고리', NULL, 0, 1),
('Computers', '컴퓨터 및 주변기기', 1, 1, 1),
('Laptops', '노트북', 2, 2, 1),
('Desktops', '데스크톱', 2, 2, 2),
('Books', '도서 카테고리', NULL, 0, 2),
('Programming', '프로그래밍 도서', 5, 1, 1)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, STOCK, CATEGORY_ID, CREATED_BY, STATUS) VALUES 
('MacBook Pro 16', 'Apple MacBook Pro 16-inch with M2 chip', 2499.99, 10, 3, 2, 'ACTIVE'),
('ThinkPad X1 Carbon', 'Lenovo ThinkPad X1 Carbon Gen 11', 1899.99, 15, 3, 2, 'ACTIVE'),
('iMac 24', 'Apple iMac 24-inch with M2 chip', 1499.99, 8, 4, 2, 'ACTIVE'),
('Spring Boot in Action', 'Comprehensive guide to Spring Boot', 49.99, 50, 6, 1, 'ACTIVE'),
('Effective Java', 'Best practices for Java programming', 54.99, 30, 6, 1, 'ACTIVE')
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO ORDERS (ORDER_NUMBER, USER_ID, TOTAL_AMOUNT, STATUS, ORDER_DATE) VALUES 
('ORD-2024-001', 3, 2499.99, 'COMPLETED', '2024-01-15 10:30:00'),
('ORD-2024-002', 3, 104.98, 'PROCESSING', '2024-01-20 14:45:00'),
('ORD-2024-003', 3, 1899.99, 'PENDING', '2024-01-25 09:15:00')
ON DUPLICATE KEY UPDATE ORDER_NUMBER = VALUES(ORDER_NUMBER);

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES 
(1, 1, 1, 2499.99, 2499.99),
(2, 4, 1, 49.99, 49.99),
(2, 5, 1, 54.99, 54.99),
(3, 2, 1, 1899.99, 1899.99)
ON DUPLICATE KEY UPDATE ORDER_ID = VALUES(ORDER_ID);

INSERT INTO REVIEWS (PRODUCT_ID, USER_ID, RATING, TITLE, CONTENT) VALUES 
(1, 3, 5, 'Excellent MacBook Pro', 'The performance and build quality are outstanding. Highly recommended for developers.'),
(4, 3, 4, 'Great Spring Boot Guide', 'Very comprehensive and well-written. Perfect for learning Spring Boot from scratch.'),
(5, 3, 5, 'Must-read for Java developers', 'Joshua Bloch''s insights are invaluable. Every Java developer should read this book.')
ON DUPLICATE KEY UPDATE PRODUCT_ID = VALUES(PRODUCT_ID);