spring:
  application:
    name: AccountApplication
  jackson:
    time-zone: UTC
  data:
    redis:
      host: localhost
      port: 6379
      password: primavera

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

primavera:
  config:
    name: account
    enabled: true
    logs:
      path: ./logs/account