spring:
  application:
    name: FrontApplication
  jackson:
    time-zone: UTC

server:
  port: 8080
  tomcat:
    threads:
      max: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.genius.primavera: DEBUG

primavera:
  config:
    name: front
    enabled: true
    logs:
      path: ./logs/front
  services:
    account-url: http://localhost:8081
    order-url: http://localhost:8082
    product-url: http://localhost:8083