spring:
  jackson:
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

primavera:
  config:
    name: front
    enabled: true
    logs:
      path: ./logs/front
  services:
    account-url: http://localhost:8081
    order-url: http://localhost:8082
    product-url: http://localhost:8083