spring:
  application:
    name: ProductApplication
  jackson:
    time-zone: UTC
  data:
    mongodb:
      host: localhost
      port: 27017
      database: primavera_products
      username: primavera
      password: root
      authentication-database: admin

logging:
  level:
    root: INFO
    com.genius.primavera: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring.kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    group-id: product-service
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"

kafka:
  topics:
    order-events: order-events
    inventory-events: inventory-events

primavera:
  config:
    name: product
    enabled: true
    logs:
      path: ./logs/product