spring:
  application:
    name: ProductStreamingApplication
  profiles:
    active: local
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
        - sentry-appender
      test:
        - console-appender
  jackson:
    time-zone: UTC

logging:
  config: classpath:logback-spring.xml

primavera:
  logs:
    path: ./logs
