spring:
  application:
    name: ProductStreamingApplication
  profiles:
    active: local
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
        - sentry-appender
      test:
        - console-appender
  jackson:
    time-zone: UTC
  jmx:
    enabled: false

logging:
  config: classpath:logback-spring.xml

primavera:
  config:
    name: primavera
    enabled: true
    logs:
      path: ./logs

server:
  port: 8081
