spring:
  application:
    name: HierarchicalCommentApplication
  jackson:
    time-zone: UTC
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    sql-migration-suffixes: .sql
    locations: classpath:db/migration
    encoding: UTF-8
    fail-on-missing-locations: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
  type-aliases-package: com.genius.primavera.domain
  type-handlers-package: com.genius.primavera.domain

primavera:
  logs:
    path: ./logs

server:
  ssl:
    key-alias: primavera
    key-store: infrastructure/certs/primavera.p12
    key-store-type: PKCS12
    key-store-password: primavera
    enabled: true
  port: 8443