spring:
  application:
    name: Primavera
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/primavera?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: primavera
    password: primavera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true
  flyway:
    enabled: false
    encoding: UTF-8
    fail-on-missing-locations: false
    locations: classpath:db/migration
    table: SCHEMA_HISTORY
    baseline-on-migrate: false
    baseline-description: schema history
  aop:
    proxy-target-class: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
  type-aliases-package: com.genius.primavera.domain
  type-handlers-package: com.genius.primavera.domain

logging:
  config: classpath:logback.xml

server:
  ssl:
    key-alias: primavera
    key-store: chap11/primavera.p12
    key-store-type: PKCS12
    key-store-password: primavera
    enabled: true
  port: 8443