spring:
  config:
    activate:
      on-profile: local
    import:
      - "optional:vault:"
      - "optional:configserver:"
  aop:
    proxy-target-class: true
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: primavera-vault-token
      connection-timeout: 5000
      read-timeout: 15000
      fail-fast: false
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: HierarchicalCommentApplication
        application-name: HierarchicalCommentApplication
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: "BalancedHikariPool"
      leak-detection-threshold: 60000
      connection-test-query: "SELECT 1"
      validation-timeout: 5000
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true
  flyway:
    sql-migration-suffixes: .sql
    locations: classpath:db/migration
    encoding: UTF-8
    fail-on-missing-locations: false
    enabled: true
    baseline-on-migrate: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
  type-aliases-package: com.genius.primavera.domain
  type-handlers-package: com.genius.primavera.domain

server:
  ssl:
    key-alias: primavera
    key-store: classpath:certs/primavera.p12
    key-store-type: PKCS12
    key-store-password: primavera
    enabled: true
  port: 8443