spring:
  application:
    name: HierarchicalCommentApplication
  jackson:
    time-zone: UTC
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    sql-migration-suffixes: .sql
    locations: classpath:db/migration
    encoding: UTF-8
    fail-on-missing-locations: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
  type-aliases-package: com.genius.primavera.domain
  type-handlers-package: com.genius.primavera.domain

logging:
  level:
    root: INFO