spring:
  application:
    name: ProductBatchApplication
  profiles:
    active: local
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
      test:
        - console-appender
  jackson:
    time-zone: UTC
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never

logging:
  config: classpath:logback-spring.xml

primavera:
  logs:
    path: ./logs