spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: ${VAULT_SCHEME:http}
      authentication: TOKEN
      token: ${VAULT_TOKEN:primavera-vault-token}
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: ProductBatchApplication
        application-name: ProductBatchApplication
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: "BalancedHikariPool"
      leak-detection-threshold: 60000
      connection-test-query: "SELECT 1"
      validation-timeout: 5000
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      globally_quoted_identifiers: true
      jdbc:
        fetch_size: 30
        batch_size: 30
    open-in-view: false
  aop:
    proxy-target-class: false
    auto: false
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  jmx:
    enabled: true