server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        composite:
          - type: vault
            host: 127.0.0.1
            port: 8200
            scheme: http
            backend: secret
            profile-separator: /
            default-key: application
            authentication: TOKEN
            token: primavera-vault-token
          - type: git
            uri: https://github.com/csj4032/primavera
            search-paths: account,front,order,product
            default-label: master
            clone-on-start: false
          - type: native
            searchLocations: classpath:/config
        default-label: main
        bootstrap: false
    vault:
      enabled: true
      host: 127.0.0.1
      port: 8200
      scheme: http
      authentication: TOKEN
      token: primavera-vault-token