spring:
  application:
    name: ConfigurationApplication
  profiles:
    active: composite
    group:
      native:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
      composite:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
      test:
        - console-appender
  cloud:
    config:
      server:
        composite:
          - type: vault
            host: localhost
            port: 8200
            scheme: http
            backend: secret
            profile-separator: '/'
            kv-version: 2
            order: 1
            token: ${VAULT_TOKEN:primavera-vault-token}
          - type: native
            search-locations: classpath:/config
            order: 2
        bootstrap: false
    vault:
      uri: http://localhost:8200
      token: primavera-vault-token
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        application-name: application

logging:
  config: classpath:logback-spring.xml

primavera:
  config:
    logs:
      path: ./logs/configuration

server:
  port: 8888