spring:
  application:
    name: ConfigurationApplication
  profiles:
    active: local
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
      test:
        - console-appender
  jackson:
    time-zone: UTC
  jmx:
    enabled: false

management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
  jmx:
    enabled: false

server:
  port: 8888

logging:
  config: classpath:logback-spring.xml

primavera:
  config:
    name: configuration
    logs:
      path: ./logs/${primavera.config.name}