server:
  port: 8888

spring:
  application:
    name: ConfigurationApplication
  cloud:
    vault:
      uri: http://localhost:8200
      token: primavera-vault-token
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        application-name: application
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          backend: secret
          profile-separator: '/'
          kv-version: 2
        native:
          search-locations: classpath:/config
        bootstrap: false