-- ==============================================
-- Database: primavera (Chapter 18: Complex Microservices)
-- ==============================================

-- 주문 서비스용 테이블들
CREATE TABLE IF NOT EXISTS ORDERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_CREATED_AT (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_PRICE DECIMAL(10,2) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID) ON DELETE CASCADE,
    INDEX IDX_ORDER_ID (ORDER_ID),
    INDEX IDX_PRODUCT_ID (PRODUCT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 샘플 데이터
INSERT INTO ORDERS (ID, USER_ID, TOTAL_AMOUNT, STATUS) VALUES
(1, 'user001', 150000.00, 'COMPLETED'),
(2, 'user002', 89000.00, 'PENDING'),
(3, 'user003', 250000.00, 'SHIPPED'),
(4, 'user001', 45000.00, 'CANCELLED')
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

INSERT INTO ORDER_ITEMS (ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_PRICE) VALUES
(1, 1, 'prod001', 2, 75000.00, 150000.00),
(2, 2, 'prod002', 1, 89000.00, 89000.00),
(3, 3, 'prod003', 1, 250000.00, 250000.00),
(4, 4, 'prod004', 3, 15000.00, 45000.00)
ON DUPLICATE KEY UPDATE ORDER_ID = VALUES(ORDER_ID);

-- 인덱스 최적화
ANALYZE TABLE ORDERS;
ANALYZE TABLE ORDER_ITEMS;