-- ==============================================
-- Primavera Project - 통합 데이터베이스 초기화 스크립트 (Production)
-- MariaDB 11.4.7 - 운영환경 최적화 구조
-- ==============================================

-- 기본 데이터베이스 설정
ALTER DATABASE primavera CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ==============================================
-- 운영용 통합 데이터베이스 생성
-- ==============================================

-- 1. 운영용 애플리케이션 데이터베이스
CREATE DATABASE IF NOT EXISTS primavera_production CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 2. 마이크로서비스 데이터베이스 (운영용)
CREATE DATABASE IF NOT EXISTS primavera_microservices CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 3. 로그 및 모니터링 데이터베이스
CREATE DATABASE IF NOT EXISTS primavera_monitoring CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ==============================================
-- 권한 설정
-- ==============================================

-- 운영용 사용자 생성 (보안 강화)
CREATE USER IF NOT EXISTS 'primavera_app'@'%' IDENTIFIED BY '${PRIMAVERA_DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'primavera_ms'@'%' IDENTIFIED BY '${PRIMAVERA_MS_PASSWORD}';
CREATE USER IF NOT EXISTS 'primavera_monitor'@'%' IDENTIFIED BY '${PRIMAVERA_MONITOR_PASSWORD}';

-- 권한 부여 (최소 권한 원칙)
GRANT SELECT, INSERT, UPDATE, DELETE ON primavera_production.* TO 'primavera_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON primavera_microservices.* TO 'primavera_ms'@'%';
GRANT SELECT, INSERT ON primavera_monitoring.* TO 'primavera_monitor'@'%';

-- 관리자 권한 (필요시에만)
GRANT ALL PRIVILEGES ON primavera.* TO 'primavera'@'%' IDENTIFIED BY '${PRIMAVERA_ADMIN_PASSWORD}';
GRANT ALL PRIVILEGES ON primavera_production.* TO 'primavera'@'%';
GRANT ALL PRIVILEGES ON primavera_microservices.* TO 'primavera'@'%';
GRANT ALL PRIVILEGES ON primavera_monitoring.* TO 'primavera'@'%';

FLUSH PRIVILEGES;

-- ==============================================
-- 1. 운영용 애플리케이션 데이터베이스 (primavera_production)
-- ==============================================

USE primavera_production;

-- 사용자 및 권한 관리
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    LAST_LOGIN DATETIME,
    LOGIN_COUNT BIGINT DEFAULT 0,
    VERSION    BIGINT DEFAULT 0, -- 낙관적 락킹
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_CREATED_AT (CREATED_AT),
    INDEX IDX_LAST_LOGIN (LAST_LOGIN)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ROLES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    TYPE        INT                NOT NULL,
    IS_ACTIVE   BOOLEAN    DEFAULT TRUE,
    CREATED_AT  DATETIME   DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  DATETIME   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VERSION     BIGINT     DEFAULT 0,
    INDEX IDX_TYPE (TYPE),
    INDEX IDX_IS_ACTIVE (IS_ACTIVE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT   NOT NULL,
    ROLE_ID    BIGINT   NOT NULL,
    GRANTED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    GRANTED_BY BIGINT,
    EXPIRES_AT DATETIME,
    IS_ACTIVE  BOOLEAN  DEFAULT TRUE,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    FOREIGN KEY (GRANTED_BY) REFERENCES USERS (ID) ON DELETE SET NULL,
    UNIQUE KEY UNIQUE_USER_ROLE (USER_ID, ROLE_ID),
    INDEX IDX_GRANTED_AT (GRANTED_AT),
    INDEX IDX_EXPIRES_AT (EXPIRES_AT),
    INDEX IDX_IS_ACTIVE (IS_ACTIVE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 소셜 로그인 연결 정보 (보안 강화)
CREATE TABLE IF NOT EXISTS USER_CONNECTIONS
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID          BIGINT       NOT NULL,
    PROVIDER_ID      VARCHAR(50)  NOT NULL,
    PROVIDER_USER_ID VARCHAR(100) NOT NULL,
    DISPLAY_NAME     VARCHAR(100),
    PROFILE_URL      VARCHAR(500),
    IMAGE_URL        VARCHAR(500),
    ACCESS_TOKEN     TEXT, -- 암호화 필요
    REFRESH_TOKEN    TEXT, -- 암호화 필요
    EXPIRE_TIME      BIGINT,
    IS_ACTIVE        BOOLEAN  DEFAULT TRUE,
    CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_USED_AT     DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_PROVIDER_USER (PROVIDER_ID, PROVIDER_USER_ID),
    INDEX IDX_IS_ACTIVE (IS_ACTIVE),
    INDEX IDX_LAST_USED_AT (LAST_USED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 운영용 게시글 테이블
CREATE TABLE IF NOT EXISTS POSTS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID     BIGINT       NOT NULL,
    TITLE         VARCHAR(255) NOT NULL,
    CONTENT       LONGTEXT     NOT NULL,
    SUMMARY       TEXT,
    VIEW_COUNT    BIGINT      DEFAULT 0,
    LIKE_COUNT    BIGINT      DEFAULT 0,
    COMMENT_COUNT BIGINT      DEFAULT 0,
    STATUS        VARCHAR(20) DEFAULT 'DRAFT',
    PUBLISHED_AT  DATETIME,
    CREATED_AT    DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VERSION       BIGINT      DEFAULT 0,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    INDEX IDX_AUTHOR_ID (AUTHOR_ID),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_PUBLISHED_AT (PUBLISHED_AT),
    INDEX IDX_VIEW_COUNT (VIEW_COUNT),
    FULLTEXT IDX_TITLE_CONTENT (TITLE, CONTENT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 운영용 댓글 테이블
CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID    BIGINT   NOT NULL,
    PARENT_ID  BIGINT,
    AUTHOR_ID  BIGINT   NOT NULL,
    CONTENT    LONGTEXT NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    LIKE_COUNT BIGINT      DEFAULT 0,
    DEPTH      INT         DEFAULT 0,
    SORT_ORDER BIGINT      DEFAULT 0,
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VERSION    BIGINT      DEFAULT 0,
    FOREIGN KEY (POST_ID) REFERENCES POSTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ID) REFERENCES COMMENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    INDEX IDX_POST_ID (POST_ID),
    INDEX IDX_PARENT_ID (PARENT_ID),
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_DEPTH_SORT (DEPTH, SORT_ORDER)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 파일 관리 테이블 (운영 최적화)
CREATE TABLE IF NOT EXISTS FILE_UPLOADS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID           BIGINT,
    ORIGINAL_FILENAME VARCHAR(255) NOT NULL,
    STORED_FILENAME   VARCHAR(255) NOT NULL,
    FILE_PATH         VARCHAR(500) NOT NULL,
    FILE_SIZE         BIGINT       NOT NULL,
    CONTENT_TYPE      VARCHAR(100),
    FILE_TYPE         VARCHAR(50),
    UPLOAD_STATUS     VARCHAR(20) DEFAULT 'UPLOADED',
    VIRUS_SCAN_STATUS VARCHAR(20) DEFAULT 'PENDING',
    VIRUS_SCAN_RESULT VARCHAR(100),
    PROCESSED_AT      DATETIME,
    UPLOADED_BY       BIGINT,
    ACCESS_COUNT      BIGINT      DEFAULT 0,
    LAST_ACCESS_AT    DATETIME,
    RETENTION_UNTIL   DATETIME, -- 데이터 보존 기간
    CREATED_AT        DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES POSTS (ID) ON DELETE SET NULL,
    FOREIGN KEY (UPLOADED_BY) REFERENCES USERS (ID) ON DELETE SET NULL,
    INDEX IDX_POST_ID (POST_ID),
    INDEX IDX_FILE_TYPE (FILE_TYPE),
    INDEX IDX_UPLOAD_STATUS (UPLOAD_STATUS),
    INDEX IDX_VIRUS_SCAN_STATUS (VIRUS_SCAN_STATUS),
    INDEX IDX_UPLOADED_BY (UPLOADED_BY),
    INDEX IDX_RETENTION_UNTIL (RETENTION_UNTIL)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자 세션 관리 (보안)
CREATE TABLE IF NOT EXISTS USER_SESSIONS
(
    ID            VARCHAR(128) PRIMARY KEY,
    USER_ID       BIGINT       NOT NULL,
    IP_ADDRESS    VARCHAR(45)  NOT NULL,
    USER_AGENT    TEXT,
    CREATED_AT    DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_ACCESS   DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    EXPIRES_AT    DATETIME     NOT NULL,
    IS_ACTIVE     BOOLEAN  DEFAULT TRUE,
    SESSION_DATA  JSON,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_EXPIRES_AT (EXPIRES_AT),
    INDEX IDX_IS_ACTIVE (IS_ACTIVE),
    INDEX IDX_IP_ADDRESS (IP_ADDRESS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 감사 로그 테이블
CREATE TABLE IF NOT EXISTS AUDIT_LOGS
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    TABLE_NAME      VARCHAR(64)  NOT NULL,
    RECORD_ID       BIGINT       NOT NULL,
    ACTION          VARCHAR(20)  NOT NULL, -- INSERT, UPDATE, DELETE
    OLD_VALUES      JSON,
    NEW_VALUES      JSON,
    CHANGED_BY      BIGINT,
    CHANGE_REASON   VARCHAR(255),
    IP_ADDRESS      VARCHAR(45),
    USER_AGENT      TEXT,
    CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CHANGED_BY) REFERENCES USERS (ID) ON DELETE SET NULL,
    INDEX IDX_TABLE_RECORD (TABLE_NAME, RECORD_ID),
    INDEX IDX_ACTION (ACTION),
    INDEX IDX_CHANGED_BY (CHANGED_BY),
    INDEX IDX_CREATED_AT (CREATED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ==============================================
-- 2. 마이크로서비스 데이터베이스 (primavera_microservices)
-- ==============================================

USE primavera_microservices;

-- 마이크로서비스용 사용자 테이블 (운영 최적화)
CREATE TABLE IF NOT EXISTS MS_USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    SERVICE_ID VARCHAR(50)         NOT NULL,
    VERSION    BIGINT      DEFAULT 0,
    INDEX IDX_MS_EMAIL (EMAIL),
    INDEX IDX_MS_STATUS (STATUS),
    INDEX IDX_MS_SERVICE_ID (SERVICE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 주문 서비스 테이블 (운영 최적화)
CREATE TABLE IF NOT EXISTS MS_ORDERS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_NUMBER   VARCHAR(50) UNIQUE NOT NULL,
    USER_ID        BIGINT             NOT NULL,
    TOTAL_AMOUNT   DECIMAL(12, 2)     NOT NULL,
    ORDER_STATUS   VARCHAR(20) DEFAULT 'PENDING',
    PAYMENT_STATUS VARCHAR(20) DEFAULT 'UNPAID',
    CREATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PROCESSED_AT   DATETIME,
    COMPLETED_AT   DATETIME,
    VERSION        BIGINT      DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES MS_USERS (ID) ON DELETE CASCADE,
    INDEX IDX_MS_ORDER_NUMBER (ORDER_NUMBER),
    INDEX IDX_MS_ORDER_STATUS (ORDER_STATUS),
    INDEX IDX_MS_PAYMENT_STATUS (PAYMENT_STATUS),
    INDEX IDX_MS_CREATED_AT (CREATED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 상품 서비스 테이블 (운영 최적화)
CREATE TABLE IF NOT EXISTS MS_PRODUCTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_CODE VARCHAR(50) UNIQUE NOT NULL,
    NAME         VARCHAR(255)       NOT NULL,
    DESCRIPTION  TEXT,
    PRICE        DECIMAL(10, 2)     NOT NULL,
    STOCK        INT         DEFAULT 0,
    STATUS       VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT   DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VERSION      BIGINT      DEFAULT 0,
    INDEX IDX_MS_PRODUCT_CODE (PRODUCT_CODE),
    INDEX IDX_MS_PRODUCT_STATUS (STATUS),
    INDEX IDX_MS_STOCK (STOCK)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 계정 서비스 테이블 (운영 최적화)
CREATE TABLE IF NOT EXISTS MS_ACCOUNTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID      BIGINT      NOT NULL,
    ACCOUNT_TYPE VARCHAR(20) NOT NULL,
    BALANCE      DECIMAL(15, 2) DEFAULT 0.00,
    CURRENCY     VARCHAR(3)     DEFAULT 'KRW',
    STATUS       VARCHAR(20)    DEFAULT 'ACTIVE',
    CREATED_AT   DATETIME       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    VERSION      BIGINT         DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES MS_USERS (ID) ON DELETE CASCADE,
    INDEX IDX_MS_ACCOUNT_USER_ID (USER_ID),
    INDEX IDX_MS_ACCOUNT_TYPE (ACCOUNT_TYPE),
    INDEX IDX_MS_ACCOUNT_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 마이크로서비스 트랜잭션 로그
CREATE TABLE IF NOT EXISTS MS_TRANSACTION_LOGS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_ID    VARCHAR(100) UNIQUE NOT NULL,
    SERVICE_NAME      VARCHAR(50)         NOT NULL,
    ACTION            VARCHAR(50)         NOT NULL,
    REQUEST_DATA      JSON,
    RESPONSE_DATA     JSON,
    STATUS            VARCHAR(20) DEFAULT 'PENDING',
    ERROR_MESSAGE     TEXT,
    PROCESSING_TIME   BIGINT      DEFAULT 0,
    CREATED_AT        DATETIME    DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT      DATETIME,
    INDEX IDX_MS_TRANSACTION_ID (TRANSACTION_ID),
    INDEX IDX_MS_SERVICE_NAME (SERVICE_NAME),
    INDEX IDX_MS_STATUS (STATUS),
    INDEX IDX_MS_CREATED_AT (CREATED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ==============================================
-- 3. 로그 및 모니터링 데이터베이스 (primavera_monitoring)
-- ==============================================

USE primavera_monitoring;

-- 시스템 로그 테이블 (대용량 최적화)
CREATE TABLE IF NOT EXISTS SYSTEM_LOGS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOG_LEVEL         VARCHAR(10)  NOT NULL,
    LOGGER_NAME       VARCHAR(255) NOT NULL,
    MESSAGE           LONGTEXT     NOT NULL,
    EXCEPTION_CLASS   VARCHAR(255),
    EXCEPTION_MESSAGE TEXT,
    STACK_TRACE       LONGTEXT,
    USER_ID           BIGINT,
    SESSION_ID        VARCHAR(128),
    REQUEST_URI       VARCHAR(500),
    REQUEST_METHOD    VARCHAR(10),
    USER_AGENT        TEXT,
    CLIENT_IP         VARCHAR(45),
    SERVER_NAME       VARCHAR(100),
    THREAD_NAME       VARCHAR(100),
    SENTRY_EVENT_ID   VARCHAR(100),
    CREATED_AT        DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_LOG_LEVEL (LOG_LEVEL),
    INDEX IDX_LOGGER_NAME (LOGGER_NAME),
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_CREATED_AT (CREATED_AT),
    INDEX IDX_SENTRY_EVENT_ID (SENTRY_EVENT_ID),
    INDEX IDX_CLIENT_IP (CLIENT_IP)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci
  PARTITION BY RANGE (TO_DAYS(CREATED_AT)) (
    PARTITION p202401 VALUES LESS THAN (TO_DAYS('2024-02-01')),
    PARTITION p202402 VALUES LESS THAN (TO_DAYS('2024-03-01')),
    PARTITION p202403 VALUES LESS THAN (TO_DAYS('2024-04-01')),
    PARTITION p202404 VALUES LESS THAN (TO_DAYS('2024-05-01')),
    PARTITION p202405 VALUES LESS THAN (TO_DAYS('2024-06-01')),
    PARTITION p202406 VALUES LESS THAN (TO_DAYS('2024-07-01')),
    PARTITION p202407 VALUES LESS THAN (TO_DAYS('2024-08-01')),
    PARTITION p202408 VALUES LESS THAN (TO_DAYS('2024-09-01')),
    PARTITION p202409 VALUES LESS THAN (TO_DAYS('2024-10-01')),
    PARTITION p202410 VALUES LESS THAN (TO_DAYS('2024-11-01')),
    PARTITION p202411 VALUES LESS THAN (TO_DAYS('2024-12-01')),
    PARTITION p202412 VALUES LESS THAN (TO_DAYS('2025-01-01')),
    PARTITION p_future VALUES LESS THAN MAXVALUE
  );

-- 성능 메트릭 테이블
CREATE TABLE IF NOT EXISTS PERFORMANCE_METRICS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    METRIC_NAME       VARCHAR(100) NOT NULL,
    METRIC_VALUE      DECIMAL(15, 4),
    METRIC_UNIT       VARCHAR(20),
    SERVICE_NAME      VARCHAR(50),
    ENDPOINT          VARCHAR(255),
    HTTP_STATUS       INT,
    RESPONSE_TIME_MS  BIGINT,
    MEMORY_USAGE_MB   BIGINT,
    CPU_USAGE_PERCENT DECIMAL(5, 2),
    CREATED_AT        DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_METRIC_NAME (METRIC_NAME),
    INDEX IDX_SERVICE_NAME (SERVICE_NAME),
    INDEX IDX_ENDPOINT (ENDPOINT),
    INDEX IDX_CREATED_AT (CREATED_AT),
    INDEX IDX_RESPONSE_TIME (RESPONSE_TIME_MS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 보안 이벤트 로그
CREATE TABLE IF NOT EXISTS SECURITY_EVENTS
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    EVENT_TYPE       VARCHAR(50)  NOT NULL,
    SEVERITY         VARCHAR(20)  NOT NULL,
    USER_ID          BIGINT,
    IP_ADDRESS       VARCHAR(45)  NOT NULL,
    USER_AGENT       TEXT,
    REQUEST_URI      VARCHAR(500),
    EVENT_DETAILS    JSON,
    THREAT_LEVEL     INT DEFAULT 0,
    IS_BLOCKED       BOOLEAN DEFAULT FALSE,
    RESPONSE_ACTION  VARCHAR(100),
    CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_EVENT_TYPE (EVENT_TYPE),
    INDEX IDX_SEVERITY (SEVERITY),
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_IP_ADDRESS (IP_ADDRESS),
    INDEX IDX_THREAT_LEVEL (THREAT_LEVEL),
    INDEX IDX_CREATED_AT (CREATED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ==============================================
-- 운영용 기본 데이터 (최소한으로)
-- ==============================================

USE primavera_production;

INSERT INTO ROLES (ID, NAME, DESCRIPTION, TYPE, IS_ACTIVE)
VALUES (1, 'ROLE_ADMIN', '시스템 관리자', 1, TRUE),
       (2, 'ROLE_MANAGER', '매니저', 2, TRUE),
       (3, 'ROLE_USER', '일반 사용자', 3, TRUE)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

-- 운영용 관리자 계정 (초기 설정용 - 이후 변경 필요)
INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS)
VALUES (1, 'admin@primavera.com', '{bcrypt}$2a$12$CHANGE_THIS_PASSWORD_HASH', 'SystemAdmin', 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID, GRANTED_BY)
VALUES (1, 1, NULL)
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

-- ==============================================
-- 인덱스 최적화 및 테이블 분석
-- ==============================================

USE primavera_production;
ANALYZE TABLE USERS, ROLES, USER_ROLES, POSTS, COMMENTS, FILE_UPLOADS, USER_SESSIONS, AUDIT_LOGS;

USE primavera_microservices;
ANALYZE TABLE MS_USERS, MS_ORDERS, MS_PRODUCTS, MS_ACCOUNTS, MS_TRANSACTION_LOGS;

USE primavera_monitoring;
ANALYZE TABLE SYSTEM_LOGS, PERFORMANCE_METRICS, SECURITY_EVENTS;

-- 기본 데이터베이스로 복귀
USE primavera;