-- ==============================================
-- Primavera Project - 통합 데이터베이스 초기화 스크립트 (Local)
-- MariaDB 11.4.7 - 3개 데이터베이스 최적화 구조
-- ==============================================

-- 기본 데이터베이스 설정
ALTER DATABASE primavera CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ==============================================
-- 통합 데이터베이스 생성 (3개 최적화 구조)
-- ==============================================

-- 1. 개발/학습용 통합 데이터베이스 (chap01-chap17)
CREATE DATABASE IF NOT EXISTS primavera_development CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 2. 마이크로서비스 데이터베이스 (chap18 운영용)
CREATE DATABASE IF NOT EXISTS primavera_microservices CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 3. 테스트 전용 데이터베이스
CREATE DATABASE IF NOT EXISTS primavera_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ==============================================
-- 권한 설정
-- ==============================================

GRANT ALL PRIVILEGES ON primavera.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_development.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_microservices.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_test.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';

FLUSH PRIVILEGES;

-- ==============================================
-- 1. 개발/학습용 통합 데이터베이스 (primavera_development)
-- 대상: chap01-chap17의 모든 학습용 테이블
-- ==============================================

USE primavera_development;

-- 공통 사용자 및 권한 테이블 (모든 챕터 공통)
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ROLES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    TYPE        INT                NOT NULL,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT NOT NULL,
    ROLE_ID    BIGINT NOT NULL,
    GRANTED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    GRANTED_BY BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    FOREIGN KEY (GRANTED_BY) REFERENCES USERS (ID) ON DELETE SET NULL,
    UNIQUE KEY UNIQUE_USER_ROLE (USER_ID, ROLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 소셜 로그인 연결 정보 (chap10+)
CREATE TABLE IF NOT EXISTS USER_CONNECTIONS
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID          BIGINT       NOT NULL,
    PROVIDER_ID      VARCHAR(50)  NOT NULL,
    PROVIDER_USER_ID VARCHAR(100) NOT NULL,
    DISPLAY_NAME     VARCHAR(100),
    PROFILE_URL      VARCHAR(500),
    IMAGE_URL        VARCHAR(500),
    ACCESS_TOKEN     TEXT,
    REFRESH_TOKEN    TEXT,
    EXPIRE_TIME      BIGINT,
    CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_PROVIDER_USER (PROVIDER_ID, PROVIDER_USER_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 기본 예제용 테이블들 (chap03-05)
CREATE TABLE IF NOT EXISTS BASIC_WINNERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(50) NOT NULL,
    YEAR       INT         NOT NULL,
    SPORT      VARCHAR(50) NOT NULL,
    PRIZE      VARCHAR(50) NOT NULL,
    AMOUNT     DECIMAL(10, 2) DEFAULT 0.00,
    CREATED_AT DATETIME       DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- MyBatis 예제용 테이블들 (chap06-11)
CREATE TABLE IF NOT EXISTS MYBATIS_POSTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    SUBJECT    VARCHAR(255) NOT NULL,
    CONTENTS   TEXT         NOT NULL,
    WRITER_ID  BIGINT       NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_MYBATIS_POSTS_WRITER_ID FOREIGN KEY (WRITER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    INDEX IDX_MYBATIS_POSTS_WRITER_ID (WRITER_ID),
    INDEX IDX_MYBATIS_POSTS_CREATED_AT (CREATED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Single Table Inheritance (Item 계층)
CREATE TABLE IF NOT EXISTS MYBATIS_ITEMS
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE   VARCHAR(10)  NOT NULL,
    NAME   VARCHAR(100) NOT NULL,
    PRICE  INT          NOT NULL DEFAULT 0,
    ARTIST VARCHAR(100),
    AUTHOR VARCHAR(100),
    ISBN   VARCHAR(20),
    INDEX IDX_MYBATIS_ITEM_TYPE (TYPE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 상속 계층 구조 테이블들 (Joined Strategy)
CREATE TABLE IF NOT EXISTS MYBATIS_FAMILY
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME            VARCHAR(100) NOT NULL,
    SCIENTIFIC_NAME VARCHAR(100) NOT NULL,
    HABITAT         VARCHAR(255),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_CANIDAE
(
    ID         BIGINT PRIMARY KEY,
    SPECIES    VARCHAR(100),
    HABITAT    VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID) REFERENCES MYBATIS_FAMILY (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS MYBATIS_FELIDAE
(
    ID         BIGINT PRIMARY KEY,
    BREED      VARCHAR(100),
    TERRITORY  VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID) REFERENCES MYBATIS_FAMILY (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- MyBatis 게시판 테이블들 (chap12-13)
CREATE TABLE IF NOT EXISTS BOARD_ARTICLES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    P_ID       BIGINT       NOT NULL DEFAULT 0,
    REFERENCE  BIGINT       NOT NULL,
    STEP       INT          NOT NULL,
    LEVEL      INT          NOT NULL,
    AUTHOR     BIGINT       NOT NULL,
    SUBJECT    VARCHAR(200) NOT NULL,
    STATUS     TINYINT      NOT NULL,
    HIT        INT          NOT NULL DEFAULT 0,
    RECOMMEND  INT          NOT NULL DEFAULT 0,
    DISAPPROVE INT          NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP    NULL     DEFAULT NULL,
    FOREIGN KEY (AUTHOR) REFERENCES USERS (ID) ON DELETE CASCADE,
    INDEX IDX_BOARD_REFERENCE (REFERENCE),
    INDEX IDX_BOARD_STEP (STEP),
    INDEX IDX_BOARD_LEVEL (LEVEL)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS BOARD_ARTICLE_CONTENTS
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID BIGINT DEFAULT NULL,
    CONTENTS   TEXT   DEFAULT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES BOARD_ARTICLES (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS BOARD_COMMENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID BIGINT      NOT NULL,
    LEVEL      INT         NOT NULL,
    STEP       INT         NOT NULL,
    COMMENT    TEXT        NOT NULL,
    AUTHOR     VARCHAR(45) NOT NULL,
    STATUS     TINYINT     NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP   NULL     DEFAULT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES BOARD_ARTICLES (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS BOARD_ATTACHMENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID BIGINT       NOT NULL,
    NAME       VARCHAR(100) NOT NULL,
    PATH       VARCHAR(200) NOT NULL,
    SIZE       INT          NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP    NULL     DEFAULT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES BOARD_ARTICLES (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- JPA 고급 매핑 테이블들 (chap14-15)
CREATE TABLE IF NOT EXISTS JPA_MEMBERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100)        NOT NULL,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_ADDRESSES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID   BIGINT       NOT NULL,
    STREET      VARCHAR(255) NOT NULL,
    CITY        VARCHAR(100) NOT NULL,
    POSTAL_CODE VARCHAR(20)  NOT NULL,
    COUNTRY     VARCHAR(100) NOT NULL DEFAULT 'South Korea',
    CREATED_AT  DATETIME              DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES JPA_MEMBERS (ID) ON DELETE CASCADE,
    INDEX IDX_JPA_MEMBER_ID (MEMBER_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_PRODUCTS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(200)   NOT NULL,
    DESCRIPTION TEXT,
    PRICE       DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    CREATED_AT  DATETIME                DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_SERIALS
(
    ID                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID             BIGINT              NOT NULL,
    SERIAL_NUMBER          VARCHAR(100) UNIQUE NOT NULL,
    MANUFACTURE_DATE       DATE                NOT NULL,
    WARRANTY_PERIOD_MONTHS INT      DEFAULT 12,
    CREATED_AT             DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES JPA_PRODUCTS (ID) ON DELETE CASCADE,
    INDEX IDX_JPA_PRODUCT_ID (PRODUCT_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- JPA 게시판 및 파일 처리 테이블들 (chap16-17)
CREATE TABLE IF NOT EXISTS JPA_POSTS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID     BIGINT       NOT NULL,
    TITLE         VARCHAR(255) NOT NULL,
    CONTENT       LONGTEXT     NOT NULL,
    SUMMARY       TEXT,
    VIEW_COUNT    BIGINT      DEFAULT 0,
    LIKE_COUNT    BIGINT      DEFAULT 0,
    COMMENT_COUNT BIGINT      DEFAULT 0,
    STATUS        VARCHAR(20) DEFAULT 'PUBLISHED',
    PUBLISHED_AT  DATETIME,
    CREATED_AT    DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    INDEX IDX_JPA_AUTHOR_ID (AUTHOR_ID),
    INDEX IDX_JPA_STATUS (STATUS),
    FULLTEXT IDX_JPA_TITLE_CONTENT (TITLE, CONTENT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS JPA_COMMENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID    BIGINT   NOT NULL,
    PARENT_ID  BIGINT,
    AUTHOR_ID  BIGINT   NOT NULL,
    CONTENT    LONGTEXT NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    LIKE_COUNT BIGINT      DEFAULT 0,
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES JPA_POSTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ID) REFERENCES JPA_COMMENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 파일 처리 테이블들 (chap17)
CREATE TABLE IF NOT EXISTS FILE_UPLOADS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID           BIGINT,
    ORIGINAL_FILENAME VARCHAR(255) NOT NULL,
    STORED_FILENAME   VARCHAR(255) NOT NULL,
    FILE_PATH         VARCHAR(500) NOT NULL,
    FILE_SIZE         BIGINT       NOT NULL,
    CONTENT_TYPE      VARCHAR(100),
    FILE_TYPE         VARCHAR(50),
    UPLOAD_STATUS     VARCHAR(20) DEFAULT 'UPLOADED',
    PROCESSED_AT      DATETIME,
    CREATED_AT        DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES JPA_POSTS (ID) ON DELETE SET NULL,
    INDEX IDX_FILE_POST_ID (POST_ID),
    INDEX IDX_FILE_TYPE (FILE_TYPE),
    INDEX IDX_FILE_UPLOAD_STATUS (UPLOAD_STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS FILE_PROCESSING_RESULTS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_UPLOAD_ID     BIGINT      NOT NULL,
    PROCESSING_TYPE    VARCHAR(50) NOT NULL,
    RESULT_STATUS      VARCHAR(20) NOT NULL,
    RESULT_MESSAGE     TEXT,
    RESULT_DATA        JSON,
    PROCESSED_ROWS     INT      DEFAULT 0,
    ERROR_ROWS         INT      DEFAULT 0,
    PROCESSING_TIME_MS BIGINT   DEFAULT 0,
    CREATED_AT         DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FILE_UPLOAD_ID) REFERENCES FILE_UPLOADS (ID) ON DELETE CASCADE,
    INDEX IDX_FILE_PROCESSING_UPLOAD_ID (FILE_UPLOAD_ID),
    INDEX IDX_FILE_PROCESSING_TYPE (PROCESSING_TYPE),
    INDEX IDX_FILE_PROCESSING_STATUS (RESULT_STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 재무 데이터 테이블 (Excel 처리 예제)
CREATE TABLE IF NOT EXISTS FINANCIAL_DATA
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_UPLOAD_ID BIGINT,
    COMPANY_CODE   VARCHAR(20)  NOT NULL,
    COMPANY_NAME   VARCHAR(100) NOT NULL,
    FISCAL_YEAR    INT          NOT NULL,
    QUARTER        INT          NOT NULL,
    REVENUE        DECIMAL(15, 2) DEFAULT 0,
    PROFIT         DECIMAL(15, 2) DEFAULT 0,
    ASSETS         DECIMAL(15, 2) DEFAULT 0,
    LIABILITIES    DECIMAL(15, 2) DEFAULT 0,
    EQUITY         DECIMAL(15, 2) DEFAULT 0,
    CREATED_AT     DATETIME       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FILE_UPLOAD_ID) REFERENCES FILE_UPLOADS (ID) ON DELETE SET NULL,
    INDEX IDX_FINANCIAL_COMPANY_CODE (COMPANY_CODE),
    INDEX IDX_FINANCIAL_FISCAL_YEAR (FISCAL_YEAR),
    UNIQUE KEY UNIQUE_FINANCIAL_COMPANY_QUARTER (COMPANY_CODE, FISCAL_YEAR, QUARTER)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 카카오톡 채팅 데이터 테이블 (CSV 처리 예제)
CREATE TABLE IF NOT EXISTS KAKAOTALK_MESSAGES
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_UPLOAD_ID  BIGINT,
    CHAT_DATE       DATE         NOT NULL,
    CHAT_TIME       TIME         NOT NULL,
    SENDER_NAME     VARCHAR(100) NOT NULL,
    MESSAGE_TEXT    LONGTEXT     NOT NULL,
    MESSAGE_LENGTH  INT         DEFAULT 0,
    WORD_COUNT      INT         DEFAULT 0,
    SENTIMENT_SCORE DECIMAL(3, 2),
    CONTAINS_EMOJI  BOOLEAN     DEFAULT FALSE,
    CONTAINS_URL    BOOLEAN     DEFAULT FALSE,
    LANGUAGE        VARCHAR(10) DEFAULT 'ko',
    CREATED_AT      DATETIME    DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FILE_UPLOAD_ID) REFERENCES FILE_UPLOADS (ID) ON DELETE SET NULL,
    INDEX IDX_KAKAO_CHAT_DATE (CHAT_DATE),
    INDEX IDX_KAKAO_SENDER_NAME (SENDER_NAME),
    INDEX IDX_KAKAO_SENTIMENT_SCORE (SENTIMENT_SCORE),
    FULLTEXT IDX_KAKAO_MESSAGE_TEXT (MESSAGE_TEXT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 시스템 로그 테이블 (Sentry 연동)
CREATE TABLE IF NOT EXISTS SYSTEM_LOGS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOG_LEVEL         VARCHAR(10)  NOT NULL,
    LOGGER_NAME       VARCHAR(255) NOT NULL,
    MESSAGE           LONGTEXT     NOT NULL,
    EXCEPTION_CLASS   VARCHAR(255),
    EXCEPTION_MESSAGE TEXT,
    STACK_TRACE       LONGTEXT,
    USER_ID           BIGINT,
    SESSION_ID        VARCHAR(100),
    REQUEST_URI       VARCHAR(500),
    REQUEST_METHOD    VARCHAR(10),
    USER_AGENT        TEXT,
    CLIENT_IP         VARCHAR(45),
    SERVER_NAME       VARCHAR(100),
    THREAD_NAME       VARCHAR(100),
    SENTRY_EVENT_ID   VARCHAR(100),
    CREATED_AT        DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE SET NULL,
    INDEX IDX_SYSTEM_LOG_LEVEL (LOG_LEVEL),
    INDEX IDX_SYSTEM_LOGGER_NAME (LOGGER_NAME),
    INDEX IDX_SYSTEM_USER_ID (USER_ID),
    INDEX IDX_SYSTEM_CREATED_AT (CREATED_AT),
    INDEX IDX_SYSTEM_SENTRY_EVENT_ID (SENTRY_EVENT_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 통합 시퀀스 관리 테이블
CREATE TABLE IF NOT EXISTS SEQUENCE_MANAGEMENT
(
    SEQUENCE_NAME VARCHAR(50) PRIMARY KEY,
    NEXT_VAL      BIGINT NOT NULL DEFAULT 1,
    CHAPTER       VARCHAR(10),
    DESCRIPTION   VARCHAR(255)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ==============================================
-- 기본 데이터 삽입
-- ==============================================

INSERT INTO ROLES (ID, NAME, DESCRIPTION, TYPE)
VALUES (1, 'ROLE_ADMIN', '시스템 관리자', 1),
       (2, 'ROLE_MANAGER', '매니저', 2),
       (3, 'ROLE_USER', '일반 사용자', 3),
       (4, 'ROLE_GUEST', '게스트', 4)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS)
VALUES (1, 'genius@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Genius', 'ACTIVE'),
       (2, 'admin@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Administrator', 'ACTIVE'),
       (3, 'user@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'User', 'ACTIVE'),
       (4, 'manager@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Manager', 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID, GRANTED_BY)
VALUES (1, 1, NULL), (1, 2, NULL), (1, 3, NULL),
       (2, 1, 1), (2, 2, 1),
       (3, 3, 2),
       (4, 2, 1), (4, 3, 1)
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

INSERT INTO BASIC_WINNERS (NAME, YEAR, SPORT, PRIZE, AMOUNT)
VALUES ('Lionel Messi', 2023, 'Football', 'Ballon d''Or', 1000000.00),
       ('Erling Haaland', 2023, 'Football', 'Golden Boot', 500000.00),
       ('Lewis Hamilton', 2023, 'Formula 1', 'World Championship', 2000000.00),
       ('Serena Williams', 2023, 'Tennis', 'Wimbledon', 750000.00),
       ('Tiger Woods', 2023, 'Golf', 'Masters Tournament', 1500000.00)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO SEQUENCE_MANAGEMENT (SEQUENCE_NAME, NEXT_VAL, CHAPTER, DESCRIPTION)
VALUES ('unified_sequence', 1, 'ALL', '통합 시퀀스 관리'),
       ('mybatis_sequence', 1, 'CHAP06-11', 'MyBatis 전용 시퀀스'),
       ('jpa_sequence', 1, 'CHAP14-17', 'JPA 전용 시퀀스')
ON DUPLICATE KEY UPDATE NEXT_VAL = VALUES(NEXT_VAL);

-- ==============================================
-- 2. 마이크로서비스 데이터베이스 (primavera_microservices)
-- 대상: chap18 (마이크로서비스 아키텍처)
-- ==============================================

USE primavera_microservices;

-- 마이크로서비스용 기본 사용자 테이블
CREATE TABLE IF NOT EXISTS MS_USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    SERVICE_ID VARCHAR(50)         NOT NULL,
    INDEX IDX_MS_EMAIL (EMAIL),
    INDEX IDX_MS_STATUS (STATUS),
    INDEX IDX_MS_SERVICE_ID (SERVICE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 주문 서비스 테이블
CREATE TABLE IF NOT EXISTS MS_ORDERS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_NUMBER   VARCHAR(50) UNIQUE NOT NULL,
    USER_ID        BIGINT             NOT NULL,
    TOTAL_AMOUNT   DECIMAL(12, 2)     NOT NULL,
    ORDER_STATUS   VARCHAR(20) DEFAULT 'PENDING',
    PAYMENT_STATUS VARCHAR(20) DEFAULT 'UNPAID',
    CREATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES MS_USERS (ID) ON DELETE CASCADE,
    INDEX IDX_MS_ORDER_NUMBER (ORDER_NUMBER),
    INDEX IDX_MS_ORDER_STATUS (ORDER_STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 상품 서비스 테이블
CREATE TABLE IF NOT EXISTS MS_PRODUCTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_CODE VARCHAR(50) UNIQUE NOT NULL,
    NAME         VARCHAR(255)       NOT NULL,
    DESCRIPTION  TEXT,
    PRICE        DECIMAL(10, 2)     NOT NULL,
    STOCK        INT         DEFAULT 0,
    STATUS       VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT   DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_MS_PRODUCT_CODE (PRODUCT_CODE),
    INDEX IDX_MS_PRODUCT_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 계정 서비스 테이블
CREATE TABLE IF NOT EXISTS MS_ACCOUNTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID      BIGINT      NOT NULL,
    ACCOUNT_TYPE VARCHAR(20) NOT NULL,
    BALANCE      DECIMAL(15, 2) DEFAULT 0.00,
    CURRENCY     VARCHAR(3)     DEFAULT 'KRW',
    STATUS       VARCHAR(20)    DEFAULT 'ACTIVE',
    CREATED_AT   DATETIME       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES MS_USERS (ID) ON DELETE CASCADE,
    INDEX IDX_MS_ACCOUNT_USER_ID (USER_ID),
    INDEX IDX_MS_ACCOUNT_TYPE (ACCOUNT_TYPE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 마이크로서비스 데이터 삽입
INSERT INTO MS_USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS, SERVICE_ID)
VALUES (1, 'front@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'FrontUser', 'ACTIVE', 'front-service'),
       (2, 'account@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'AccountUser', 'ACTIVE', 'account-service'),
       (3, 'product@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'ProductUser', 'ACTIVE', 'product-service'),
       (4, 'order@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'OrderUser', 'ACTIVE', 'order-service')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO MS_PRODUCTS (PRODUCT_CODE, NAME, DESCRIPTION, PRICE, STOCK)
VALUES ('PRD001', 'Spring Boot 완전정복', 'Spring Boot 교육서적', 35000.00, 100),
       ('PRD002', 'Java 프로그래밍 마스터', 'Java 고급 프로그래밍 가이드', 42000.00, 50),
       ('PRD003', 'Microservices 아키텍처', '마이크로서비스 설계 패턴', 38000.00, 75)
ON DUPLICATE KEY UPDATE PRODUCT_CODE = VALUES(PRODUCT_CODE);

INSERT INTO MS_ACCOUNTS (USER_ID, ACCOUNT_TYPE, BALANCE, CURRENCY)
VALUES (1, 'CHECKING', 1000000.00, 'KRW'),
       (2, 'SAVINGS', 5000000.00, 'KRW'),
       (3, 'CHECKING', 2500000.00, 'KRW'),
       (4, 'SAVINGS', 3000000.00, 'KRW')
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

-- ==============================================
-- 3. 테스트용 데이터베이스 (primavera_test)
-- ==============================================

USE primavera_test;

-- 테스트용 기본 테이블들 (간소화)
CREATE TABLE IF NOT EXISTS TEST_USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TEST_POSTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID  BIGINT       NOT NULL,
    TITLE      VARCHAR(255) NOT NULL,
    CONTENT    TEXT         NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AUTHOR_ID) REFERENCES TEST_USERS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 테스트 데이터
INSERT INTO TEST_USERS (EMAIL, NICKNAME)
VALUES ('test1@example.com', 'Tester1'),
       ('test2@example.com', 'Tester2'),
       ('test3@example.com', 'Tester3')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO TEST_POSTS (AUTHOR_ID, TITLE, CONTENT)
VALUES (1, 'Test Post 1', 'This is a test content for automated testing.'),
       (1, 'Test Post 2', 'Another test content with different data.'),
       (2, 'Test Post 3', 'User 2 test content for validation.'),
       (3, 'Test Post 4', 'Final test content for comprehensive testing.')
ON DUPLICATE KEY UPDATE AUTHOR_ID = VALUES(AUTHOR_ID);

-- ==============================================
-- 인덱스 최적화
-- ==============================================

USE primavera_development;
ANALYZE TABLE USERS, ROLES, USER_ROLES, MYBATIS_POSTS, JPA_POSTS, BOARD_ARTICLES;

USE primavera_microservices;
ANALYZE TABLE MS_USERS, MS_ORDERS, MS_PRODUCTS, MS_ACCOUNTS;

USE primavera_test;
ANALYZE TABLE TEST_USERS, TEST_POSTS;

-- 기본 데이터베이스로 복귀
USE primavera;