-- ==============================================
-- Primavera Project - 용도별 데이터베이스 초기화 스크립트
-- MariaDB 11.4.7 종합 초기화 스크립트
-- ==============================================

-- 기본 데이터베이스 설정
ALTER DATABASE primavera CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ==============================================
-- 용도별 데이터베이스 생성
-- ==============================================

-- 1. 기본 예제 데이터베이스 (chap03-chap05)
CREATE DATABASE IF NOT EXISTS primavera_basic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 2. MyBatis 예제 데이터베이스 (chap06-chap11)
CREATE DATABASE IF NOT EXISTS primavera_mybatis CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 3. MyBatis 게시판 데이터베이스 (chap12-chap13)
CREATE DATABASE IF NOT EXISTS primavera_mybatis_board CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 4. JPA 고급 데이터베이스 (chap14-chap15)
CREATE DATABASE IF NOT EXISTS primavera_jpa_advanced CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 5. JPA 게시판 데이터베이스 (chap16-chap17)
CREATE DATABASE IF NOT EXISTS primavera_jpa_board CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 6. 마이크로서비스 데이터베이스 (chap18)
CREATE DATABASE IF NOT EXISTS primavera_microservices CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 6. 테스트용 데이터베이스
CREATE DATABASE IF NOT EXISTS primavera_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ==============================================
-- 권한 설정
-- ==============================================

GRANT ALL PRIVILEGES ON primavera.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_basic.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_mybatis.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_mybatis_board.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_jpa_advanced.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_jpa_board.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_microservices.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';
GRANT ALL PRIVILEGES ON primavera_test.* TO 'primavera'@'%' IDENTIFIED BY 'primavera';

FLUSH PRIVILEGES;

-- ==============================================
-- 1. 기본 예제 데이터베이스 (primavera_basic)
-- 대상: chap03, chap04, chap05
-- ==============================================

USE primavera_basic;

-- 기본 사용자 테이블
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 권한 테이블
CREATE TABLE IF NOT EXISTS ROLES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(50) UNIQUE NOT NULL,
    TYPE       INT                NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자-권한 연결 테이블
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 스포츠 수상자 테이블 (테스트용)
CREATE TABLE IF NOT EXISTS WINNERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(50) NOT NULL,
    YEAR       INT         NOT NULL,
    SPORT      VARCHAR(50) NOT NULL,
    PRIZE      VARCHAR(50) NOT NULL,
    AMOUNT     DECIMAL(10, 2) DEFAULT 0.00,
    CREATED_AT DATETIME       DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 기본 데이터 삽입
INSERT INTO ROLES (ID, NAME, TYPE)
VALUES (1, 'ROLE_ADMIN', 1),
       (2, 'ROLE_MANAGER', 2),
       (3, 'ROLE_USER', 3)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS)
VALUES (1, 'genius@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Genius', 'ACTIVE'),
       (2, 'admin@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Admin', 'ACTIVE'),
       (3, 'user@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'User', 'ACTIVE'),
       (4, 'son@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Son', 'ACTIVE'),
       (5, 'messi@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Messi', 'ACTIVE'),
       (6, 'ronaldo@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Ronaldo', 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (1, 1),
       (1, 2),
       (1, 3), -- genius -> all roles
       (2, 1),
       (2, 2), -- admin -> admin, manager
       (3, 3), -- user -> user
       (4, 3),
       (5, 3),
       (6, 3)  -- sports players -> user
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

INSERT INTO WINNERS (NAME, YEAR, SPORT, PRIZE, AMOUNT)
VALUES ('Lionel Messi', 2023, 'Football', 'Ballon d''Or', 1000000.00),
       ('Erling Haaland', 2023, 'Football', 'Golden Boot', 500000.00),
       ('Lewis Hamilton', 2023, 'Formula 1', 'World Championship', 2000000.00),
       ('Serena Williams', 2023, 'Tennis', 'Wimbledon', 750000.00),
       ('Tiger Woods', 2023, 'Golf', 'Masters Tournament', 1500000.00)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

-- ==============================================
-- 2. MyBatis 예제 데이터베이스 (primavera_mybatis)
-- 대상: chap06, chap07, chap11
-- ==============================================

USE primavera_mybatis;

-- 사용자 테이블 (MyBatis 호환)
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     INT                 NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP                    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP                    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_USER_EMAIL (EMAIL),
    INDEX IDX_USER_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 권한 테이블
CREATE TABLE IF NOT EXISTS ROLES
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE INT NOT NULL,
    UNIQUE KEY UK_ROLE_TYPE (TYPE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자-권한 연결 테이블
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 소셜 로그인 연결 정보
CREATE TABLE IF NOT EXISTS USER_CONNECTIONS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL        VARCHAR(100) NOT NULL,
    PROVIDER     INT          NOT NULL,
    PROVIDER_ID  VARCHAR(50)  NOT NULL,
    DISPLAY_NAME VARCHAR(100),
    PROFILE_URL  VARCHAR(255),
    IMAGE_URL    VARCHAR(255),
    ACCESS_TOKEN TEXT,
    EXPIRATION   BIGINT,
    CONSTRAINT FK_USER_CONNECTION_EMAIL FOREIGN KEY (EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE,
    UNIQUE KEY UK_USER_CONNECTION (EMAIL, PROVIDER, PROVIDER_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 게시글 테이블
CREATE TABLE IF NOT EXISTS POSTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    SUBJECT    VARCHAR(255) NOT NULL,
    CONTENTS   TEXT         NOT NULL,
    WRITER_ID  BIGINT       NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_POSTS_WRITER_ID FOREIGN KEY (WRITER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    INDEX IDX_POSTS_WRITER_ID (WRITER_ID),
    INDEX IDX_POSTS_CREATED_AT (CREATED_AT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Single Table Inheritance (Item 계층)
CREATE TABLE IF NOT EXISTS ITEMS
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE   VARCHAR(10)  NOT NULL,
    NAME   VARCHAR(100) NOT NULL,
    PRICE  INT          NOT NULL DEFAULT 0,
    ARTIST VARCHAR(100),
    AUTHOR VARCHAR(100),
    ISBN   VARCHAR(20),
    INDEX IDX_ITEM_TYPE (TYPE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Table Per Class (Contact 계층)
CREATE TABLE IF NOT EXISTS CONTACT_BASE
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE       VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTACT_ADDRESSES
(
    ID      BIGINT PRIMARY KEY,
    COUNTRY VARCHAR(100),
    CITY    VARCHAR(100),
    STREET  VARCHAR(200),
    ZIPCODE VARCHAR(20),
    FOREIGN KEY (ID) REFERENCES CONTACT_BASE (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTACT_EMAILS
(
    ID            BIGINT PRIMARY KEY,
    EMAIL_ADDRESS VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID) REFERENCES CONTACT_BASE (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTACT_MOBILES
(
    ID           BIGINT PRIMARY KEY,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID) REFERENCES CONTACT_BASE (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Joined Strategy (Family 계층)
CREATE TABLE IF NOT EXISTS CANIDAE
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    SPECIES    VARCHAR(100),
    HABITAT    VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS FELIDAE
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    BREED      VARCHAR(100),
    TERRITORY  VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SCINCIDAE
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    LENGTH_CM  INT,
    HABITAT    VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Professor-Student OneToMany
CREATE TABLE IF NOT EXISTS PROFESSORS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    COURSE     VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STUDENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Table Generator 시퀀스
CREATE TABLE IF NOT EXISTS TABLE_SEQ
(
    SEQUENCE_NAME VARCHAR(50) PRIMARY KEY,
    NEXT_VAL      BIGINT NOT NULL DEFAULT 1
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- MyBatis 데이터 삽입
INSERT INTO ROLES (ID, TYPE)
VALUES (1, 1),
       (2, 2),
       (3, 3)
ON DUPLICATE KEY UPDATE TYPE = VALUES(TYPE);

INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS)
VALUES (1, 'genius@primavera.com', '$2a$10$9OUQiTQ6xiR0xYv8G0FGkOGJsY8PLO6LKUEeNXz4ePgN.NChVF6Ja', 'genius', 1),
       (2, 'csj4032@gmail.com', '{noop}password', 'Genius', 1),
       (3, 'admin@primavera.com', '{noop}password', 'Admin', 1)
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (1, 3),
       (2, 3),
       (3, 1)
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

INSERT INTO USER_CONNECTIONS (EMAIL, PROVIDER, PROVIDER_ID, DISPLAY_NAME)
VALUES ('genius@primavera.com', 1, 'genius', 'Genius'),
       ('csj4032@gmail.com', 1, 'genius-choi', 'Genius Choi')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO POSTS (ID, SUBJECT, CONTENTS, WRITER_ID)
VALUES (1, '로마는 하루아침에 이루어지지 않았다.', '제1권 로마는 하루아침에 이루어지지 않았다. 내용...', 1),
       (2, '한니발 전쟁', '제2권 한니발 전쟁 내용...', 1)
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO TABLE_SEQ (SEQUENCE_NAME, NEXT_VAL)
VALUES ('table_generator', 1)
ON DUPLICATE KEY UPDATE NEXT_VAL = VALUES(NEXT_VAL);

-- ==============================================
-- 3. JPA 고급 데이터베이스 (primavera_jpa_advanced)
-- 대상: chap14, chap15 (JPA 관계 매핑, Reactive Programming)
-- ==============================================

USE primavera_jpa_advanced;

-- OneToOne 관계 테이블들
CREATE TABLE IF NOT EXISTS MEMBERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100)        NOT NULL,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ADDRESSES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID   BIGINT       NOT NULL,
    STREET      VARCHAR(255) NOT NULL,
    CITY        VARCHAR(100) NOT NULL,
    POSTAL_CODE VARCHAR(20)  NOT NULL,
    COUNTRY     VARCHAR(100) NOT NULL DEFAULT 'South Korea',
    CREATED_AT  DATETIME              DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS (ID) ON DELETE CASCADE,
    INDEX IDX_MEMBER_ID (MEMBER_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(200)   NOT NULL,
    DESCRIPTION TEXT,
    PRICE       DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    CREATED_AT  DATETIME                DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SERIALS
(
    ID                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID             BIGINT              NOT NULL,
    SERIAL_NUMBER          VARCHAR(100) UNIQUE NOT NULL,
    MANUFACTURE_DATE       DATE                NOT NULL,
    WARRANTY_PERIOD_MONTHS INT      DEFAULT 12,
    CREATED_AT             DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID) ON DELETE CASCADE,
    INDEX IDX_PRODUCT_ID (PRODUCT_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ARTICLES
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE        VARCHAR(255) NOT NULL,
    AUTHOR       VARCHAR(100) NOT NULL,
    PUBLISHED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    STATUS       VARCHAR(20) DEFAULT 'DRAFT'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID BIGINT   NOT NULL,
    BODY       LONGTEXT NOT NULL,
    WORD_COUNT INT      DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID) ON DELETE CASCADE,
    INDEX IDX_ARTICLE_ID (ARTICLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS BOOKS
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE            VARCHAR(255) NOT NULL,
    AUTHOR           VARCHAR(100) NOT NULL,
    PUBLISHER        VARCHAR(100),
    PUBLICATION_DATE DATE,
    PAGES            INT           DEFAULT 0,
    PRICE            DECIMAL(8, 2) DEFAULT 0.00
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ISBNS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID       BIGINT             NOT NULL,
    ISBN_10       VARCHAR(10),
    ISBN_13       VARCHAR(13) UNIQUE NOT NULL,
    ASSIGNED_DATE DATE DEFAULT (CURRENT_DATE),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE,
    INDEX IDX_BOOK_ID (BOOK_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- OneToMany 관계 테이블들
CREATE TABLE IF NOT EXISTS CUSTOMERS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME              VARCHAR(100)        NOT NULL,
    EMAIL             VARCHAR(100) UNIQUE NOT NULL,
    PHONE             VARCHAR(20),
    REGISTRATION_DATE DATE        DEFAULT (CURRENT_DATE),
    STATUS            VARCHAR(20) DEFAULT 'ACTIVE'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTACTS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID   BIGINT       NOT NULL,
    CONTACT_TYPE  VARCHAR(50)  NOT NULL,
    CONTACT_VALUE VARCHAR(255) NOT NULL,
    IS_PRIMARY    BOOLEAN  DEFAULT FALSE,
    CREATED_AT    DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID) ON DELETE CASCADE,
    INDEX IDX_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_CONTACT_TYPE (CONTACT_TYPE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS PROFESSORS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(100)        NOT NULL,
    DEPARTMENT VARCHAR(100)        NOT NULL,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    OFFICE     VARCHAR(50),
    HIRE_DATE  DATE                NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS STUDENTS
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    PROFESSOR_ID    BIGINT,
    STUDENT_NUMBER  VARCHAR(20) UNIQUE  NOT NULL,
    NAME            VARCHAR(100)        NOT NULL,
    MAJOR           VARCHAR(100)        NOT NULL,
    GRADE           INT                 NOT NULL CHECK (GRADE BETWEEN 1 AND 4),
    EMAIL           VARCHAR(100) UNIQUE NOT NULL,
    ENROLLMENT_DATE DATE                NOT NULL,
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSORS (ID) ON DELETE SET NULL,
    INDEX IDX_PROFESSOR_ID (PROFESSOR_ID),
    INDEX IDX_STUDENT_NUMBER (STUDENT_NUMBER)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ManyToOne 관계 테이블들
CREATE TABLE IF NOT EXISTS DEPARTMENTS
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME             VARCHAR(100)       NOT NULL,
    CODE             VARCHAR(10) UNIQUE NOT NULL,
    MANAGER_NAME     VARCHAR(100),
    BUDGET           DECIMAL(15, 2) DEFAULT 0.00,
    ESTABLISHED_DATE DATE               NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    DEPARTMENT_ID   BIGINT              NOT NULL,
    EMPLOYEE_NUMBER VARCHAR(20) UNIQUE  NOT NULL,
    NAME            VARCHAR(100)        NOT NULL,
    POSITION        VARCHAR(100)        NOT NULL,
    SALARY          DECIMAL(10, 2)      NOT NULL,
    HIRE_DATE       DATE                NOT NULL,
    EMAIL           VARCHAR(100) UNIQUE NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (ID) ON DELETE RESTRICT,
    INDEX IDX_DEPARTMENT_ID (DEPARTMENT_ID),
    INDEX IDX_EMPLOYEE_NUMBER (EMPLOYEE_NUMBER)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TEAMS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME         VARCHAR(100) NOT NULL,
    CITY         VARCHAR(100) NOT NULL,
    FOUNDED_YEAR INT          NOT NULL,
    LEAGUE       VARCHAR(100) NOT NULL,
    BUDGET       DECIMAL(15, 2) DEFAULT 0.00
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS PLAYERS
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEAM_ID             BIGINT,
    JERSEY_NUMBER       INT          NOT NULL,
    NAME                VARCHAR(100) NOT NULL,
    POSITION            VARCHAR(50)  NOT NULL,
    AGE                 INT          NOT NULL,
    NATIONALITY         VARCHAR(100)   DEFAULT 'South Korea',
    SALARY              DECIMAL(12, 2) DEFAULT 0.00,
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE   DATE,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID) ON DELETE SET NULL,
    INDEX IDX_TEAM_ID (TEAM_ID),
    INDEX IDX_POSITION (POSITION),
    UNIQUE KEY UNIQUE_TEAM_JERSEY (TEAM_ID, JERSEY_NUMBER)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- ManyToMany 관계 테이블들
CREATE TABLE IF NOT EXISTS BUYERS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME              VARCHAR(100)        NOT NULL,
    COMPANY           VARCHAR(100)        NOT NULL,
    EMAIL             VARCHAR(100) UNIQUE NOT NULL,
    PHONE             VARCHAR(20),
    REGISTRATION_DATE DATE DEFAULT (CURRENT_DATE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SELLERS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME              VARCHAR(100)        NOT NULL,
    COMPANY           VARCHAR(100)        NOT NULL,
    EMAIL             VARCHAR(100) UNIQUE NOT NULL,
    PHONE             VARCHAR(20),
    REGISTRATION_DATE DATE DEFAULT (CURRENT_DATE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTRACTS
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    BUYER_ID        BIGINT             NOT NULL,
    SELLER_ID       BIGINT             NOT NULL,
    CONTRACT_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    AMOUNT          DECIMAL(15, 2)     NOT NULL,
    CURRENCY        VARCHAR(3)  DEFAULT 'KRW',
    CONTRACT_DATE   DATE               NOT NULL,
    DELIVERY_DATE   DATE,
    STATUS          VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT      DATETIME    DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BUYER_ID) REFERENCES BUYERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (SELLER_ID) REFERENCES SELLERS (ID) ON DELETE CASCADE,
    INDEX IDX_BUYER_ID (BUYER_ID),
    INDEX IDX_SELLER_ID (SELLER_ID),
    INDEX IDX_CONTRACT_DATE (CONTRACT_DATE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 상속 계층 구조 테이블들
CREATE TABLE IF NOT EXISTS FAMILY
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME            VARCHAR(100) NOT NULL,
    SCIENTIFIC_NAME VARCHAR(100) NOT NULL,
    HABITAT         VARCHAR(255),
    CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CANIDAE
(
    ID            BIGINT PRIMARY KEY,
    PACK_SIZE     INT DEFAULT 1,
    HUNTING_STYLE VARCHAR(100),
    FOREIGN KEY (ID) REFERENCES FAMILY (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS FELIDAE
(
    ID               BIGINT PRIMARY KEY,
    CLIMBING_ABILITY VARCHAR(50),
    HUNTING_STYLE    VARCHAR(100),
    FOREIGN KEY (ID) REFERENCES FAMILY (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS SCINCIDAE
(
    ID                BIGINT PRIMARY KEY,
    SCALE_TYPE        VARCHAR(50),
    BURROWING_ABILITY VARCHAR(50),
    FOREIGN KEY (ID) REFERENCES FAMILY (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Item 상속 계층 (Single Table Strategy)
CREATE TABLE IF NOT EXISTS ITEMS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    DTYPE          VARCHAR(31)    NOT NULL,
    NAME           VARCHAR(255)   NOT NULL,
    PRICE          DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    STOCK_QUANTITY INT                     DEFAULT 0,
    ARTIST         VARCHAR(100),
    ETC            VARCHAR(255),
    AUTHOR         VARCHAR(100),
    ISBN           VARCHAR(20),
    DIRECTOR       VARCHAR(100),
    ACTOR          VARCHAR(255),
    CREATED_AT     DATETIME                DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_DTYPE (DTYPE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- Contact 상속 계층 (Table Per Class Strategy)
CREATE TABLE IF NOT EXISTS CONTACT_ADDRESSES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL,
    STREET      VARCHAR(255) NOT NULL,
    CITY        VARCHAR(100) NOT NULL,
    POSTAL_CODE VARCHAR(20)  NOT NULL,
    COUNTRY     VARCHAR(100) DEFAULT 'South Korea',
    CREATED_AT  DATETIME     DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS CONTACT_EMAILS
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL,
    EMAIL       VARCHAR(100) NOT NULL,
    IS_VERIFIED BOOLEAN  DEFAULT FALSE,
    DOMAIN      VARCHAR(100),
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- JPA 고급 테스트 데이터
INSERT INTO MEMBERS (ID, NAME, EMAIL)
VALUES (1, '김철수', 'kim@primavera.com'),
       (2, '이영희', 'lee@primavera.com'),
       (3, '박민수', 'park@primavera.com')
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO ADDRESSES (MEMBER_ID, STREET, CITY, POSTAL_CODE)
VALUES (1, '강남대로 123', '서울특별시', '06123'),
       (2, '해운대해변로 456', '부산광역시', '48094'),
       (3, '중앙로 789', '대구광역시', '41911')
ON DUPLICATE KEY UPDATE MEMBER_ID = VALUES(MEMBER_ID);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE)
VALUES ('MacBook Pro', 'Apple 노트북 컴퓨터', 2500000.00),
       ('iPhone 15', 'Apple 스마트폰', 1200000.00),
       ('Galaxy S24', 'Samsung 스마트폰', 1100000.00)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO SERIALS (PRODUCT_ID, SERIAL_NUMBER, MANUFACTURE_DATE)
VALUES (1, 'MBP2024001', '2024-01-15'),
       (2, 'IPH2024001', '2024-02-20'),
       (3, 'GAL2024001', '2024-03-10')
ON DUPLICATE KEY UPDATE PRODUCT_ID = VALUES(PRODUCT_ID);

INSERT INTO FAMILY (NAME, SCIENTIFIC_NAME, HABITAT)
VALUES ('개과', 'Canidae', '전 세계 다양한 서식지'),
       ('고양이과', 'Felidae', '숲, 초원, 사막 등'),
       ('도마뱀과', 'Scincidae', '땅속, 낙엽 아래')
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO CANIDAE (ID, PACK_SIZE, HUNTING_STYLE)
VALUES (1, 8, '무리 사냥')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO FELIDAE (ID, CLIMBING_ABILITY, HUNTING_STYLE)
VALUES (2, '뛰어남', '단독 사냥')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO SCINCIDAE (ID, SCALE_TYPE, BURROWING_ABILITY)
VALUES (3, '매끄러운 비늘', '뛰어남')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO ITEMS (DTYPE, NAME, PRICE, STOCK_QUANTITY, ARTIST, AUTHOR, DIRECTOR)
VALUES ('ALBUM', 'Love Yourself', 25000.00, 100, 'BTS', NULL, NULL),
       ('BOOK', 'Spring Boot 완전정복', 35000.00, 50, NULL, '김개발', NULL),
       ('MOVIE', 'Parasite', 15000.00, 200, NULL, NULL, '봉준호')
ON DUPLICATE KEY UPDATE DTYPE = VALUES(DTYPE);

-- ==============================================
-- 4. MyBatis 게시판 데이터베이스 (primavera_mybatis_board)
-- 대상: chap12, chap13 (계층형 게시판)
-- ==============================================

USE primavera_mybatis_board;

-- 사용자 테이블
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(50)  NOT NULL,
    PASSWORD   VARCHAR(100) NOT NULL,
    NICKNAME   VARCHAR(45)  NOT NULL,
    STATUS     CHAR(1)      NOT NULL DEFAULT 'A',
    CREATED_AT DATETIME     NOT NULL,
    UPDATED_AT DATETIME              DEFAULT NULL,
    UNIQUE KEY EMAIL_UNIQUE (EMAIL)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 권한 테이블
CREATE TABLE IF NOT EXISTS ROLES
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    TYPE TINYINT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자-권한 연결 테이블
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID INT    NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 소셜 로그인 연결 정보
CREATE TABLE IF NOT EXISTS USER_CONNECTIONS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL        VARCHAR(50)  NOT NULL,
    PROVIDER     TINYINT      NOT NULL,
    PROVIDER_ID  VARCHAR(45)  NOT NULL,
    DISPLAY_NAME VARCHAR(45)  DEFAULT NULL,
    PROFILE_URL  VARCHAR(200) DEFAULT NULL,
    IMAGE_URL    VARCHAR(200) DEFAULT NULL,
    ACCESS_TOKEN VARCHAR(200) NOT NULL,
    EXPIRE_TIME  BIGINT       DEFAULT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 게시글 테이블
CREATE TABLE IF NOT EXISTS POSTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    WRITER_ID  BIGINT       NOT NULL,
    SUBJECT    VARCHAR(200) NOT NULL,
    CONTENTS   TEXT         NOT NULL,
    STATUS     TINYINT      NOT NULL,
    CREATED_AT DATETIME DEFAULT NULL,
    UPDATED_AT DATETIME DEFAULT NULL,
    FOREIGN KEY (WRITER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 계층형 아티클 테이블
CREATE TABLE IF NOT EXISTS ARTICLES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    P_ID       BIGINT       NOT NULL DEFAULT 0,
    REFERENCE  BIGINT       NOT NULL,
    STEP       INT          NOT NULL,
    LEVEL      INT          NOT NULL,
    AUTHOR     BIGINT       NOT NULL,
    SUBJECT    VARCHAR(200) NOT NULL,
    STATUS     TINYINT      NOT NULL,
    HIT        INT          NOT NULL DEFAULT 0,
    RECOMMEND  INT          NOT NULL DEFAULT 0,
    DISAPPROVE INT          NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP    NULL     DEFAULT NULL,
    FOREIGN KEY (AUTHOR) REFERENCES USERS (ID) ON DELETE CASCADE,
    INDEX IDX_REFERENCE (REFERENCE),
    INDEX IDX_STEP (STEP),
    INDEX IDX_LEVEL (LEVEL)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 아티클 내용 테이블
CREATE TABLE IF NOT EXISTS ARTICLE_CONTENTS
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID BIGINT DEFAULT NULL,
    CONTENTS   TEXT   DEFAULT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 댓글 테이블 (계층형 구조)
CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID BIGINT      NOT NULL,
    LEVEL      INT         NOT NULL,
    STEP       INT         NOT NULL,
    COMMENT    TEXT        NOT NULL,
    AUTHOR     VARCHAR(45) NOT NULL,
    STATUS     TINYINT     NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP   NULL     DEFAULT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 첨부파일 테이블
CREATE TABLE IF NOT EXISTS ATTACHMENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID BIGINT       NOT NULL,
    NAME       VARCHAR(100) NOT NULL,
    PATH       VARCHAR(200) NOT NULL,
    SIZE       INT          NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP    NULL     DEFAULT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- MyBatis 게시판 데이터
INSERT INTO ROLES (TYPE)
VALUES (1),
       (2),
       (3)
ON DUPLICATE KEY UPDATE TYPE = VALUES(TYPE);

INSERT INTO USERS (EMAIL, PASSWORD, NICKNAME, STATUS, CREATED_AT)
VALUES ('Genius Choi', '{bcrypt}$2a$10$7UEHLpn1r4gZY2qxiZFJ5.7wa3Hdz8IXgxUtFogy0Ac10fh7TG4V.', 'Genius', '1', NOW()),
       ('Son Heung-min', '{bcrypt}$2a$10$7UEHLpn1r4gZY2qxiZFJ5.7wa3Hdz8IXgxUtFogy0Ac10fh7TG4V.', 'Son', '1', NOW()),
       ('Lionel Messi', '{bcrypt}$2a$10$7UEHLpn1r4gZY2qxiZFJ5.7wa3Hdz8IXgxUtFogy0Ac10fh7TG4V.', 'Messi', '1', NOW()),
       ('Cristiano Ronaldo', '{bcrypt}$2a$10$7UEHLpn1r4gZY2qxiZFJ5.7wa3Hdz8IXgxUtFogy0Ac10fh7TG4V.', 'Ronaldo', '1', NOW())
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (2, 1),
       (2, 2),
       (2, 3),
       (3, 1),
       (3, 2),
       (4, 1)
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

INSERT INTO USER_CONNECTIONS (EMAIL, PROVIDER, PROVIDER_ID, DISPLAY_NAME, PROFILE_URL, IMAGE_URL, ACCESS_TOKEN, EXPIRE_TIME)
VALUES ('Genius Choi', 1, '123456789', 'Genius', 'PROFILE', 'IMAGE', '1234567890', -1)
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO ARTICLES (P_ID, REFERENCE, STEP, LEVEL, AUTHOR, SUBJECT, STATUS, HIT)
VALUES (0, 1, 0, 0, 1, 'Spring Boot MyBatis 게시판 만들기', 1, 150),
       (0, 2, 0, 0, 2, '계층형 댓글 시스템 구현', 1, 200),
       (1, 1, 1, 1, 3, 'Re: Spring Boot MyBatis 게시판 만들기', 1, 50),
       (1, 1, 2, 1, 4, 'Re: 추가 질문이 있습니다', 1, 30),
       (3, 1, 3, 2, 1, 'Re: Re: 답변 감사합니다', 1, 20)
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO ARTICLE_CONTENTS (ARTICLE_ID, CONTENTS)
VALUES (1, 'Spring Boot와 MyBatis를 활용한 계층형 게시판 시스템을 구현해보겠습니다. 답글과 대댓글이 가능한 구조로 설계했습니다.'),
       (2, '계층형 댓글 시스템은 STEP과 LEVEL 컬럼을 활용하여 구현할 수 있습니다. 이를 통해 무한 깊이의 댓글이 가능합니다.'),
       (3, '좋은 예제 감사합니다! 혹시 페이징 처리는 어떻게 하나요?'),
       (4, '저도 궁금한게 있는데, 파일 첨부 기능은 어떻게 구현하셨나요?'),
       (5, '페이징은 MyBatis의 RowBounds를 사용하시면 됩니다. 파일 첨부는 별도 테이블로 관리하고 있습니다.')
ON DUPLICATE KEY UPDATE ARTICLE_ID = VALUES(ARTICLE_ID);

-- ==============================================
-- 5. JPA 게시판 데이터베이스 (primavera_jpa_board)
-- 대상: chap16, chap17 (파일 처리, CI/CD 등)
-- ==============================================

USE primavera_jpa_board;

-- 사용자 테이블 (JPA 엔티티 호환)
CREATE TABLE IF NOT EXISTS USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY BIGINT,
    UPDATED_BY BIGINT,
    INDEX IDX_EMAIL (EMAIL),
    INDEX IDX_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 권한 테이블
CREATE TABLE IF NOT EXISTS ROLES
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    TYPE        INT                NOT NULL,
    CREATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 사용자-권한 연결 테이블
CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    BIGINT NOT NULL,
    ROLE_ID    BIGINT NOT NULL,
    GRANTED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    GRANTED_BY BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE,
    FOREIGN KEY (GRANTED_BY) REFERENCES USERS (ID) ON DELETE SET NULL,
    UNIQUE KEY UNIQUE_USER_ROLE (USER_ID, ROLE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 소셜 로그인 연결 정보
CREATE TABLE IF NOT EXISTS USER_CONNECTIONS
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID          BIGINT       NOT NULL,
    PROVIDER_ID      VARCHAR(50)  NOT NULL,
    PROVIDER_USER_ID VARCHAR(100) NOT NULL,
    DISPLAY_NAME     VARCHAR(100),
    PROFILE_URL      VARCHAR(500),
    IMAGE_URL        VARCHAR(500),
    ACCESS_TOKEN     TEXT,
    REFRESH_TOKEN    TEXT,
    EXPIRE_TIME      BIGINT,
    CREATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQUE_PROVIDER_USER (PROVIDER_ID, PROVIDER_USER_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 게시글 테이블 (JPA 엔티티 호환)
CREATE TABLE IF NOT EXISTS POSTS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID     BIGINT       NOT NULL,
    TITLE         VARCHAR(255) NOT NULL,
    CONTENT       LONGTEXT     NOT NULL,
    SUMMARY       TEXT,
    VIEW_COUNT    BIGINT      DEFAULT 0,
    LIKE_COUNT    BIGINT      DEFAULT 0,
    COMMENT_COUNT BIGINT      DEFAULT 0,
    STATUS        VARCHAR(20) DEFAULT 'PUBLISHED',
    PUBLISHED_AT  DATETIME,
    CREATED_AT    DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    INDEX IDX_AUTHOR_ID (AUTHOR_ID),
    INDEX IDX_STATUS (STATUS),
    FULLTEXT IDX_TITLE_CONTENT (TITLE, CONTENT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 댓글 테이블
CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID    BIGINT   NOT NULL,
    PARENT_ID  BIGINT,
    AUTHOR_ID  BIGINT   NOT NULL,
    CONTENT    LONGTEXT NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    LIKE_COUNT BIGINT      DEFAULT 0,
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES POSTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_ID) REFERENCES COMMENTS (ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 파일 처리 테이블 (chap17)
CREATE TABLE IF NOT EXISTS FILE_UPLOADS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID           BIGINT,
    ORIGINAL_FILENAME VARCHAR(255) NOT NULL,
    STORED_FILENAME   VARCHAR(255) NOT NULL,
    FILE_PATH         VARCHAR(500) NOT NULL,
    FILE_SIZE         BIGINT       NOT NULL,
    CONTENT_TYPE      VARCHAR(100),
    FILE_TYPE         VARCHAR(50),                    -- EXCEL, CSV, PDF, IMAGE, etc.
    UPLOAD_STATUS     VARCHAR(20) DEFAULT 'UPLOADED', -- UPLOADED, PROCESSING, PROCESSED, FAILED
    PROCESSED_AT      DATETIME,
    CREATED_AT        DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES POSTS (ID) ON DELETE SET NULL,
    INDEX IDX_POST_ID (POST_ID),
    INDEX IDX_FILE_TYPE (FILE_TYPE),
    INDEX IDX_UPLOAD_STATUS (UPLOAD_STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 파일 처리 결과 테이블
CREATE TABLE IF NOT EXISTS FILE_PROCESSING_RESULTS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_UPLOAD_ID     BIGINT      NOT NULL,
    PROCESSING_TYPE    VARCHAR(50) NOT NULL, -- VALIDATION, EXTRACTION, ANALYSIS
    RESULT_STATUS      VARCHAR(20) NOT NULL, -- SUCCESS, FAILED, WARNING
    RESULT_MESSAGE     TEXT,
    RESULT_DATA        JSON,
    PROCESSED_ROWS     INT      DEFAULT 0,
    ERROR_ROWS         INT      DEFAULT 0,
    PROCESSING_TIME_MS BIGINT   DEFAULT 0,
    CREATED_AT         DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FILE_UPLOAD_ID) REFERENCES FILE_UPLOADS (ID) ON DELETE CASCADE,
    INDEX IDX_FILE_UPLOAD_ID (FILE_UPLOAD_ID),
    INDEX IDX_PROCESSING_TYPE (PROCESSING_TYPE),
    INDEX IDX_RESULT_STATUS (RESULT_STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 재무 데이터 테이블 (Excel 처리 예제)
CREATE TABLE IF NOT EXISTS FINANCIAL_DATA
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_UPLOAD_ID BIGINT,
    COMPANY_CODE   VARCHAR(20)  NOT NULL,
    COMPANY_NAME   VARCHAR(100) NOT NULL,
    FISCAL_YEAR    INT          NOT NULL,
    QUARTER        INT          NOT NULL,
    REVENUE        DECIMAL(15, 2) DEFAULT 0,
    PROFIT         DECIMAL(15, 2) DEFAULT 0,
    ASSETS         DECIMAL(15, 2) DEFAULT 0,
    LIABILITIES    DECIMAL(15, 2) DEFAULT 0,
    EQUITY         DECIMAL(15, 2) DEFAULT 0,
    CREATED_AT     DATETIME       DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FILE_UPLOAD_ID) REFERENCES FILE_UPLOADS (ID) ON DELETE SET NULL,
    INDEX IDX_COMPANY_CODE (COMPANY_CODE),
    INDEX IDX_FISCAL_YEAR (FISCAL_YEAR),
    UNIQUE KEY UNIQUE_COMPANY_QUARTER (COMPANY_CODE, FISCAL_YEAR, QUARTER)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 카카오톡 채팅 데이터 테이블 (CSV 처리 예제)
CREATE TABLE IF NOT EXISTS KAKAOTALK_MESSAGES
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    FILE_UPLOAD_ID  BIGINT,
    CHAT_DATE       DATE         NOT NULL,
    CHAT_TIME       TIME         NOT NULL,
    SENDER_NAME     VARCHAR(100) NOT NULL,
    MESSAGE_TEXT    LONGTEXT     NOT NULL,
    MESSAGE_LENGTH  INT         DEFAULT 0,
    WORD_COUNT      INT         DEFAULT 0,
    SENTIMENT_SCORE DECIMAL(3, 2), -- -1.0 to 1.0
    CONTAINS_EMOJI  BOOLEAN     DEFAULT FALSE,
    CONTAINS_URL    BOOLEAN     DEFAULT FALSE,
    LANGUAGE        VARCHAR(10) DEFAULT 'ko',
    CREATED_AT      DATETIME    DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FILE_UPLOAD_ID) REFERENCES FILE_UPLOADS (ID) ON DELETE SET NULL,
    INDEX IDX_CHAT_DATE (CHAT_DATE),
    INDEX IDX_SENDER_NAME (SENDER_NAME),
    INDEX IDX_SENTIMENT_SCORE (SENTIMENT_SCORE),
    FULLTEXT IDX_MESSAGE_TEXT (MESSAGE_TEXT)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 시스템 로그 테이블 (Sentry 연동)
CREATE TABLE IF NOT EXISTS SYSTEM_LOGS
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOG_LEVEL         VARCHAR(10)  NOT NULL,
    LOGGER_NAME       VARCHAR(255) NOT NULL,
    MESSAGE           LONGTEXT     NOT NULL,
    EXCEPTION_CLASS   VARCHAR(255),
    EXCEPTION_MESSAGE TEXT,
    STACK_TRACE       LONGTEXT,
    USER_ID           BIGINT,
    SESSION_ID        VARCHAR(100),
    REQUEST_URI       VARCHAR(500),
    REQUEST_METHOD    VARCHAR(10),
    USER_AGENT        TEXT,
    CLIENT_IP         VARCHAR(45),
    SERVER_NAME       VARCHAR(100),
    THREAD_NAME       VARCHAR(100),
    SENTRY_EVENT_ID   VARCHAR(100),
    CREATED_AT        DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE SET NULL,
    INDEX IDX_LOG_LEVEL (LOG_LEVEL),
    INDEX IDX_LOGGER_NAME (LOGGER_NAME),
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_CREATED_AT (CREATED_AT),
    INDEX IDX_SENTRY_EVENT_ID (SENTRY_EVENT_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- JPA 게시판 데이터
INSERT INTO ROLES (ID, NAME, DESCRIPTION, TYPE)
VALUES (1, 'ROLE_ADMIN', '시스템 관리자', 1),
       (2, 'ROLE_MANAGER', '매니저', 2),
       (3, 'ROLE_USER', '일반 사용자', 3),
       (4, 'ROLE_GUEST', '게스트', 4)
ON DUPLICATE KEY UPDATE NAME = VALUES(NAME);

INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS)
VALUES (1, 'genius@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Genius', 'ACTIVE'),
       (2, 'admin@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Administrator', 'ACTIVE'),
       (3, 'user@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'User', 'ACTIVE'),
       (4, 'manager@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'Manager', 'ACTIVE')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID, GRANTED_BY)
VALUES (1, 1, NULL),
       (1, 2, NULL),
       (1, 3, NULL),
       (2, 1, 1),
       (2, 2, 1),
       (3, 3, 2),
       (4, 2, 1),
       (4, 3, 1)
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

INSERT INTO USER_CONNECTIONS (USER_ID, PROVIDER_ID, PROVIDER_USER_ID, DISPLAY_NAME)
VALUES (1, 'google', 'google_genius', 'Genius Google'),
       (1, 'github', 'github_genius', 'genius-dev'),
       (2, 'kakao', 'kakao_admin', '관리자'),
       (3, 'facebook', 'facebook_user', '일반사용자')
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

INSERT INTO POSTS (ID, AUTHOR_ID, TITLE, CONTENT, SUMMARY, STATUS, PUBLISHED_AT)
VALUES (1, 1, 'Spring Boot 파일 처리 완벽 가이드', 'Apache POI, Tika, OpenCSV를 활용한 파일 처리 시스템을 구현해보겠습니다. Excel, CSV, PDF 파일을 업로드하고 분석하는 방법을 알아보겠습니다.', 'Spring Boot 파일 처리 시스템 구현', 'PUBLISHED', NOW()),
       (2, 1, 'Sentry를 활용한 에러 모니터링', 'Spring Boot 애플리케이션에 Sentry를 연동하여 실시간 에러 모니터링 시스템을 구축하는 방법을 설명합니다.', 'Sentry 에러 모니터링 시스템', 'PUBLISHED', NOW()),
       (3, 2, 'Reactive Programming with Spring WebFlux', 'Spring WebFlux를 활용한 리액티브 프로그래밍 패턴과 비동기 처리 방법을 다룹니다.', 'Spring WebFlux 리액티브 프로그래밍', 'PUBLISHED', NOW()),
       (4, 3, 'MariaDB 11.4.7 성능 최적화', 'MariaDB 11.4.7의 새로운 기능들과 성능 최적화 방법을 실무 중심으로 설명합니다.', 'MariaDB 성능 최적화 가이드', 'DRAFT', NULL)
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO COMMENTS (POST_ID, AUTHOR_ID, CONTENT, STATUS)
VALUES (1, 2, '파일 처리 예제가 정말 유용하네요! 특히 Chain of Responsibility 패턴 적용 부분이 인상적입니다.', 'ACTIVE'),
       (1, 3, '혹시 대용량 파일 처리는 어떻게 하나요? 메모리 이슈가 있을 것 같은데요.', 'ACTIVE'),
       (1, 1, '대용량 파일은 스트리밍 방식으로 처리하고, 배치 작업으로 나누어 처리하는 것이 좋습니다.', 'ACTIVE'),
       (2, 4, 'Sentry 설정 방법이 정말 자세하게 나와있어서 도움이 많이 되었습니다.', 'ACTIVE'),
       (3, 1, 'WebFlux 예제도 추가해주시면 좋겠어요!', 'ACTIVE')
ON DUPLICATE KEY UPDATE POST_ID = VALUES(POST_ID);

-- 샘플 파일 업로드 데이터
INSERT INTO FILE_UPLOADS (ID, POST_ID, ORIGINAL_FILENAME, STORED_FILENAME, FILE_PATH, FILE_SIZE, CONTENT_TYPE, FILE_TYPE, UPLOAD_STATUS)
VALUES (1, 1, 'financial_data_2024.xlsx', '20240101_financial_data_abc123.xlsx', '/uploads/files/1/', 2048576, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'EXCEL', 'PROCESSED'),
       (2, 1, 'kakaotalk_chat_export.csv', '20240102_kakaotalk_chat_def456.csv', '/uploads/files/2/', 1024000, 'text/csv', 'CSV', 'PROCESSED'),
       (3, 1, 'company_report.pdf', '20240103_company_report_ghi789.pdf', '/uploads/files/3/', 5242880, 'application/pdf', 'PDF', 'UPLOADED')
ON DUPLICATE KEY UPDATE ID = VALUES(ID);

INSERT INTO FINANCIAL_DATA (FILE_UPLOAD_ID, COMPANY_CODE, COMPANY_NAME, FISCAL_YEAR, QUARTER, REVENUE, PROFIT, ASSETS, LIABILITIES, EQUITY)
VALUES (1, 'AAPL', 'Apple Inc.', 2024, 1, 119100000000.00, 30688000000.00, 352755000000.00, 290437000000.00, 62318000000.00),
       (1, 'MSFT', 'Microsoft Corporation', 2024, 1, 61858000000.00, 22291000000.00, 364840000000.00, 198298000000.00, 166542000000.00),
       (1, 'GOOGL', 'Alphabet Inc.', 2024, 1, 80539000000.00, 20687000000.00, 365264000000.00, 106248000000.00, 259016000000.00)
ON DUPLICATE KEY UPDATE FILE_UPLOAD_ID = VALUES(FILE_UPLOAD_ID);

INSERT INTO KAKAOTALK_MESSAGES (FILE_UPLOAD_ID, CHAT_DATE, CHAT_TIME, SENDER_NAME, MESSAGE_TEXT, MESSAGE_LENGTH, WORD_COUNT, SENTIMENT_SCORE)
VALUES (2, '2024-01-01', '10:30:00', '김철수', '새해 복 많이 받으세요! 올해도 좋은 일만 가득하길 바랍니다.', 32, 10, 0.8),
       (2, '2024-01-01', '10:31:15', '이영희', '감사합니다! 김철수님도 새해 복 많이 받으세요 ^^', 28, 8, 0.9),
       (2, '2024-01-01', '14:22:30', '박민수', '오늘 날씨가 정말 춥네요. 모두 감기 조심하세요!', 26, 8, 0.3),
       (2, '2024-01-02', '09:15:45', '김철수', '어제 프로젝트 회의는 어떠셨나요?', 19, 5, 0.1),
       (2, '2024-01-02', '09:20:12', '이영희', '생각보다 잘 진행된 것 같아요. 다음 단계 계획도 구체적이고요.', 34, 11, 0.6)
ON DUPLICATE KEY UPDATE FILE_UPLOAD_ID = VALUES(FILE_UPLOAD_ID);

-- ==============================================
-- 6. 마이크로서비스 데이터베이스 (primavera_microservices)
-- 대상: chap18 (마이크로서비스 아키텍처)
-- ==============================================

USE primavera_microservices;

-- 마이크로서비스용 기본 사용자 테이블
CREATE TABLE IF NOT EXISTS MS_USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255)        NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    STATUS     VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    SERVICE_ID VARCHAR(50)         NOT NULL, -- 서비스 식별자
    INDEX IDX_MS_EMAIL (EMAIL),
    INDEX IDX_MS_STATUS (STATUS),
    INDEX IDX_MS_SERVICE_ID (SERVICE_ID)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 주문 서비스 테이블
CREATE TABLE IF NOT EXISTS MS_ORDERS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_NUMBER   VARCHAR(50) UNIQUE NOT NULL,
    USER_ID        BIGINT             NOT NULL,
    TOTAL_AMOUNT   DECIMAL(12, 2)     NOT NULL,
    ORDER_STATUS   VARCHAR(20) DEFAULT 'PENDING',
    PAYMENT_STATUS VARCHAR(20) DEFAULT 'UNPAID',
    CREATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES MS_USERS (ID) ON DELETE CASCADE,
    INDEX IDX_MS_ORDER_NUMBER (ORDER_NUMBER),
    INDEX IDX_MS_ORDER_STATUS (ORDER_STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 상품 서비스 테이블
CREATE TABLE IF NOT EXISTS MS_PRODUCTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_CODE VARCHAR(50) UNIQUE NOT NULL,
    NAME         VARCHAR(255)       NOT NULL,
    DESCRIPTION  TEXT,
    PRICE        DECIMAL(10, 2)     NOT NULL,
    STOCK        INT         DEFAULT 0,
    STATUS       VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT   DATETIME    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_MS_PRODUCT_CODE (PRODUCT_CODE),
    INDEX IDX_MS_PRODUCT_STATUS (STATUS)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 계정 서비스 테이블
CREATE TABLE IF NOT EXISTS MS_ACCOUNTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID      BIGINT      NOT NULL,
    ACCOUNT_TYPE VARCHAR(20) NOT NULL, -- SAVINGS, CHECKING, CREDIT
    BALANCE      DECIMAL(15, 2) DEFAULT 0.00,
    CURRENCY     VARCHAR(3)     DEFAULT 'KRW',
    STATUS       VARCHAR(20)    DEFAULT 'ACTIVE',
    CREATED_AT   DATETIME       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES MS_USERS (ID) ON DELETE CASCADE,
    INDEX IDX_MS_ACCOUNT_USER_ID (USER_ID),
    INDEX IDX_MS_ACCOUNT_TYPE (ACCOUNT_TYPE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 마이크로서비스 데이터 삽입
INSERT INTO MS_USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS, SERVICE_ID)
VALUES (1, 'front@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'FrontUser', 'ACTIVE', 'front-service'),
       (2, 'account@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'AccountUser', 'ACTIVE', 'account-service'),
       (3, 'product@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'ProductUser', 'ACTIVE', 'product-service'),
       (4, 'order@primavera.com', '{bcrypt}$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'OrderUser', 'ACTIVE', 'order-service')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO MS_PRODUCTS (PRODUCT_CODE, NAME, DESCRIPTION, PRICE, STOCK)
VALUES ('PRD001', 'Spring Boot 완전정복', 'Spring Boot 교육서적', 35000.00, 100),
       ('PRD002', 'Java 프로그래밍 마스터', 'Java 고급 프로그래밍 가이드', 42000.00, 50),
       ('PRD003', 'Microservices 아키텍처', '마이크로서비스 설계 패턴', 38000.00, 75)
ON DUPLICATE KEY UPDATE PRODUCT_CODE = VALUES(PRODUCT_CODE);

INSERT INTO MS_ACCOUNTS (USER_ID, ACCOUNT_TYPE, BALANCE, CURRENCY)
VALUES (1, 'CHECKING', 1000000.00, 'KRW'),
       (2, 'SAVINGS', 5000000.00, 'KRW'),
       (3, 'CHECKING', 2500000.00, 'KRW'),
       (4, 'SAVINGS', 3000000.00, 'KRW')
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);

-- ==============================================
-- 7. 테스트용 데이터베이스 (primavera_test)
-- ==============================================

USE primavera_test;

-- 테스트용 기본 테이블들 (간소화)
CREATE TABLE IF NOT EXISTS TEST_USERS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) UNIQUE NOT NULL,
    NICKNAME   VARCHAR(50)         NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TEST_POSTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_ID  BIGINT       NOT NULL,
    TITLE      VARCHAR(255) NOT NULL,
    CONTENT    TEXT         NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AUTHOR_ID) REFERENCES TEST_USERS (ID) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

-- 테스트 데이터
INSERT INTO TEST_USERS (EMAIL, NICKNAME)
VALUES ('test1@example.com', 'Tester1'),
       ('test2@example.com', 'Tester2'),
       ('test3@example.com', 'Tester3')
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO TEST_POSTS (AUTHOR_ID, TITLE, CONTENT)
VALUES (1, 'Test Post 1', 'This is a test content for automated testing.'),
       (1, 'Test Post 2', 'Another test content with different data.'),
       (2, 'Test Post 3', 'User 2 test content for validation.'),
       (3, 'Test Post 4', 'Final test content for comprehensive testing.')
ON DUPLICATE KEY UPDATE AUTHOR_ID = VALUES(AUTHOR_ID);

-- ==============================================
-- 데이터베이스별 용도 및 모듈 매핑 정보
-- ==============================================

-- 1. primavera_basic (기본 예제 데이터베이스)
--    - chap03: 기본 Spring Boot 설정 및 테스트
--    - chap04: 사용자 관리 및 보안 기초
--    - chap05: 기본 웹 애플리케이션 구조
--    
-- 2. primavera_mybatis (MyBatis 예제 데이터베이스)
--    - chap06: MyBatis 기본 설정 및 매핑
--    - chap07: MyBatis 고급 기능 (동적 쿼리, 커스텀 TypeHandler)
--    - chap11: MyBatis 최적화 및 성능 튜닝
--    
-- 3. primavera_mybatis_board (MyBatis 게시판 데이터베이스)
--    - chap12: MyBatis 기반 계층형 게시판 구현
--    - chap13: MyBatis 기반 고급 게시판 기능 (검색, 정렬, 페이징)
--    
-- 4. primavera_jpa_advanced (JPA 고급 데이터베이스)
--    - chap14: JPA 관계 매핑 (OneToOne, OneToMany, ManyToOne, ManyToMany)
--    - chap15: Reactive Programming (Spring WebFlux, R2DBC)
--    
-- 5. primavera_jpa_board (JPA 게시판 데이터베이스)
--    - chap16: 파일 처리 시스템 (Excel, CSV, PDF)
--    - chap17: CI/CD 및 배포 자동화
--    
-- 6. primavera_microservices (마이크로서비스 데이터베이스)
--    - chap18: 마이크로서비스 아키텍처 (Front, Account, Product, Configuration)
--    
-- 7. primavera_test (테스트용 데이터베이스)
--    - 모든 모듈의 TestContainers 기반 통합 테스트
--    - CI/CD 파이프라인에서 사용

-- ==============================================
-- 인덱스 최적화
-- ==============================================

-- 각 데이터베이스별로 테이블 분석 실행
USE primavera_basic;
ANALYZE TABLE USERS, ROLES, USER_ROLES, WINNERS;

USE primavera_mybatis;
ANALYZE TABLE USERS, ROLES, USER_ROLES, POSTS, ITEMS;

USE primavera_jpa_advanced;
ANALYZE TABLE MEMBERS, ADDRESSES, PRODUCTS, SERIALS, ARTICLES, CONTENTS;

USE primavera_mybatis_board;
ANALYZE TABLE USERS, ARTICLES, ARTICLE_CONTENTS, COMMENTS;

USE primavera_jpa_board;
ANALYZE TABLE USERS, POSTS, COMMENTS, FILE_UPLOADS, FINANCIAL_DATA;

USE primavera_test;
ANALYZE TABLE TEST_USERS, TEST_POSTS;

-- 기본 데이터베이스로 복귀
USE primavera;