version: '3.8'

services:
  mariadb:
    image: mariadb:11.4.7
    container_name: mariadb-primavera
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: primavera
      MARIADB_USER: primavera
      MARIADB_PASSWORD: primavera
      MARIADB_AUTO_UPGRADE: 1
    ports:
      - "1109:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
    driver: local