spring:
  application:
    name: FrontApplication
  profiles:
    active: local
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
      test:
        - console-appender
  jackson:
    time-zone: UTC
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 8081
  tomcat:
    threads:
      max: 1

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  config: classpath:logback-spring.xml

primavera:
  config:
    name: front
    enabled: true
    logs:
      path: ./logs/${primavera.config.name}
