
// chap12: Web + MyBatis + File Upload + Thymeleaf
dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation "org.springframework.boot:spring-boot-starter-security"
    implementation "org.springframework.boot:spring-boot-starter-oauth2-client"
    implementation "org.modelmapper:modelmapper:${modelMapperVersion}"
    implementation project(":appendix:spring-boot-starter-lucy-filter")
    databaseDependencies.each { dep -> implementation dep }
    mybatisDependencies.each { dep -> implementation dep }
    thymeleafDependencies.each { dep -> implementation dep }
    
    // File Upload 지원
    implementation "commons-io:commons-io:${commonsIoVersion}"
    implementation "commons-codec:commons-codec:${commonsCodecVersion}"
    
    testContainersDependencies.each { dep -> testImplementation dep }
}