spring:
  application:
    name: FileProcessingMonitoringApplication
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  profiles:
    group:
      local:
        - console-appender
        - file-debug-appender
        - file-error-appender
        - file-info-appender
        - file-warn-appender
        - sentry-appender
      test:
        - console-appender
  jackson:
    time-zone: UTC
  jmx:
    enabled: false

logging:
  config: classpath:logback-spring.xml

primavera:
  config:
    name: primavera
    enabled: true
    logs:
      path: ./logs

sentry:
  dns: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:local}
  release: ${SENTRY_RELEASE:0.0.1-SNAPSHOT}
  servername: ${SENTRY_SERVER_NAME:FileProcessingMonitoringApplication}