dependencies {
    implementation "com.monitorjbl:xlsx-streamer:${xlsxStreamerVersion}"
    implementation "com.opencsv:opencsv:${openCsvVersion}"
    implementation "com.zaxxer:HikariCP:${hikariCPVersion}"
    implementation "commons-io:commons-io:${commonsIoVersion}"
    implementation "io.awspring.cloud:spring-cloud-aws-starter:${springCloudAwsVersion}"
    implementation "io.awspring.cloud:spring-cloud-aws-starter-s3:${springCloudAwsVersion}"
    implementation "io.sentry:sentry:${sentryVersion}"
    implementation "org.apache.commons:commons-lang3:${commonsLang3Version}"
    implementation "org.apache.poi:poi:${poiVersion}"
    implementation "org.apache.poi:poi-ooxml:${poiVersion}"
    implementation "org.apache.tika:tika-core:${tikaVersion}"
    implementation "org.apache.tika:tika-parsers:${tikaVersion}"
    implementation "org.javatuples:javatuples:${javatuplesVersion}"
    implementation "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    implementation "org.openkoreantext:open-korean-text:${openKoreanTextVersion}"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springframework.cloud:spring-cloud-starter-vault-config:${springCloudVaultVersion}"
    testImplementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    testImplementation "org.testcontainers:localstack:${testContainersVersion}"
    testImplementation "software.amazon.awssdk:auth:${awsSdkVersion}"
    testImplementation "software.amazon.awssdk:core:${awsSdkVersion}"
    testImplementation "software.amazon.awssdk:regions:${awsSdkVersion}"
    testImplementation "software.amazon.awssdk:s3:${awsSdkVersion}"
    testImplementation project(':appendix:spring-boot-starter-test-containers')
}