CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(50) NOT NULL,
    STATUS INT NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_email (EMAIL),
    INDEX idx_user_status (STATUS)
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE INT NOT NULL,
    UNIQUE KEY uk_role_type (TYPE)
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
);

INSERT INTO ROLES (ID, TYPE) VALUES
(1, 1), -- ADMINISTRATOR
(2, 2), -- MANAGER
(3, 3)  -- USER
ON DUPLICATE KEY UPDATE TYPE = VALUES(TYPE);

INSERT INTO USERS (ID, EMAIL, PASSWORD, NICKNAME, STATUS, CREATED_AT, UPDATED_AT) VALUES
(1, 'genius@gmail.com', '$2a$10$N8kKAJz4rT8d.JLZ8QqC6O8.YhJQrGeFGRqF2QhPZKJf3ZcJwQq7e', 'genius', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE EMAIL = VALUES(EMAIL);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES
(1, 3)
ON DUPLICATE KEY UPDATE USER_ID = VALUES(USER_ID);