-- chap06 Database Schema
-- MySQL Database Schema for Primavera Application

-- Create database
CREATE DATABASE IF NOT EXISTS primavera DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE primavera;

CREATE TABLE IF NOT EXISTS USERS
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    email      VARCHAR(100) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    nickname   VARCHAR(50)  NOT NULL,
    status     INT          NOT NULL DEFAULT 1,
    created_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_email (email),
    INDEX idx_user_status (status)
);

CREATE TABLE IF NOT EXISTS ROLES
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    type INT NOT NULL,
    UNIQUE KEY uk_role_type (type)
);

CREATE TABLE IF NOT EXISTS USER_ROLE
(
    user_id BIGINT NOT NULL,
    role_id INT    NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES ROLES (id) ON DELETE CASCADE
);

-- Single Table Inheritance Strategy (Item hierarchy)
CREATE TABLE IF NOT EXISTS ITEM
(
    id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE   VARCHAR(10)  NOT NULL,
    name   VARCHAR(100) NOT NULL,
    price  INT          NOT NULL DEFAULT 0,
    ARTIST VARCHAR(100),
    AUTHOR VARCHAR(100),
    ISBN   VARCHAR(20),
    INDEX idx_item_type (TYPE)
);

CREATE TABLE IF NOT EXISTS CONTACT
(
    id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE   VARCHAR(10) NOT NULL,
    reg_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mod_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ADDRESS
(
    id      BIGINT PRIMARY KEY,
    country VARCHAR(100),
    city    VARCHAR(100),
    street  VARCHAR(200),
    zipcode VARCHAR(20),
    FOREIGN KEY (id) REFERENCES CONTACT (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EMAIL
(
    id            BIGINT PRIMARY KEY,
    email_address VARCHAR(100) NOT NULL,
    FOREIGN KEY (id) REFERENCES CONTACT (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MOBILE
(
    id           BIGINT PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL,
    FOREIGN KEY (id) REFERENCES CONTACT (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TABLE_SEQ
(
    sequence_name VARCHAR(50) PRIMARY KEY,
    next_val      BIGINT NOT NULL DEFAULT 1
);

INSERT INTO TABLE_SEQ (sequence_name, next_val)
VALUES ('table_generator', 1)
ON DUPLICATE KEY UPDATE next_val = next_val;

CREATE TABLE IF NOT EXISTS CANIDAE
(
    id         BIGINT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    species    VARCHAR(100),
    habitat    VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS FELIDAE
(
    id         BIGINT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    breed      VARCHAR(100),
    territory  VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS SCINCIDAE
(
    id         BIGINT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    length_cm  INT,
    habitat    VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS PROFESSOR
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    course     VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS STUDENT
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    department VARCHAR(100)
);

-- Insert initial data
INSERT INTO ROLES (id, type)
VALUES (1, 1), -- ADMINISTRATOR
       (2, 2), -- MANAGER
       (3, 3)  -- USER
ON DUPLICATE KEY UPDATE type = VALUES(type);