CREATE DATABASE IF NOT EXISTS primavera CHARACTER SET utf8 COLLATE utf8_general_ci;
USE primavera;

CREATE TABLE IF NOT EXISTS USER
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(255) NOT NULL,
    NICKNAME   VARCHAR(50)  NOT NULL,
    STATUS     INT          NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_USER_EMAIL (EMAIL),
    INDEX IDX_USER_STATUS (STATUS)
);


CREATE TABLE IF NOT EXISTS POSTS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    SUBJECT    VARCHAR(255) NOT NULL,
    CONTENTS   TEXT         NOT NULL,
    WRITER_ID  BIGINT       NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_POSTS_WRITER_ID FOREIGN KEY (WRITER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    INDEX IDX_POSTS_WRITER_ID (WRITER_ID),
    INDEX IDX_POSTS_CREATED_AT (CREATED_AT)
);

CREATE TABLE IF NOT EXISTS USER_CONNECTION
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL        VARCHAR(100) NOT NULL,
    PROVIDER     INT          NOT NULL,
    PROVIDER_ID  VARCHAR(50)  NOT NULL,
    DISPLAY_NAME VARCHAR(100),
    PROFILE_URL  VARCHAR(255),
    IMAGE_URL    VARCHAR(255),
    ACCESS_TOKEN TEXT,
    EXPIRATION   BIGINT,
    CONSTRAINT FK_USER_CONNECTION_EMAIL FOREIGN KEY (EMAIL) REFERENCES USER (EMAIL) ON DELETE CASCADE,
    UNIQUE KEY UK_USER_CONNECTION (EMAIL, PROVIDER, PROVIDER_ID)
);

CREATE TABLE IF NOT EXISTS ROLE
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE INT NOT NULL UNIQUE,
    INDEX IDX_ROLE_TYPE (TYPE)
);

CREATE TABLE IF NOT EXISTS USER_ROLE
(
    ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT FK_USER_ROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ID) ON DELETE CASCADE,
    UNIQUE KEY UK_USER_ROLE (USER_ID, ROLE_ID),
    INDEX IDX_USER_ROLE_USER_ID (USER_ID),
    INDEX IDX_USER_ROLE_ROLE_ID (ROLE_ID)
);

-- Insert test data
INSERT IGNORE INTO USER (ID, EMAIL, PASSWORD, NICKNAME, STATUS) VALUES
(1, 'csj4032@gmail.com', '{noop}password', 'Genius', 1),
(2, 'Genius Choi', '{noop}password', 'Genius Choi', 1);

INSERT IGNORE INTO USER_CONNECTION (EMAIL, PROVIDER, PROVIDER_ID, DISPLAY_NAME) VALUES
('csj4032@gmail.com', 1, 'genius', 'Genius'),
('Genius Choi', 1, 'genius-choi', 'Genius Choi');

INSERT IGNORE INTO ROLE (ID, TYPE) VALUES
(1, 1), -- ADMINISTRATOR
(2, 2), -- MANAGER  
(3, 3); -- USER

INSERT IGNORE INTO USER_ROLE (USER_ID, ROLE_ID) VALUES
(1, 3), -- Assign USER role to genius
(2, 3); -- Assign USER role to Genius Choi

INSERT IGNORE INTO POSTS (ID, SUBJECT, CONTENTS, WRITER_ID) VALUES
(1, '로마는 하루아침에 이루어지지 않았다.', '제1권 로마는 하루아침에 이루어지지 않았다. 내용...', 1),
(2, '한니발 전쟁', '제2권 한니발 전쟁 내용...', 1);