CREATE TABLE IF NOT EXISTS USER
(
    ID       BIGINT       NOT NULL AUTO_INCREMENT,
    EMAIL    VARCHAR(50)  NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NICKNAME VARCHAR(45)  NOT NULL,
    STATUS   CHAR(1)      NOT NULL DEFAULT 'A',
    CREATED_AT   TIMESTAMP    NOT NULL,
    UPDATED_AT   TIMESTAMP    DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX EMAIL_UNIQUE ON USER(EMAIL);

CREATE TABLE IF NOT EXISTS USER_CONNECTION
(
    ID           BIGINT       NOT NULL AUTO_INCREMENT,
    EMAIL        VARCHAR(50)  NOT NULL,
    PROVIDER     TINYINT      NOT NULL,
    PROVIDER_ID  VARCHAR(45)  NOT NULL,
    DISPLAY_NAME VARCHAR(45)  DEFAULT NULL,
    PROFILE_URL  VARCHAR(200) DEFAULT NULL,
    IMAGE_URL    VARCHAR(200) DEFAULT NULL,
    ACCESS_TOKEN VARCHAR(200) NOT NULL,
    EXPIRE_TIME  BIGINT       DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ROLE
(
    ID   INT         NOT NULL AUTO_INCREMENT,
    TYPE TINYINT     NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID INT    NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

CREATE TABLE IF NOT EXISTS POST
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    WRITER_ID BIGINT       NOT NULL,
    SUBJECT   VARCHAR(200) NOT NULL,
    CONTENTS  TEXT         NOT NULL,
    STATUS    TINYINT      NOT NULL,
    CREATED_AT    TIMESTAMP    DEFAULT NULL,
    UPDATED_AT    TIMESTAMP    DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ARTICLE
(
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    P_ID       BIGINT       NOT NULL DEFAULT 0,
    REFERENCE  BIGINT       NOT NULL,
    STEP       INT          NOT NULL,
    LEVEL      INT          NOT NULL,
    AUTHOR     BIGINT       NOT NULL,
    SUBJECT    VARCHAR(200) NOT NULL,
    STATUS     TINYINT      NOT NULL,
    HIT        INT          NOT NULL DEFAULT 0,
    RECOMMEND  INT          NOT NULL DEFAULT 0,
    DISAPPROVE INT          NOT NULL DEFAULT 0,
    CREATED_AT     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     TIMESTAMP    NULL     DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ARTICLE_CONTENT
(
    ID         INT    NOT NULL AUTO_INCREMENT,
    ARTICLE_ID BIGINT DEFAULT NULL,
    CONTENTS   TEXT   DEFAULT NULL,
    PRIMARY KEY (ID)
);

-- Insert test data
INSERT INTO ROLE (TYPE) VALUES (1);
INSERT INTO ROLE (TYPE) VALUES (2);
INSERT INTO ROLE (TYPE) VALUES (3);

INSERT INTO USER(EMAIL, PASSWORD, NICKNAME, STATUS, CREATED_AT)
VALUES ('Genius Choi', '{bcrypt}$2a$10$7UEHLpn1r4gZY2qxiZFJ5.7wa3Hdz8IXgxUtFogy0Ac10fh7TG4V.', 'Genius', '1', CURRENT_TIMESTAMP);

INSERT INTO USER_CONNECTION(EMAIL, PROVIDER, PROVIDER_ID, DISPLAY_NAME, PROFILE_URL, IMAGE_URL, ACCESS_TOKEN, EXPIRE_TIME)
VALUES ('Genius Choi', 1, '123456789', 'Genius', 'PROFILE', 'IMAGE', '1234567890', -1);

INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (1, 3);

INSERT INTO USER(EMAIL, PASSWORD, NICKNAME, STATUS, CREATED_AT)
VALUES ('Son Heung-min', '{bcrypt}$2a$10$7UEHLpn1r4gZY2qxiZFJ5.7wa3Hdz8IXgxUtFogy0Ac10fh7TG4V.', 'Son', '1', CURRENT_TIMESTAMP);

INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES (2, 3);