dependencies {
    implementation "co.elastic.clients:elasticsearch-java:${elasticsearchVersion}"
    implementation "io.debezium:debezium-embedded:${debeziumVersion}"
    implementation "io.debezium:debezium-connector-mariadb:${debeziumVersion}"
    implementation "org.apache.kafka:connect-api:${kafkaConnectVersion}"
    implementation "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    implementation "org.springframework.boot:spring-boot-starter-webflux"
    implementation('org.springframework.boot:spring-boot-starter-websocket') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
    }
    implementation "org.springframework.cloud:spring-cloud-starter-config"
    implementation "org.springframework.cloud:spring-cloud-starter-vault-config:${springCloudVaultVersion}"
    implementation "org.springframework.boot:spring-boot-starter-data-elasticsearch"
    implementation project(':chap17:common')
    testImplementation "io.debezium:debezium-embedded:${debeziumVersion}"
    testImplementation "io.projectreactor:reactor-test:${reactorTestVersion}"
    testImplementation "io.rest-assured:rest-assured:${restAssuredVersion}"
    testImplementation "org.awaitility:awaitility:${awaitilityVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.boot:spring-boot-testcontainers"
    testImplementation "org.springframework.boot:spring-boot-starter-webflux"
    testImplementation "org.testcontainers:elasticsearch:${testContainersVersion}"
    testImplementation "org.testcontainers:junit-jupiter:${testContainersVersion}"
    testImplementation "org.testcontainers:kafka:${testContainersVersion}"
    testImplementation "org.testcontainers:mariadb:${testContainersVersion}"
    testImplementation "org.testcontainers:testcontainers:${testContainersVersion}"
    testImplementation "org.mariadb.jdbc:mariadb-java-client:${mariadbVersion}"
    testImplementation project(':appendix:spring-boot-starter-test-containers')
}