spring:
  application:
    name: product
  cloud:
    config:
      uri: http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27017
      database: primavera_products
      username: root
      password: primavera
      authentication-database: admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

kafka:
  topics:
    order-events: order-events
    inventory-events: inventory-events

server:
  tomcat:
    threads:
      max: 1
  port: 8083

logging:
  level:
    org.springframework: DEBUG
    com.genius.primavera: info