spring:
  application:
    name: product
  cloud:
    config:
      uri: http://localhost:8888
  data:
    mongodb:
      host: localhost
      port: 27017
      database: primavera_products
      username: root
      password: primavera
      authentication-database: admin

server:
  tomcat:
    threads:
      max: 1
  port: 8083

logging:
  level:
    org.springframework: DEBUG