dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web") {
        exclude module: "spring-boot-starter-tomcat"
    }
    implementation "org.springframework.boot:spring-boot-starter-undertow"
    aopDependencies.each { dep -> implementation dep }
    databaseDependencies.each { dep -> implementation dep }
    mybatisDependencies.each { dep -> implementation dep }
    thymeleafDependencies.each { dep -> implementation dep }
    validationDependencies.each { dep -> implementation dep }
    developmentDependencies.each { dep -> implementation dep }
    loggingDependencies.each { dep -> implementation dep }
    webUiDependencies.each { dep -> implementation dep }
    testContainersDependencies.each { dep -> testImplementation dep }
    implementation "org.springframework.cloud:spring-cloud-starter-vault-config:${springCloudVaultVersion}"
    implementation "org.springframework.cloud:spring-cloud-vault-config-databases:${springCloudVaultVersion}"
    implementation "org.springframework.security:spring-security-core:${springSecurityVersion}"
    implementation "org.springframework.security:spring-security-crypto:${springSecurityVersion}"
    implementation "org.springframework.security:spring-security-web:${springSecurityVersion}"
    implementation "org.hibernate:hibernate-core:${hibernateVersion}"
    implementation project(":appendix:spring-boot-starter-lucy-filter")
    testImplementation project(":appendix:spring-boot-starter-lucy-filter")
}